// Code generated by tushare-gen. DO NOT EDIT.

package stock_financial

import (
	"context"
	"fmt"

	"tushare-go/pkg/sdk"
)

// DividendRequest 表示 分红送股数据 API 的请求
type DividendRequest struct {
	TsCode string `json:"ts_code,omitempty"` // TS代码
	AnnDate string `json:"ann_date,omitempty"` // 公告日
	RecordDate string `json:"record_date,omitempty"` // 股权登记日期
	ExDate string `json:"ex_date,omitempty"` // 除权除息日
	ImpAnnDate string `json:"imp_ann_date,omitempty"` // 实施公告日
}

// DividendItem 表示单个 分红送股数据 数据项
type DividendItem struct {
	TsCode string `json:"ts_code"` // TS代码
	EndDate string `json:"end_date"` // 分红年度
	AnnDate string `json:"ann_date"` // 预案公告日
	DivProc string `json:"div_proc"` // 实施进度
	StkDiv float64 `json:"stk_div"` // 每股送转
	StkBoRate float64 `json:"stk_bo_rate"` // 每股送股比例
	StkCoRate float64 `json:"stk_co_rate"` // 每股转增比例
	CashDiv float64 `json:"cash_div"` // 每股分红（税后）
	CashDivTax float64 `json:"cash_div_tax"` // 每股分红（税前）
	RecordDate string `json:"record_date"` // 股权登记日
	ExDate string `json:"ex_date"` // 除权除息日
	PayDate string `json:"pay_date"` // 派息日
	DivListdate string `json:"div_listdate"` // 红股上市日
	ImpAnnDate string `json:"imp_ann_date"` // 实施公告日
	BaseDate string `json:"base_date"` // 基准日
	BaseShare float64 `json:"base_share"` // 基准股本（万）
}

// Dividend 调用 分红送股数据 API
func Dividend(ctx context.Context, client *sdk.Client, req *DividendRequest) ([]DividendItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.AnnDate != "" {
		params["ann_date"] = req.AnnDate
	}
	if req.RecordDate != "" {
		params["record_date"] = req.RecordDate
	}
	if req.ExDate != "" {
		params["ex_date"] = req.ExDate
	}
	if req.ImpAnnDate != "" {
		params["imp_ann_date"] = req.ImpAnnDate
	}

	fields := []string{"ts_code", "end_date", "ann_date", "div_proc", "stk_div", "stk_bo_rate", "stk_co_rate", "cash_div", "cash_div_tax", "record_date", "ex_date", "pay_date", "div_listdate", "imp_ann_date", "base_date", "base_share"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "dividend", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]DividendItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 ts_code 的简单类型
		tsCode, ok := item["ts_code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 end_date 的简单类型
		endDate, ok := item["end_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 end_date 类型")
		}
		// 处理 ann_date 的简单类型
		annDate, ok := item["ann_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ann_date 类型")
		}
		// 处理 div_proc 的简单类型
		divProc, ok := item["div_proc"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 div_proc 类型")
		}
		// 处理 stk_div 的简单类型
		stkDiv, ok := item["stk_div"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 stk_div 类型")
		}
		// 处理 stk_bo_rate 的简单类型
		stkBoRate, ok := item["stk_bo_rate"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 stk_bo_rate 类型")
		}
		// 处理 stk_co_rate 的简单类型
		stkCoRate, ok := item["stk_co_rate"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 stk_co_rate 类型")
		}
		// 处理 cash_div 的简单类型
		cashDiv, ok := item["cash_div"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 cash_div 类型")
		}
		// 处理 cash_div_tax 的简单类型
		cashDivTax, ok := item["cash_div_tax"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 cash_div_tax 类型")
		}
		// 处理 record_date 的简单类型
		recordDate, ok := item["record_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 record_date 类型")
		}
		// 处理 ex_date 的简单类型
		exDate, ok := item["ex_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ex_date 类型")
		}
		// 处理 pay_date 的简单类型
		payDate, ok := item["pay_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 pay_date 类型")
		}
		// 处理 div_listdate 的简单类型
		divListdate, ok := item["div_listdate"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 div_listdate 类型")
		}
		// 处理 imp_ann_date 的简单类型
		impAnnDate, ok := item["imp_ann_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 imp_ann_date 类型")
		}
		// 处理 base_date 的简单类型
		baseDate, ok := item["base_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 base_date 类型")
		}
		// 处理 base_share 的简单类型
		baseShare, ok := item["base_share"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 base_share 类型")
		}
		items[i] = DividendItem{
			TsCode: tsCode,
			EndDate: endDate,
			AnnDate: annDate,
			DivProc: divProc,
			StkDiv: stkDiv,
			StkBoRate: stkBoRate,
			StkCoRate: stkCoRate,
			CashDiv: cashDiv,
			CashDivTax: cashDivTax,
			RecordDate: recordDate,
			ExDate: exDate,
			PayDate: payDate,
			DivListdate: divListdate,
			ImpAnnDate: impAnnDate,
			BaseDate: baseDate,
			BaseShare: baseShare,
		}
	}

	return items, nil
}
