// Code generated by tushare-gen. DO NOT EDIT.

package api

import (
	"context"
	"fmt"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// Top10HoldersRequest 表示 top10_holders API 的请求
type Top10HoldersRequest struct {
	TsCode string `json:"ts_code,omitempty"`
	Period string `json:"period,omitempty"`
	AnnDate string `json:"ann_date,omitempty"`
}

// Top10HoldersItem 表示单个 top10_holders 数据项
type Top10HoldersItem struct {
	TsCode string `json:"ts_code"`
	AnnDate string `json:"ann_date"`
	EndDate string `json:"end_date"`
	HolderName string `json:"holder_name"`
	HoldAmount float64 `json:"hold_amount"`
	HoldRatio float64 `json:"hold_ratio"`
}

// Top10Holders 调用 top10_holders API
func Top10Holders(ctx context.Context, client *sdk.Client, req *Top10HoldersRequest) ([]Top10HoldersItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.Period != "" {
		params["period"] = req.Period
	}
	if req.AnnDate != "" {
		params["ann_date"] = req.AnnDate
	}

	fields := []string{"ts_code", "ann_date", "end_date", "holder_name", "hold_amount", "hold_ratio"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "top10_holders", params, fields, &result); err != nil {
		return nil, err
	}

	items := make([]Top10HoldersItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 ts_code 的简单类型
		tsCode, ok := item["ts_code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 ann_date 的简单类型
		annDate, ok := item["ann_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ann_date 类型")
		}
		// 处理 end_date 的简单类型
		endDate, ok := item["end_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 end_date 类型")
		}
		// 处理 holder_name 的简单类型
		holderName, ok := item["holder_name"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 holder_name 类型")
		}
		// 处理 hold_amount 的简单类型
		holdAmount, ok := item["hold_amount"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 hold_amount 类型")
		}
		// 处理 hold_ratio 的简单类型
		holdRatio, ok := item["hold_ratio"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 hold_ratio 类型")
		}
		items[i] = Top10HoldersItem{
			TsCode: tsCode,
			AnnDate: annDate,
			EndDate: endDate,
			HolderName: holderName,
			HoldAmount: holdAmount,
			HoldRatio: holdRatio,
		}
	}

	return items, nil
}
