// Code generated by tushare-gen. DO NOT EDIT.

package bond

import (
	"context"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// Api272Request 表示 api_272 API 的请求
type Api272Request struct {
}

// Api272Item 表示单个 api_272 数据项
type Api272Item struct {
}

// Api272 调用 api_272 API
func Api272(ctx context.Context, client *sdk.Client, req *Api272Request) ([]Api272Item, error) {
	params := map[string]interface{}{}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "api_272", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []Api272Item{}, nil
}
