// Code generated by tushare-gen. DO NOT EDIT.

package bond

import (
	"context"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// CbInterestRequest 表示 cb_interest API 的请求
type CbInterestRequest struct {
}

// CbInterestItem 表示单个 cb_interest 数据项
type CbInterestItem struct {
}

// CbInterest 调用 cb_interest API
func CbInterest(ctx context.Context, client *sdk.Client, req *CbInterestRequest) ([]CbInterestItem, error) {
	params := map[string]interface{}{}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "cb_interest", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []CbInterestItem{}, nil
}
