// Code generated by tushare-gen. DO NOT EDIT.

package bond

import (
	"context"
	"encoding/json"
	"fmt"
	"log"

	"tushare-go/pkg/sdk"
)

// CbRateRequest 表示 可转债票面利率 API 的请求
type CbRateRequest struct {
	TsCode string `json:"ts_code,omitempty"` // 转债代码，支持多值输入
}

// CbRateItem 表示单个 可转债票面利率 数据项
type CbRateItem struct {
	TsCode string `json:"ts_code"` // 转债代码
	RateFreq int `json:"rate_freq"` // 付息频率(次/年)
	RateStartDate string `json:"rate_start_date"` // 付息开始日期
	RateEndDate string `json:"rate_end_date"` // 付息结束日期
	CouponRate float64 `json:"coupon_rate"` // 票面利率(%)
}

// CbRate 调用 可转债票面利率 API
// 获取可转债票面利率
// 注意：积分要求等使用限制请参考Tushare官方文档
func CbRate(ctx context.Context, client *sdk.Client, req *CbRateRequest) ([]CbRateItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}

	fields := []string{"ts_code", "rate_freq", "rate_start_date", "rate_end_date", "coupon_rate"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPIFlexible(ctx, "cb_rate", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]CbRateItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 ts_code 的简单类型
		// 对 string 类型尝试多种转换
		var tsCode string
		if v, ok := item["ts_code"].(string); ok {
			tsCode = v
		} else if v, ok := item["ts_code"].(float64); ok {
			tsCode = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["ts_code"].(int); ok {
			tsCode = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["ts_code"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: cb_rate")
			log.Printf("字段: ts_code")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["ts_code"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 rate_freq 的简单类型
		rateFreq, ok := item["rate_freq"].(int)
		if !ok {
			return nil, fmt.Errorf("无效的 rate_freq 类型")
		}
		// 处理 rate_start_date 的简单类型
		// 对 string 类型尝试多种转换
		var rateStartDate string
		if v, ok := item["rate_start_date"].(string); ok {
			rateStartDate = v
		} else if v, ok := item["rate_start_date"].(float64); ok {
			rateStartDate = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["rate_start_date"].(int); ok {
			rateStartDate = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["rate_start_date"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: cb_rate")
			log.Printf("字段: rate_start_date")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["rate_start_date"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 rate_start_date 类型")
		}
		// 处理 rate_end_date 的简单类型
		// 对 string 类型尝试多种转换
		var rateEndDate string
		if v, ok := item["rate_end_date"].(string); ok {
			rateEndDate = v
		} else if v, ok := item["rate_end_date"].(float64); ok {
			rateEndDate = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["rate_end_date"].(int); ok {
			rateEndDate = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["rate_end_date"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: cb_rate")
			log.Printf("字段: rate_end_date")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["rate_end_date"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 rate_end_date 类型")
		}
		// 处理 coupon_rate 的简单类型
		couponRate, ok := item["coupon_rate"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 coupon_rate 类型")
		}
		items[i] = CbRateItem{
			TsCode: tsCode,
			RateFreq: rateFreq,
			RateStartDate: rateStartDate,
			RateEndDate: rateEndDate,
			CouponRate: couponRate,
		}
	}

	return items, nil
}
