// Code generated by tushare-gen. DO NOT EDIT.

package bond

import (
	"context"
	"encoding/json"
	"fmt"
	"log"

	"tushare-go/pkg/sdk"
)

// EcoCalRequest 表示 全球财经事件 API 的请求
type EcoCalRequest struct {
	Date string `json:"date,omitempty"` // 日期（YYYYMMDD格式）
	StartDate string `json:"start_date,omitempty"` // 开始日期
	EndDate string `json:"end_date,omitempty"` // 结束日期
	Currency string `json:"currency,omitempty"` // 货币代码
	Country string `json:"country,omitempty"` // 国家（比如：中国、美国）
	Event string `json:"event,omitempty"` // 事件 （支持模糊匹配： *非农*）
}

// EcoCalItem 表示单个 全球财经事件 数据项
type EcoCalItem struct {
	Date string `json:"date"` // 日期
	Time string `json:"time"` // 时间
	Currency string `json:"currency"` // 货币代码
	Country string `json:"country"` // 国家
	Event string `json:"event"` // 经济事件
	Value string `json:"value"` // 今值
	PreValue string `json:"pre_value"` // 前值
	ForeValue string `json:"fore_value"` // 预测值
}

// EcoCal 调用 全球财经事件 API
// 获取全球财经日历、包括经济事件数据更新
// 注意：积分要求等使用限制请参考Tushare官方文档
func EcoCal(ctx context.Context, client *sdk.Client, req *EcoCalRequest) ([]EcoCalItem, error) {
	params := map[string]interface{}{}
	if req.Date != "" {
		params["date"] = req.Date
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}
	if req.Currency != "" {
		params["currency"] = req.Currency
	}
	if req.Country != "" {
		params["country"] = req.Country
	}
	if req.Event != "" {
		params["event"] = req.Event
	}

	fields := []string{"date", "time", "currency", "country", "event", "value", "pre_value", "fore_value"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPIFlexible(ctx, "eco_cal", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]EcoCalItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 date 的简单类型
		// 对 string 类型尝试多种转换
		var date string
		if item["date"] == nil {
			// 字段值为 null，使用零值
			date = ""
		} else if v, ok := item["date"].(string); ok {
			date = v
		} else if v, ok := item["date"].(float64); ok {
			date = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["date"].(int); ok {
			date = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["date"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: eco_cal")
			log.Printf("字段: date")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["date"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 date 类型")
		}
		// 处理 time 的简单类型
		// 对 string 类型尝试多种转换
		var time string
		if item["time"] == nil {
			// 字段值为 null，使用零值
			time = ""
		} else if v, ok := item["time"].(string); ok {
			time = v
		} else if v, ok := item["time"].(float64); ok {
			time = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["time"].(int); ok {
			time = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["time"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: eco_cal")
			log.Printf("字段: time")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["time"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 time 类型")
		}
		// 处理 currency 的简单类型
		// 对 string 类型尝试多种转换
		var currency string
		if item["currency"] == nil {
			// 字段值为 null，使用零值
			currency = ""
		} else if v, ok := item["currency"].(string); ok {
			currency = v
		} else if v, ok := item["currency"].(float64); ok {
			currency = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["currency"].(int); ok {
			currency = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["currency"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: eco_cal")
			log.Printf("字段: currency")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["currency"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 currency 类型")
		}
		// 处理 country 的简单类型
		// 对 string 类型尝试多种转换
		var country string
		if item["country"] == nil {
			// 字段值为 null，使用零值
			country = ""
		} else if v, ok := item["country"].(string); ok {
			country = v
		} else if v, ok := item["country"].(float64); ok {
			country = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["country"].(int); ok {
			country = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["country"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: eco_cal")
			log.Printf("字段: country")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["country"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 country 类型")
		}
		// 处理 event 的简单类型
		// 对 string 类型尝试多种转换
		var event string
		if item["event"] == nil {
			// 字段值为 null，使用零值
			event = ""
		} else if v, ok := item["event"].(string); ok {
			event = v
		} else if v, ok := item["event"].(float64); ok {
			event = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["event"].(int); ok {
			event = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["event"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: eco_cal")
			log.Printf("字段: event")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["event"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 event 类型")
		}
		// 处理 value 的简单类型
		// 对 string 类型尝试多种转换
		var value string
		if item["value"] == nil {
			// 字段值为 null，使用零值
			value = ""
		} else if v, ok := item["value"].(string); ok {
			value = v
		} else if v, ok := item["value"].(float64); ok {
			value = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["value"].(int); ok {
			value = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["value"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: eco_cal")
			log.Printf("字段: value")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["value"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 value 类型")
		}
		// 处理 pre_value 的简单类型
		// 对 string 类型尝试多种转换
		var preValue string
		if item["pre_value"] == nil {
			// 字段值为 null，使用零值
			preValue = ""
		} else if v, ok := item["pre_value"].(string); ok {
			preValue = v
		} else if v, ok := item["pre_value"].(float64); ok {
			preValue = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["pre_value"].(int); ok {
			preValue = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["pre_value"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: eco_cal")
			log.Printf("字段: pre_value")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["pre_value"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 pre_value 类型")
		}
		// 处理 fore_value 的简单类型
		// 对 string 类型尝试多种转换
		var foreValue string
		if item["fore_value"] == nil {
			// 字段值为 null，使用零值
			foreValue = ""
		} else if v, ok := item["fore_value"].(string); ok {
			foreValue = v
		} else if v, ok := item["fore_value"].(float64); ok {
			foreValue = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["fore_value"].(int); ok {
			foreValue = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["fore_value"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: eco_cal")
			log.Printf("字段: fore_value")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["fore_value"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 fore_value 类型")
		}
		items[i] = EcoCalItem{
			Date: date,
			Time: time,
			Currency: currency,
			Country: country,
			Event: event,
			Value: value,
			PreValue: preValue,
			ForeValue: foreValue,
		}
	}

	return items, nil
}
