// Code generated by tushare-gen. DO NOT EDIT.

package stock_basic

import (
	"context"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// BseCodeTranslateRequest 表示 bse_code_translate API 的请求
type BseCodeTranslateRequest struct {
}

// BseCodeTranslateItem 表示单个 bse_code_translate 数据项
type BseCodeTranslateItem struct {
}

// BseCodeTranslate 调用 bse_code_translate API
func BseCodeTranslate(ctx context.Context, client *sdk.Client, req *BseCodeTranslateRequest) ([]BseCodeTranslateItem, error) {
	params := map[string]interface{}{}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "bse_code_translate", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []BseCodeTranslateItem{}, nil
}
