// Code generated by tushare-gen. DO NOT EDIT.

package stock_basic

import (
	"context"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// StStockListRequest 表示 st_stock_list API 的请求
type StStockListRequest struct {
}

// StStockListItem 表示单个 st_stock_list 数据项
type StStockListItem struct {
}

// StStockList 调用 st_stock_list API
func StStockList(ctx context.Context, client *sdk.Client, req *StStockListRequest) ([]StStockListItem, error) {
	params := map[string]interface{}{}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "st_stock_list", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []StStockListItem{}, nil
}
