// Code generated by tushare-gen. DO NOT EDIT.

package stock_basic

import (
	"context"
	"fmt"

	"tushare-go/pkg/sdk"
)

// StkManagersRequest 表示 上市公司管理层 API 的请求
type StkManagersRequest struct {
	TsCode string `json:"ts_code,omitempty"` // 股票代码，支持单个或多个股票输入
	AnnDate string `json:"ann_date,omitempty"` // 公告日期（YYYYMMDD格式，下同）
	StartDate string `json:"start_date,omitempty"` // 公告开始日期
	EndDate string `json:"end_date,omitempty"` // 公告结束日期
}

// StkManagersItem 表示单个 上市公司管理层 数据项
type StkManagersItem struct {
	TsCode string `json:"ts_code"` // TS股票代码
	AnnDate string `json:"ann_date"` // 公告日期
	Name string `json:"name"` // 姓名
	Gender string `json:"gender"` // 性别
	Lev string `json:"lev"` // 岗位类别
	Title string `json:"title"` // 岗位
	Edu string `json:"edu"` // 学历
	National string `json:"national"` // 国籍
	Birthday string `json:"birthday"` // 出生年月
	BeginDate string `json:"begin_date"` // 上任日期
	EndDate string `json:"end_date"` // 离任日期
	Resume string `json:"resume"` // 个人简历
}

// StkManagers 调用 上市公司管理层 API
// 获取上市公司管理层
// 注意：积分要求等使用限制请参考Tushare官方文档
func StkManagers(ctx context.Context, client *sdk.Client, req *StkManagersRequest) ([]StkManagersItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.AnnDate != "" {
		params["ann_date"] = req.AnnDate
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}

	fields := []string{"ts_code", "ann_date", "name", "gender", "lev", "title", "edu", "national", "birthday", "begin_date", "end_date", "resume"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPIFlexible(ctx, "stk_managers", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]StkManagersItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 ts_code 的简单类型
		// 对 string 类型尝试多种转换
		var tsCode string
		if v, ok := item["ts_code"].(string); ok {
			tsCode = v
		} else if v, ok := item["ts_code"].(float64); ok {
			tsCode = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["ts_code"].(int); ok {
			tsCode = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 ann_date 的简单类型
		// 对 string 类型尝试多种转换
		var annDate string
		if v, ok := item["ann_date"].(string); ok {
			annDate = v
		} else if v, ok := item["ann_date"].(float64); ok {
			annDate = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["ann_date"].(int); ok {
			annDate = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 ann_date 类型")
		}
		// 处理 name 的简单类型
		// 对 string 类型尝试多种转换
		var name string
		if v, ok := item["name"].(string); ok {
			name = v
		} else if v, ok := item["name"].(float64); ok {
			name = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["name"].(int); ok {
			name = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 name 类型")
		}
		// 处理 gender 的简单类型
		// 对 string 类型尝试多种转换
		var gender string
		if v, ok := item["gender"].(string); ok {
			gender = v
		} else if v, ok := item["gender"].(float64); ok {
			gender = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["gender"].(int); ok {
			gender = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 gender 类型")
		}
		// 处理 lev 的简单类型
		// 对 string 类型尝试多种转换
		var lev string
		if v, ok := item["lev"].(string); ok {
			lev = v
		} else if v, ok := item["lev"].(float64); ok {
			lev = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["lev"].(int); ok {
			lev = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 lev 类型")
		}
		// 处理 title 的简单类型
		// 对 string 类型尝试多种转换
		var title string
		if v, ok := item["title"].(string); ok {
			title = v
		} else if v, ok := item["title"].(float64); ok {
			title = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["title"].(int); ok {
			title = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 title 类型")
		}
		// 处理 edu 的简单类型
		// 对 string 类型尝试多种转换
		var edu string
		if v, ok := item["edu"].(string); ok {
			edu = v
		} else if v, ok := item["edu"].(float64); ok {
			edu = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["edu"].(int); ok {
			edu = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 edu 类型")
		}
		// 处理 national 的简单类型
		// 对 string 类型尝试多种转换
		var national string
		if v, ok := item["national"].(string); ok {
			national = v
		} else if v, ok := item["national"].(float64); ok {
			national = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["national"].(int); ok {
			national = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 national 类型")
		}
		// 处理 birthday 的简单类型
		// 对 string 类型尝试多种转换
		var birthday string
		if v, ok := item["birthday"].(string); ok {
			birthday = v
		} else if v, ok := item["birthday"].(float64); ok {
			birthday = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["birthday"].(int); ok {
			birthday = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 birthday 类型")
		}
		// 处理 begin_date 的简单类型
		// 对 string 类型尝试多种转换
		var beginDate string
		if v, ok := item["begin_date"].(string); ok {
			beginDate = v
		} else if v, ok := item["begin_date"].(float64); ok {
			beginDate = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["begin_date"].(int); ok {
			beginDate = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 begin_date 类型")
		}
		// 处理 end_date 的简单类型
		// 对 string 类型尝试多种转换
		var endDate string
		if v, ok := item["end_date"].(string); ok {
			endDate = v
		} else if v, ok := item["end_date"].(float64); ok {
			endDate = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["end_date"].(int); ok {
			endDate = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 end_date 类型")
		}
		// 处理 resume 的简单类型
		// 对 string 类型尝试多种转换
		var resume string
		if v, ok := item["resume"].(string); ok {
			resume = v
		} else if v, ok := item["resume"].(float64); ok {
			resume = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["resume"].(int); ok {
			resume = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 resume 类型")
		}
		items[i] = StkManagersItem{
			TsCode: tsCode,
			AnnDate: annDate,
			Name: name,
			Gender: gender,
			Lev: lev,
			Title: title,
			Edu: edu,
			National: national,
			Birthday: birthday,
			BeginDate: beginDate,
			EndDate: endDate,
			Resume: resume,
		}
	}

	return items, nil
}
