// Code generated by tushare-gen. DO NOT EDIT.

package stock_basic

import (
	"context"
	"fmt"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// StkPremarketRequest 表示 每日股本（盘前） API 的请求
type StkPremarketRequest struct {
	TsCode string `json:"ts_code,omitempty"`
	TradeDate string `json:"trade_date,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
}

// StkPremarketItem 表示单个 每日股本（盘前） 数据项
type StkPremarketItem struct {
	TradeDate string `json:"trade_date"`
	TsCode string `json:"ts_code"`
	TotalShare float64 `json:"total_share"`
	FloatShare float64 `json:"float_share"`
	PreClose float64 `json:"pre_close"`
	UpLimit float64 `json:"up_limit"`
	DownLimit float64 `json:"down_limit"`
}

// StkPremarket 调用 每日股本（盘前） API
func StkPremarket(ctx context.Context, client *sdk.Client, req *StkPremarketRequest) ([]StkPremarketItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.TradeDate != "" {
		params["trade_date"] = req.TradeDate
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}

	fields := []string{"trade_date", "ts_code", "total_share", "float_share", "pre_close", "up_limit", "down_limit"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "stk_premarket", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]StkPremarketItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 trade_date 的简单类型
		tradeDate, ok := item["trade_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 trade_date 类型")
		}
		// 处理 ts_code 的简单类型
		tsCode, ok := item["ts_code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 total_share 的简单类型
		totalShare, ok := item["total_share"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 total_share 类型")
		}
		// 处理 float_share 的简单类型
		floatShare, ok := item["float_share"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 float_share 类型")
		}
		// 处理 pre_close 的简单类型
		preClose, ok := item["pre_close"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 pre_close 类型")
		}
		// 处理 up_limit 的简单类型
		upLimit, ok := item["up_limit"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 up_limit 类型")
		}
		// 处理 down_limit 的简单类型
		downLimit, ok := item["down_limit"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 down_limit 类型")
		}
		items[i] = StkPremarketItem{
			TradeDate: tradeDate,
			TsCode: tsCode,
			TotalShare: totalShare,
			FloatShare: floatShare,
			PreClose: preClose,
			UpLimit: upLimit,
			DownLimit: downLimit,
		}
	}

	return items, nil
}
