// Code generated by tushare-gen. DO NOT EDIT.

package stock_market

import (
	"context"
	"fmt"

	"tushare-go/pkg/sdk"
)

// RtKRequest 表示 实时日线 API 的请求
type RtKRequest struct {
	TsCode string `json:"ts_code,omitempty"` // 支持通配符方式，e.g. 所有上交所股票：6*.SH、所有创业板股票3*.SZ、所有科创板股票688*.SH，或单个股票600000.SH
}

// RtKItem 表示单个 实时日线 数据项
type RtKItem struct {
	TsCode string `json:"ts_code"` // 股票代码
	Name string `json:"name"` // 股票名称
	PreClose float64 `json:"pre_close"` // 昨收价
	High float64 `json:"high"` // 最高价
	Open float64 `json:"open"` // 开盘价
	Low float64 `json:"low"` // 最低价
	Close float64 `json:"close"` // 收盘价（最新价）
	Vol int `json:"vol"` // 成交量（股）
	Amount int `json:"amount"` // 成交金额（元）
	Num int `json:"num"` // 开盘以来成交笔数
	AskPrice1 float64 `json:"ask_price1"` // 委托卖盘（元）
	AskVolume1 int `json:"ask_volume1"` // 委托卖盘（股）
	BidPrice1 float64 `json:"bid_price1"` // 委托买盘（元）
	BidVolume1 int `json:"bid_volume1"` // 委托买盘（股）
	TradeTime string `json:"trade_time"` // 交易时间
}

// RtK 调用 实时日线 API
// 获取实时日k线行情，支持按股票代码及股票代码通配符一次性提取全部股票实时日k线行情
// 注意：积分要求等使用限制请参考Tushare官方文档
func RtK(ctx context.Context, client *sdk.Client, req *RtKRequest) ([]RtKItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}

	fields := []string{"ts_code", "name", "pre_close", "high", "open", "low", "close", "vol", "amount", "num", "ask_price1", "ask_volume1", "bid_price1", "bid_volume1", "trade_time"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPIFlexible(ctx, "rt_k", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]RtKItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 ts_code 的简单类型
		tsCode, ok := item["ts_code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 name 的简单类型
		name, ok := item["name"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 name 类型")
		}
		// 处理 pre_close 的简单类型
		preClose, ok := item["pre_close"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 pre_close 类型")
		}
		// 处理 high 的简单类型
		high, ok := item["high"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 high 类型")
		}
		// 处理 open 的简单类型
		open, ok := item["open"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 open 类型")
		}
		// 处理 low 的简单类型
		low, ok := item["low"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 low 类型")
		}
		// 处理 close 的简单类型
		close, ok := item["close"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 close 类型")
		}
		// 处理 vol 的简单类型
		vol, ok := item["vol"].(int)
		if !ok {
			return nil, fmt.Errorf("无效的 vol 类型")
		}
		// 处理 amount 的简单类型
		amount, ok := item["amount"].(int)
		if !ok {
			return nil, fmt.Errorf("无效的 amount 类型")
		}
		// 处理 num 的简单类型
		num, ok := item["num"].(int)
		if !ok {
			return nil, fmt.Errorf("无效的 num 类型")
		}
		// 处理 ask_price1 的简单类型
		askPrice1, ok := item["ask_price1"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 ask_price1 类型")
		}
		// 处理 ask_volume1 的简单类型
		askVolume1, ok := item["ask_volume1"].(int)
		if !ok {
			return nil, fmt.Errorf("无效的 ask_volume1 类型")
		}
		// 处理 bid_price1 的简单类型
		bidPrice1, ok := item["bid_price1"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 bid_price1 类型")
		}
		// 处理 bid_volume1 的简单类型
		bidVolume1, ok := item["bid_volume1"].(int)
		if !ok {
			return nil, fmt.Errorf("无效的 bid_volume1 类型")
		}
		// 处理 trade_time 的简单类型
		tradeTime, ok := item["trade_time"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 trade_time 类型")
		}
		items[i] = RtKItem{
			TsCode: tsCode,
			Name: name,
			PreClose: preClose,
			High: high,
			Open: open,
			Low: low,
			Close: close,
			Vol: vol,
			Amount: amount,
			Num: num,
			AskPrice1: askPrice1,
			AskVolume1: askVolume1,
			BidPrice1: bidPrice1,
			BidVolume1: bidVolume1,
			TradeTime: tradeTime,
		}
	}

	return items, nil
}
