// Code generated by tushare-gen. DO NOT EDIT.

package stock_market

import (
	"context"
	"fmt"

	"tushare-go/pkg/sdk"
)

// StkWeeklyMonthlyRequest 表示 周/月线行情(每日更新) API 的请求
type StkWeeklyMonthlyRequest struct {
	TsCode string `json:"ts_code,omitempty"` // TS代码
	TradeDate string `json:"trade_date,omitempty"` // 交易日期(格式：YYYYMMDD，每周或每月最后一天的日期）
	StartDate string `json:"start_date,omitempty"` // 开始交易日期
	EndDate string `json:"end_date,omitempty"` // 结束交易日期
	Freq string `json:"freq,omitempty"` // 频率week周，month月
}

// StkWeeklyMonthlyItem 表示单个 周/月线行情(每日更新) 数据项
type StkWeeklyMonthlyItem struct {
	TsCode string `json:"ts_code"` // 股票代码
	TradeDate string `json:"trade_date"` // 交易日期
	EndDate string `json:"end_date"` // 计算截至日期
	Freq string `json:"freq"` // 频率(周week,月month)
	Open float64 `json:"open"` // (周/月)开盘价
	High float64 `json:"high"` // (周/月)最高价
	Low float64 `json:"low"` // (周/月)最低价
	Close float64 `json:"close"` // (周/月)收盘价
	PreClose float64 `json:"pre_close"` // 上一(周/月)收盘价
	Vol float64 `json:"vol"` // (周/月)成交量
	Amount float64 `json:"amount"` // (周/月)成交额
	Change float64 `json:"change"` // (周/月)涨跌额
	PctChg float64 `json:"pct_chg"` // (周/月)涨跌幅(未复权,如果是复权请用 通用行情接口)
}

// StkWeeklyMonthly 调用 周/月线行情(每日更新) API
// 股票周/月线行情(每日更新)
// 注意：积分要求等使用限制请参考Tushare官方文档
func StkWeeklyMonthly(ctx context.Context, client *sdk.Client, req *StkWeeklyMonthlyRequest) ([]StkWeeklyMonthlyItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.TradeDate != "" {
		params["trade_date"] = req.TradeDate
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}
	if req.Freq != "" {
		params["freq"] = req.Freq
	}

	fields := []string{"ts_code", "trade_date", "end_date", "freq", "open", "high", "low", "close", "pre_close", "vol", "amount", "change", "pct_chg"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPIFlexible(ctx, "stk_weekly_monthly", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]StkWeeklyMonthlyItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 ts_code 的简单类型
		tsCode, ok := item["ts_code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 trade_date 的简单类型
		tradeDate, ok := item["trade_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 trade_date 类型")
		}
		// 处理 end_date 的简单类型
		endDate, ok := item["end_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 end_date 类型")
		}
		// 处理 freq 的简单类型
		freq, ok := item["freq"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 freq 类型")
		}
		// 处理 open 的简单类型
		open, ok := item["open"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 open 类型")
		}
		// 处理 high 的简单类型
		high, ok := item["high"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 high 类型")
		}
		// 处理 low 的简单类型
		low, ok := item["low"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 low 类型")
		}
		// 处理 close 的简单类型
		close, ok := item["close"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 close 类型")
		}
		// 处理 pre_close 的简单类型
		preClose, ok := item["pre_close"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 pre_close 类型")
		}
		// 处理 vol 的简单类型
		vol, ok := item["vol"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 vol 类型")
		}
		// 处理 amount 的简单类型
		amount, ok := item["amount"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 amount 类型")
		}
		// 处理 change 的简单类型
		change, ok := item["change"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 change 类型")
		}
		// 处理 pct_chg 的简单类型
		pctChg, ok := item["pct_chg"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 pct_chg 类型")
		}
		items[i] = StkWeeklyMonthlyItem{
			TsCode: tsCode,
			TradeDate: tradeDate,
			EndDate: endDate,
			Freq: freq,
			Open: open,
			High: high,
			Low: low,
			Close: close,
			PreClose: preClose,
			Vol: vol,
			Amount: amount,
			Change: change,
			PctChg: pctChg,
		}
	}

	return items, nil
}
