// Code generated by tushare-gen. DO NOT EDIT.

package stock_market

import (
	"context"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// Api315Request 表示 api_315 API 的请求
type Api315Request struct {
}

// Api315Item 表示单个 api_315 数据项
type Api315Item struct {
}

// Api315 调用 api_315 API
func Api315(ctx context.Context, client *sdk.Client, req *Api315Request) ([]Api315Item, error) {
	params := map[string]interface{}{}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "api_315", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []Api315Item{}, nil
}
