// Code generated by tushare-gen. DO NOT EDIT.

package stock_market

import (
	"context"
	"encoding/json"
	"fmt"
	"log"

	"tushare-go/pkg/sdk"
)

// BakDailyRequest 表示 备用行情 API 的请求
type BakDailyRequest struct {
	TsCode string `json:"ts_code,omitempty"` // 股票代码
	TradeDate string `json:"trade_date,omitempty"` // 交易日期
	StartDate string `json:"start_date,omitempty"` // 开始日期
	EndDate string `json:"end_date,omitempty"` // 结束日期
	Offset string `json:"offset,omitempty"` // 开始行数
	Limit string `json:"limit,omitempty"` // 最大行数
}

// BakDailyItem 表示单个 备用行情 数据项
type BakDailyItem struct {
	TsCode string `json:"ts_code"` // 股票代码
	TradeDate string `json:"trade_date"` // 交易日期
	Name string `json:"name"` // 股票名称
	PctChange float64 `json:"pct_change"` // 涨跌幅
	Close float64 `json:"close"` // 收盘价
	Change float64 `json:"change"` // 涨跌额
	Open float64 `json:"open"` // 开盘价
	High float64 `json:"high"` // 最高价
	Low float64 `json:"low"` // 最低价
	PreClose float64 `json:"pre_close"` // 昨收价
	VolRatio float64 `json:"vol_ratio"` // 量比
	TurnOver float64 `json:"turn_over"` // 换手率
	Swing float64 `json:"swing"` // 振幅
	Vol float64 `json:"vol"` // 成交量
	Amount float64 `json:"amount"` // 成交额
	Selling float64 `json:"selling"` // 内盘（主动卖，手）
	Buying float64 `json:"buying"` // 外盘（主动买， 手）
	TotalShare float64 `json:"total_share"` // 总股本(亿)
	FloatShare float64 `json:"float_share"` // 流通股本(亿)
	Pe float64 `json:"pe"` // 市盈(动)
	Industry string `json:"industry"` // 所属行业
	Area string `json:"area"` // 所属地域
	FloatMv float64 `json:"float_mv"` // 流通市值
	TotalMv float64 `json:"total_mv"` // 总市值
	AvgPrice float64 `json:"avg_price"` // 平均价
	Strength float64 `json:"strength"` // 强弱度(%)
	Activity float64 `json:"activity"` // 活跃度(%)
	AvgTurnover float64 `json:"avg_turnover"` // 笔换手
	Attack float64 `json:"attack"` // 攻击波(%)
	Interval3 float64 `json:"interval_3"` // 近3月涨幅
	Interval6 float64 `json:"interval_6"` // 近6月涨幅
}

// BakDaily 调用 备用行情 API
// 获取备用行情，包括特定的行情指标(数据从2017年中左右开始，早期有几天数据缺失，近期正常)
// 注意：积分要求等使用限制请参考Tushare官方文档
func BakDaily(ctx context.Context, client *sdk.Client, req *BakDailyRequest) ([]BakDailyItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.TradeDate != "" {
		params["trade_date"] = req.TradeDate
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}
	if req.Offset != "" {
		params["offset"] = req.Offset
	}
	if req.Limit != "" {
		params["limit"] = req.Limit
	}

	fields := []string{"ts_code", "trade_date", "name", "pct_change", "close", "change", "open", "high", "low", "pre_close", "vol_ratio", "turn_over", "swing", "vol", "amount", "selling", "buying", "total_share", "float_share", "pe", "industry", "area", "float_mv", "total_mv", "avg_price", "strength", "activity", "avg_turnover", "attack", "interval_3", "interval_6"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPIFlexible(ctx, "bak_daily", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]BakDailyItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 ts_code 的简单类型
		// 对 string 类型尝试多种转换
		var tsCode string
		if v, ok := item["ts_code"].(string); ok {
			tsCode = v
		} else if v, ok := item["ts_code"].(float64); ok {
			tsCode = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["ts_code"].(int); ok {
			tsCode = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["ts_code"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: bak_daily")
			log.Printf("字段: ts_code")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["ts_code"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 trade_date 的简单类型
		// 对 string 类型尝试多种转换
		var tradeDate string
		if v, ok := item["trade_date"].(string); ok {
			tradeDate = v
		} else if v, ok := item["trade_date"].(float64); ok {
			tradeDate = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["trade_date"].(int); ok {
			tradeDate = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["trade_date"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: bak_daily")
			log.Printf("字段: trade_date")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["trade_date"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 trade_date 类型")
		}
		// 处理 name 的简单类型
		// 对 string 类型尝试多种转换
		var name string
		if v, ok := item["name"].(string); ok {
			name = v
		} else if v, ok := item["name"].(float64); ok {
			name = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["name"].(int); ok {
			name = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["name"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: bak_daily")
			log.Printf("字段: name")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["name"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 name 类型")
		}
		// 处理 pct_change 的简单类型
		pctChange, ok := item["pct_change"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 pct_change 类型")
		}
		// 处理 close 的简单类型
		close, ok := item["close"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 close 类型")
		}
		// 处理 change 的简单类型
		change, ok := item["change"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 change 类型")
		}
		// 处理 open 的简单类型
		open, ok := item["open"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 open 类型")
		}
		// 处理 high 的简单类型
		high, ok := item["high"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 high 类型")
		}
		// 处理 low 的简单类型
		low, ok := item["low"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 low 类型")
		}
		// 处理 pre_close 的简单类型
		preClose, ok := item["pre_close"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 pre_close 类型")
		}
		// 处理 vol_ratio 的简单类型
		volRatio, ok := item["vol_ratio"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 vol_ratio 类型")
		}
		// 处理 turn_over 的简单类型
		turnOver, ok := item["turn_over"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 turn_over 类型")
		}
		// 处理 swing 的简单类型
		swing, ok := item["swing"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 swing 类型")
		}
		// 处理 vol 的简单类型
		vol, ok := item["vol"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 vol 类型")
		}
		// 处理 amount 的简单类型
		amount, ok := item["amount"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 amount 类型")
		}
		// 处理 selling 的简单类型
		selling, ok := item["selling"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 selling 类型")
		}
		// 处理 buying 的简单类型
		buying, ok := item["buying"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 buying 类型")
		}
		// 处理 total_share 的简单类型
		totalShare, ok := item["total_share"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 total_share 类型")
		}
		// 处理 float_share 的简单类型
		floatShare, ok := item["float_share"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 float_share 类型")
		}
		// 处理 pe 的简单类型
		pe, ok := item["pe"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 pe 类型")
		}
		// 处理 industry 的简单类型
		// 对 string 类型尝试多种转换
		var industry string
		if v, ok := item["industry"].(string); ok {
			industry = v
		} else if v, ok := item["industry"].(float64); ok {
			industry = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["industry"].(int); ok {
			industry = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["industry"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: bak_daily")
			log.Printf("字段: industry")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["industry"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 industry 类型")
		}
		// 处理 area 的简单类型
		// 对 string 类型尝试多种转换
		var area string
		if v, ok := item["area"].(string); ok {
			area = v
		} else if v, ok := item["area"].(float64); ok {
			area = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["area"].(int); ok {
			area = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["area"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: bak_daily")
			log.Printf("字段: area")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["area"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 area 类型")
		}
		// 处理 float_mv 的简单类型
		floatMv, ok := item["float_mv"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 float_mv 类型")
		}
		// 处理 total_mv 的简单类型
		totalMv, ok := item["total_mv"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 total_mv 类型")
		}
		// 处理 avg_price 的简单类型
		avgPrice, ok := item["avg_price"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 avg_price 类型")
		}
		// 处理 strength 的简单类型
		strength, ok := item["strength"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 strength 类型")
		}
		// 处理 activity 的简单类型
		activity, ok := item["activity"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 activity 类型")
		}
		// 处理 avg_turnover 的简单类型
		avgTurnover, ok := item["avg_turnover"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 avg_turnover 类型")
		}
		// 处理 attack 的简单类型
		attack, ok := item["attack"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 attack 类型")
		}
		// 处理 interval_3 的简单类型
		interval3, ok := item["interval_3"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 interval_3 类型")
		}
		// 处理 interval_6 的简单类型
		interval6, ok := item["interval_6"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 interval_6 类型")
		}
		items[i] = BakDailyItem{
			TsCode: tsCode,
			TradeDate: tradeDate,
			Name: name,
			PctChange: pctChange,
			Close: close,
			Change: change,
			Open: open,
			High: high,
			Low: low,
			PreClose: preClose,
			VolRatio: volRatio,
			TurnOver: turnOver,
			Swing: swing,
			Vol: vol,
			Amount: amount,
			Selling: selling,
			Buying: buying,
			TotalShare: totalShare,
			FloatShare: floatShare,
			Pe: pe,
			Industry: industry,
			Area: area,
			FloatMv: floatMv,
			TotalMv: totalMv,
			AvgPrice: avgPrice,
			Strength: strength,
			Activity: activity,
			AvgTurnover: avgTurnover,
			Attack: attack,
			Interval3: interval3,
			Interval6: interval6,
		}
	}

	return items, nil
}
