// Code generated by tushare-gen. DO NOT EDIT.

package stock_market

import (
	"context"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// DailyRequest 表示 daily API 的请求
type DailyRequest struct {
}

// DailyItem 表示单个 daily 数据项
type DailyItem struct {
}

// Daily 调用 daily API
func Daily(ctx context.Context, client *sdk.Client, req *DailyRequest) ([]DailyItem, error) {
	params := map[string]interface{}{}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "daily", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []DailyItem{}, nil
}
