// Code generated by tushare-gen. DO NOT EDIT.

package stock_market

import (
	"context"
	"encoding/json"
	"fmt"
	"log"

	"tushare-go/pkg/sdk"
)

// SuspendDRequest 表示 每日停复牌信息 API 的请求
type SuspendDRequest struct {
	TsCode string `json:"ts_code,omitempty"` // 股票代码(可输入多值)
	TradeDate string `json:"trade_date,omitempty"` // 交易日日期
	StartDate string `json:"start_date,omitempty"` // 停复牌查询开始日期
	EndDate string `json:"end_date,omitempty"` // 停复牌查询结束日期
	SuspendType string `json:"suspend_type,omitempty"` // 停复牌类型：S-停牌,R-复牌
}

// SuspendDItem 表示单个 每日停复牌信息 数据项
type SuspendDItem struct {
	TsCode string `json:"ts_code"` // TS代码
	TradeDate string `json:"trade_date"` // 停复牌日期
	SuspendTiming string `json:"suspend_timing"` // 日内停牌时间段
	SuspendType string `json:"suspend_type"` // 停复牌类型：S-停牌，R-复牌
}

// SuspendD 调用 每日停复牌信息 API
// 按日期方式获取股票每日停复牌信息
// 注意：积分要求等使用限制请参考Tushare官方文档
func SuspendD(ctx context.Context, client *sdk.Client, req *SuspendDRequest) ([]SuspendDItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.TradeDate != "" {
		params["trade_date"] = req.TradeDate
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}
	if req.SuspendType != "" {
		params["suspend_type"] = req.SuspendType
	}

	fields := []string{"ts_code", "trade_date", "suspend_timing", "suspend_type"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPIFlexible(ctx, "suspend_d", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]SuspendDItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 ts_code 的简单类型
		// 对 string 类型尝试多种转换
		var tsCode string
		if v, ok := item["ts_code"].(string); ok {
			tsCode = v
		} else if v, ok := item["ts_code"].(float64); ok {
			tsCode = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["ts_code"].(int); ok {
			tsCode = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["ts_code"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: suspend_d")
			log.Printf("字段: ts_code")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["ts_code"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 trade_date 的简单类型
		// 对 string 类型尝试多种转换
		var tradeDate string
		if v, ok := item["trade_date"].(string); ok {
			tradeDate = v
		} else if v, ok := item["trade_date"].(float64); ok {
			tradeDate = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["trade_date"].(int); ok {
			tradeDate = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["trade_date"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: suspend_d")
			log.Printf("字段: trade_date")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["trade_date"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 trade_date 类型")
		}
		// 处理 suspend_timing 的简单类型
		// 对 string 类型尝试多种转换
		var suspendTiming string
		if v, ok := item["suspend_timing"].(string); ok {
			suspendTiming = v
		} else if v, ok := item["suspend_timing"].(float64); ok {
			suspendTiming = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["suspend_timing"].(int); ok {
			suspendTiming = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["suspend_timing"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: suspend_d")
			log.Printf("字段: suspend_timing")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["suspend_timing"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 suspend_timing 类型")
		}
		// 处理 suspend_type 的简单类型
		// 对 string 类型尝试多种转换
		var suspendType string
		if v, ok := item["suspend_type"].(string); ok {
			suspendType = v
		} else if v, ok := item["suspend_type"].(float64); ok {
			suspendType = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["suspend_type"].(int); ok {
			suspendType = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["suspend_type"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: suspend_d")
			log.Printf("字段: suspend_type")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["suspend_type"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 suspend_type 类型")
		}
		items[i] = SuspendDItem{
			TsCode: tsCode,
			TradeDate: tradeDate,
			SuspendTiming: suspendTiming,
			SuspendType: suspendType,
		}
	}

	return items, nil
}
