// Code generated by gen-mcp-tools. DO NOT EDIT.

package macro_money_supplytools

import (
	"context"
	"encoding/json"
	"fmt"

	macro_money_supply "tushare-go/pkg/sdk/api/macro_money_supply"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerCnM registers the tool
func (r *Macro_money_supplyTools) registerCnM() {
	inputSchema, _ := jsonschema.For[CnMInput](nil)
	schemaJSON, _ := json.Marshal(inputSchema)

	tool := &mcp.Tool{
		Name:        "macro_money_supply.cn_m",
		Description: "获取货币供应量之月度数据",
		InputSchema: json.RawMessage(schemaJSON),
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input CnMInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &macro_money_supply.CnMRequest{
M: input.M,
StartM: input.StartM,
EndM: input.EndM,
Fields: input.Fields,

		}

		items, err := macro_money_supply.CnM(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := CnMOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
