// Code generated by gen-mcp-tools. DO NOT EDIT.

package industry_tmttools

import (
	"context"
	"encoding/json"
	"fmt"

	industry_industry_tmt "tushare-go/pkg/sdk/api/industry/industry_tmt"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerBoWeekly registers the tool
func (r *Industry_tmtTools) registerBoWeekly() {
	inputSchema, _ := jsonschema.For[BoWeeklyInput](nil)

	tool := &mcp.Tool{
		Name:        "industry_tmt.bo_weekly",
		Description: "Retrieve boweekly data from Tushare industry tmt API",
		InputSchema: inputSchema,
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input BoWeeklyInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &industry_industry_tmt.BoWeeklyRequest{

		}

		items, err := industry_industry_tmt.BoWeekly(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := BoWeeklyOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
