// Code generated by gen-mcp-tools. DO NOT EDIT.

package us_stocktools

import (
	"context"
	"encoding/json"
	"fmt"

	us_stock "tushare-go/pkg/sdk/api/us_stock"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerUsDailyAdj registers the tool
func (r *Us_stockTools) registerUsDailyAdj() {
	inputSchema, _ := jsonschema.For[UsDailyAdjInput](nil)
	schemaJSON, _ := json.Marshal(inputSchema)

	tool := &mcp.Tool{
		Name:        "us_stock.us_daily_adj",
		Description: "获取美股复权行情，支持美股全市场股票，提供股本、市值、复权因子和成交信息等多个数据指标",
		InputSchema: json.RawMessage(schemaJSON),
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input UsDailyAdjInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &us_stock.UsDailyAdjRequest{
TsCode: input.TsCode,
TradeDate: input.TradeDate,
StartDate: input.StartDate,
EndDate: input.EndDate,
Exchange: input.Exchange,
Offset: input.Offset,
Limit: input.Limit,

		}

		items, err := us_stock.UsDailyAdj(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := UsDailyAdjOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
