// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_featuretools

import (
	"context"

	stock_stock_feature "github.com/chenniannian90/tushare-go/pkg/sdk/api/stock/stock_feature"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// callBrokerRecommend handles BrokerRecommend tool calls
func (m *Stock_featureTools) callBrokerRecommend(ctx context.Context, args map[string]interface{}) (*common.ToolResult, error) {
	req := &stock_stock_feature.BrokerRecommendRequest{}

	// Parse arguments into request
	if err := common.ParseInput(args, req); err != nil {
		return common.ErrorResult(err), nil
	}

	items, err := stock_stock_feature.BrokerRecommend(ctx, m.client, req)
	if err != nil {
		return common.ErrorResult(err), nil
	}

	// Format results
	result, err := common.APIResult(items, "stock_feature", "broker_recommend")
	if err != nil {
		return common.ErrorResult(err), nil
	}
	return result, nil
}
