// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_featuretools

import (
	"tushare-go/pkg/sdk"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// Stock_featureTools represents stock_feature tools
type Stock_featureTools struct {
	server *mcp.Server
	client *sdk.Client
}

// NewStock_featureTools creates a new instance
func NewStock_featureTools(server *mcp.Server, client *sdk.Client) *Stock_featureTools {
	return &Stock_featureTools{server: server, client: client}
}

// RegisterAll registers all tools
func (r *Stock_featureTools) RegisterAll() {
	r.registerBrokerRecommend()
	//r.registerCcassHold()
	//r.registerCcassHoldDetail()
	r.registerCyqChips()
	r.registerCyqPerf()
	r.registerHkHold()
	//r.registerReportRc()
	//r.registerStkAhComparison()
	//r.registerStkAuctionC()
	//r.registerStkAuctionO()
	r.registerStkFactorPro()
	//r.registerStkNineturn()
	r.registerStkSurv()

}
