// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_featuretools

import (
	"context"
	"encoding/json"
	"fmt"

	stock_stock_feature "tushare-go/pkg/sdk/api/stock/stock_feature"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerStkAuctionC registers the tool
func (r *Stock_featureTools) registerStkAuctionC() {
	inputSchema, _ := jsonschema.For[StkAuctionCInput](nil)

	tool := &mcp.Tool{
		Name:        "stock_feature.stk_auction_c",
		Description: "Retrieve stkauctionc data from Tushare stock feature API",
		InputSchema: inputSchema,
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input StkAuctionCInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &stock_stock_feature.StkAuctionCRequest{

		}

		items, err := stock_stock_feature.StkAuctionC(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := StkAuctionCOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
