// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_featuretools

import (
	stock_stock_feature "tushare-go/pkg/sdk/api/stock/stock_feature"

)


// BrokerRecommendInput defines the input schema
type BrokerRecommendInput struct {

}

// BrokerRecommendOutput defines the output schema
type BrokerRecommendOutput struct {
	Data  []stock_stock_feature.BrokerRecommendItem `json:data jsonschema:broker_recommend data list`
	Total int              `json:total jsonschema:Total count`
}

// CcassHoldInput defines the input schema
type CcassHoldInput struct {

}

// CcassHoldOutput defines the output schema
type CcassHoldOutput struct {
	Data  []stock_stock_feature.CcassHoldItem `json:data jsonschema:ccass_hold data list`
	Total int              `json:total jsonschema:Total count`
}

// CcassHoldDetailInput defines the input schema
type CcassHoldDetailInput struct {

}

// CcassHoldDetailOutput defines the output schema
type CcassHoldDetailOutput struct {
	Data  []stock_stock_feature.CcassHoldDetailItem `json:data jsonschema:ccass_hold_detail data list`
	Total int              `json:total jsonschema:Total count`
}

// CyqChipsInput defines the input schema
type CyqChipsInput struct {

}

// CyqChipsOutput defines the output schema
type CyqChipsOutput struct {
	Data  []stock_stock_feature.CyqChipsItem `json:data jsonschema:cyq_chips data list`
	Total int              `json:total jsonschema:Total count`
}

// CyqPerfInput defines the input schema
type CyqPerfInput struct {

}

// CyqPerfOutput defines the output schema
type CyqPerfOutput struct {
	Data  []stock_stock_feature.CyqPerfItem `json:data jsonschema:cyq_perf data list`
	Total int              `json:total jsonschema:Total count`
}

// HkHoldInput defines the input schema
type HkHoldInput struct {

}

// HkHoldOutput defines the output schema
type HkHoldOutput struct {
	Data  []stock_stock_feature.HkHoldItem `json:data jsonschema:hk_hold data list`
	Total int              `json:total jsonschema:Total count`
}

// ReportRcInput defines the input schema
type ReportRcInput struct {

}

// ReportRcOutput defines the output schema
type ReportRcOutput struct {
	Data  []stock_stock_feature.ReportRcItem `json:data jsonschema:report_rc data list`
	Total int              `json:total jsonschema:Total count`
}

// StkAhComparisonInput defines the input schema
type StkAhComparisonInput struct {

}

// StkAhComparisonOutput defines the output schema
type StkAhComparisonOutput struct {
	Data  []stock_stock_feature.StkAhComparisonItem `json:data jsonschema:stk_ah_comparison data list`
	Total int              `json:total jsonschema:Total count`
}

// StkAuctionCInput defines the input schema
type StkAuctionCInput struct {

}

// StkAuctionCOutput defines the output schema
type StkAuctionCOutput struct {
	Data  []stock_stock_feature.StkAuctionCItem `json:data jsonschema:stk_auction_c data list`
	Total int              `json:total jsonschema:Total count`
}

// StkAuctionOInput defines the input schema
type StkAuctionOInput struct {

}

// StkAuctionOOutput defines the output schema
type StkAuctionOOutput struct {
	Data  []stock_stock_feature.StkAuctionOItem `json:data jsonschema:stk_auction_o data list`
	Total int              `json:total jsonschema:Total count`
}

// StkFactorProInput defines the input schema
type StkFactorProInput struct {

}

// StkFactorProOutput defines the output schema
type StkFactorProOutput struct {
	Data  []stock_stock_feature.StkFactorProItem `json:data jsonschema:stk_factor_pro data list`
	Total int              `json:total jsonschema:Total count`
}

// StkNineturnInput defines the input schema
type StkNineturnInput struct {

}

// StkNineturnOutput defines the output schema
type StkNineturnOutput struct {
	Data  []stock_stock_feature.StkNineturnItem `json:data jsonschema:stk_nineturn data list`
	Total int              `json:total jsonschema:Total count`
}

// StkSurvInput defines the input schema
type StkSurvInput struct {

}

// StkSurvOutput defines the output schema
type StkSurvOutput struct {
	Data  []stock_stock_feature.StkSurvItem `json:data jsonschema:stk_surv data list`
	Total int              `json:total jsonschema:Total count`
}

