// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_markettools

import (
	"context"
	"encoding/json"
	"fmt"

	stock_market "tushare-go/pkg/sdk/api/stock_market"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerGgtTop10 registers the tool
func (r *Stock_marketTools) registerGgtTop10() {
	inputSchema, _ := jsonschema.For[GgtTop10Input](nil)

	tool := &mcp.Tool{
		Name:        "stock_market.ggt_top10",
		Description: "获取港股通每日成交数据，其中包括沪市、深市详细数据，每天18~20点之间完成当日更新",
		InputSchema: inputSchema,
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input GgtTop10Input
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &stock_market.GgtTop10Request{
TsCode: input.TsCode,
TradeDate: input.TradeDate,
StartDate: input.StartDate,
EndDate: input.EndDate,
MarketType: input.MarketType,

		}

		items, err := stock_market.GgtTop10(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := GgtTop10Output{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
