// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_markettools

import (
	"context"
	"fmt"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// Stock_marketTools implements tools for stock_market API
type Stock_marketTools struct {
	client *sdk.Client
}

// NewStock_marketTools creates a new stock_market tools instance
func NewStock_marketTools(client *sdk.Client) *Stock_marketTools {
	return &Stock_marketTools{
		client: client,
	}
}

// GetAPIName returns the Tushare API name for this module
func (m *Stock_marketTools) GetAPIName() string {
	return "stock_market"
}

// ListTools returns all available tools in this module
func (m *Stock_marketTools) ListTools() []common.Tool {
	return []common.Tool{
		{
			Name: "stock_market.adj_factor",
			Description: "Access adj_factor data from Tushare API",
		},
		{
			Name: "stock_market.api315",
			Description: "Access api315 data from Tushare API",
		},
		{
			Name: "stock_market.api316",
			Description: "Access api316 data from Tushare API",
		},
		{
			Name: "stock_market.api317",
			Description: "Access api317 data from Tushare API",
		},
		{
			Name: "stock_market.api336",
			Description: "Access api336 data from Tushare API",
		},
		{
			Name: "stock_market.api365",
			Description: "Access api365 data from Tushare API",
		},
		{
			Name: "stock_market.daily",
			Description: "Access daily data from Tushare API",
		},
		{
			Name: "stock_market.daily_basic",
			Description: "Access daily_basic data from Tushare API",
		},
		{
			Name: "stock_market.daily_now",
			Description: "Access daily_now data from Tushare API",
		},
		{
			Name: "stock_market.gg_daily",
			Description: "Access gg_daily data from Tushare API",
		},
		{
			Name: "stock_market.gg_monthly",
			Description: "Access gg_monthly data from Tushare API",
		},
		{
			Name: "stock_market.gg_top10",
			Description: "Access gg_top10 data from Tushare API",
		},
		{
			Name: "stock_market.hg_top10",
			Description: "Access hg_top10 data from Tushare API",
		},
		{
			Name: "stock_market.limit_list",
			Description: "Access limit_list data from Tushare API",
		},
		{
			Name: "stock_market.monthly",
			Description: "Access monthly data from Tushare API",
		},
		{
			Name: "stock_market.stk_mins",
			Description: "Access stk_mins data from Tushare API",
		},
		{
			Name: "stock_market.stk_mins_now",
			Description: "Access stk_mins_now data from Tushare API",
		},
		{
			Name: "stock_market.suspend",
			Description: "Access suspend data from Tushare API",
		},
		{
			Name: "stock_market.universal",
			Description: "Access universal data from Tushare API",
		},
		{
			Name: "stock_market.weekly",
			Description: "Access weekly data from Tushare API",
		},
	}
}

// HandlesTool checks if this module handles a tool
func (m *Stock_marketTools) HandlesTool(toolName string) bool {
	tools := m.ListTools()
	for _, tool := range tools {
		if tool.Name == toolName {
			return true
		}
	}
	return false
}

// CallTool executes a tool call
func (m *Stock_marketTools) CallTool(ctx context.Context, toolName string, args map[string]interface{}) (*common.ToolResult, error) {
	switch toolName {
	case "stock_market.adj_factor":
		return m.callAdjFactor(ctx, args)
	case "stock_market.api315":
		return m.callApi315(ctx, args)
	case "stock_market.api316":
		return m.callApi316(ctx, args)
	case "stock_market.api317":
		return m.callApi317(ctx, args)
	case "stock_market.api336":
		return m.callApi336(ctx, args)
	case "stock_market.api365":
		return m.callApi365(ctx, args)
	case "stock_market.daily":
		return m.callDaily(ctx, args)
	case "stock_market.daily_basic":
		return m.callDailyBasic(ctx, args)
	case "stock_market.daily_now":
		return m.callDailyNow(ctx, args)
	case "stock_market.gg_daily":
		return m.callGgDaily(ctx, args)
	case "stock_market.gg_monthly":
		return m.callGgMonthly(ctx, args)
	case "stock_market.gg_top10":
		return m.callGgTop10(ctx, args)
	case "stock_market.hg_top10":
		return m.callHgTop10(ctx, args)
	case "stock_market.limit_list":
		return m.callLimitList(ctx, args)
	case "stock_market.monthly":
		return m.callMonthly(ctx, args)
	case "stock_market.stk_mins":
		return m.callStkMins(ctx, args)
	case "stock_market.stk_mins_now":
		return m.callStkMinsNow(ctx, args)
	case "stock_market.suspend":
		return m.callSuspend(ctx, args)
	case "stock_market.universal":
		return m.callUniversal(ctx, args)
	case "stock_market.weekly":
		return m.callWeekly(ctx, args)
	default:
		return nil, fmt.Errorf("unknown tool: %s", toolName)
	}
}
