// Code generated by tushare-gen. DO NOT EDIT.

package stock_fund_flow

import (
	"context"

	"tushare-go/pkg/sdk"
)

// MoneyflowHsgtRequest 表示 沪深港通资金流向 API 的请求
type MoneyflowHsgtRequest struct {
	TradeDate string `json:"trade_date,omitempty"` // 交易日期 (二选一)
	StartDate string `json:"start_date,omitempty"` // 开始日期 (二选一)
	EndDate string `json:"end_date,omitempty"` // 结束日期
}

// MoneyflowHsgtItem 表示单个 沪深港通资金流向 数据项
type MoneyflowHsgtItem struct {
}

// MoneyflowHsgt 调用 沪深港通资金流向 API
// 获取沪股通、深股通、港股通每日资金流向数据，每次最多返回300条记录，总量不限制。 积分要求：2000积分起，5000积分每分钟可提取500次
// 注意：积分要求等使用限制请参考Tushare官方文档
func MoneyflowHsgt(ctx context.Context, client *sdk.Client, req *MoneyflowHsgtRequest) ([]MoneyflowHsgtItem, error) {
	params := map[string]interface{}{}
	if req.TradeDate != "" {
		params["trade_date"] = req.TradeDate
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "moneyflow_hsgt", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []MoneyflowHsgtItem{}, nil
}
