// Code generated by tushare-gen. DO NOT EDIT.

package hk_stock

import (
	"context"
	"fmt"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// HkDailyAdjRequest 表示 港股复权行情 API 的请求
type HkDailyAdjRequest struct {
	TsCode string `json:"ts_code,omitempty"` // 股票代码（e.g. 00001.HK）
	TradeDate string `json:"trade_date,omitempty"` // 交易日期（YYYYMMDD）
	StartDate string `json:"start_date,omitempty"` // 开始日期（YYYYMMDD）
	EndDate string `json:"end_date,omitempty"` // 结束日期（YYYYMMDD）
}

// HkDailyAdjItem 表示单个 港股复权行情 数据项
type HkDailyAdjItem struct {
	TsCode string `json:"ts_code"` // 股票代码
	TradeDate string `json:"trade_date"` // 交易日期
	Close float64 `json:"close"` // 收盘价
	Open float64 `json:"open"` // 开盘价
	High float64 `json:"high"` // 最高价
	Low float64 `json:"low"` // 最低价
	PreClose float64 `json:"pre_close"` // 昨收价
	Change float64 `json:"change"` // 涨跌额
	PctChange float64 `json:"pct_change"` // 涨跌幅
	Vol string `json:"vol"` // 成交量
	Amount float64 `json:"amount"` // 成交额
	Vwap float64 `json:"vwap"` // 平均价
	AdjFactor float64 `json:"adj_factor"` // 复权因子
	TurnoverRatio float64 `json:"turnover_ratio"` // 换手率(基于总股本)
	FreeShare string `json:"free_share"` // 流通股本
	TotalShare string `json:"total_share"` // 总股本
	FreeMv float64 `json:"free_mv"` // 流通市值
	TotalMv float64 `json:"total_mv"` // 总市值
}

// HkDailyAdj 调用 港股复权行情 API
func HkDailyAdj(ctx context.Context, client *sdk.Client, req *HkDailyAdjRequest) ([]HkDailyAdjItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.TradeDate != "" {
		params["trade_date"] = req.TradeDate
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}

	fields := []string{"ts_code", "trade_date", "close", "open", "high", "low", "pre_close", "change", "pct_change", "vol", "amount", "vwap", "adj_factor", "turnover_ratio", "free_share", "total_share", "free_mv", "total_mv"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "hk_daily_adj", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]HkDailyAdjItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 ts_code 的简单类型
		tsCode, ok := item["ts_code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 trade_date 的简单类型
		tradeDate, ok := item["trade_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 trade_date 类型")
		}
		// 处理 close 的简单类型
		close, ok := item["close"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 close 类型")
		}
		// 处理 open 的简单类型
		open, ok := item["open"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 open 类型")
		}
		// 处理 high 的简单类型
		high, ok := item["high"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 high 类型")
		}
		// 处理 low 的简单类型
		low, ok := item["low"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 low 类型")
		}
		// 处理 pre_close 的简单类型
		preClose, ok := item["pre_close"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 pre_close 类型")
		}
		// 处理 change 的简单类型
		change, ok := item["change"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 change 类型")
		}
		// 处理 pct_change 的简单类型
		pctChange, ok := item["pct_change"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 pct_change 类型")
		}
		// 处理 vol 的简单类型
		vol, ok := item["vol"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 vol 类型")
		}
		// 处理 amount 的简单类型
		amount, ok := item["amount"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 amount 类型")
		}
		// 处理 vwap 的简单类型
		vwap, ok := item["vwap"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 vwap 类型")
		}
		// 处理 adj_factor 的简单类型
		adjFactor, ok := item["adj_factor"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 adj_factor 类型")
		}
		// 处理 turnover_ratio 的简单类型
		turnoverRatio, ok := item["turnover_ratio"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 turnover_ratio 类型")
		}
		// 处理 free_share 的简单类型
		freeShare, ok := item["free_share"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 free_share 类型")
		}
		// 处理 total_share 的简单类型
		totalShare, ok := item["total_share"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 total_share 类型")
		}
		// 处理 free_mv 的简单类型
		freeMv, ok := item["free_mv"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 free_mv 类型")
		}
		// 处理 total_mv 的简单类型
		totalMv, ok := item["total_mv"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 total_mv 类型")
		}
		items[i] = HkDailyAdjItem{
			TsCode: tsCode,
			TradeDate: tradeDate,
			Close: close,
			Open: open,
			High: high,
			Low: low,
			PreClose: preClose,
			Change: change,
			PctChange: pctChange,
			Vol: vol,
			Amount: amount,
			Vwap: vwap,
			AdjFactor: adjFactor,
			TurnoverRatio: turnoverRatio,
			FreeShare: freeShare,
			TotalShare: totalShare,
			FreeMv: freeMv,
			TotalMv: totalMv,
		}
	}

	return items, nil
}
