// Code generated by tushare-gen. DO NOT EDIT.

package hk_stock

import (
	"context"
	"fmt"

	"tushare-go/pkg/sdk"
)

// HkFinaIndicatorRequest 表示 港股财务指标数据 API 的请求
type HkFinaIndicatorRequest struct {
	TsCode string `json:"ts_code,omitempty"` // 股票代码
	Period string `json:"period,omitempty"` // 报告期(格式：YYYYMMDD）
	ReportType string `json:"report_type,omitempty"` // 报告期类型（Q1一季报Q2半年报Q3三季报Q4年报）
	StartDate string `json:"start_date,omitempty"` // 报告期开始日期(格式：YYYYMMDD）
	EndDate string `json:"end_date,omitempty"` // 报告结束日期(格式：YYYYMMDD）
}

// HkFinaIndicatorItem 表示单个 港股财务指标数据 数据项
type HkFinaIndicatorItem struct {
	TsCode string `json:"ts_code"` // 股票代码
	Name string `json:"name"` // 股票名称
	EndDate string `json:"end_date"` // 报告期
	IndType string `json:"ind_type"` // 报告类型,Q-按报告期(季度),Y-按年度
	ReportType string `json:"report_type"` // 报告期类型
	StdReportDate string `json:"std_report_date"` // 标准报告期
	PerNetcashOperate float64 `json:"per_netcash_operate"` // 每股经营现金流(元)
	PerOi float64 `json:"per_oi"` // 每股营业收入(元)
	Bps float64 `json:"bps"` // 每股净资产(元)
	BasicEps float64 `json:"basic_eps"` // 基本每股收益(元)
	DilutedEps float64 `json:"diluted_eps"` // 稀释每股收益(元)
	OperateIncome float64 `json:"operate_income"` // 营业总收入(元)
	OperateIncomeYoy float64 `json:"operate_income_yoy"` // 营业总收入同比增长(%)
	GrossProfit float64 `json:"gross_profit"` // 毛利润(元)
	GrossProfitYoy float64 `json:"gross_profit_yoy"` // 毛利润同比增长(%)
	HolderProfit float64 `json:"holder_profit"` // 归母净利润(元)
	HolderProfitYoy float64 `json:"holder_profit_yoy"` // 归母净利润同比增长(%)
	GrossProfitRatio float64 `json:"gross_profit_ratio"` // 毛利率(%)
	EpsTtm float64 `json:"eps_ttm"` // ttm每股收益(元)
	OperateIncomeQoq float64 `json:"operate_income_qoq"` // 营业总收入滚动环比增长(%)
	NetProfitRatio float64 `json:"net_profit_ratio"` // 净利率(%)
	RoeAvg float64 `json:"roe_avg"` // 平均净资产收益率(%)
	GrossProfitQoq float64 `json:"gross_profit_qoq"` // 毛利润滚动环比增长(%)
	Roa float64 `json:"roa"` // 总资产净利率(%)
	HolderProfitQoq float64 `json:"holder_profit_qoq"` // 归母净利润滚动环比增长(%)
	RoeYearly float64 `json:"roe_yearly"` // 年化净资产收益率(%)
	RoicYearly float64 `json:"roic_yearly"` // 年化投资回报率(%)
	TotalAssets float64 `json:"total_assets"` // 资产总额
	TotalLiabilities float64 `json:"total_liabilities"` // 负债总额
	TaxEbt float64 `json:"tax_ebt"` // 所得税/利润总额(%)
	OcfSales float64 `json:"ocf_sales"` // 经营现金流/营业收入(%)
	TotalParentEquity float64 `json:"total_parent_equity"` // 本公司权益持有人应占权益
	DebtAssetRatio float64 `json:"debt_asset_ratio"` // 资产负债率(%)
	OperateProfit float64 `json:"operate_profit"` // 经营盈利
	PretaxProfit float64 `json:"pretax_profit"` // 除税前盈利
	NetcashOperate float64 `json:"netcash_operate"` // 经营活动所得现金流量净额
	NetcashInvest float64 `json:"netcash_invest"` // 投资活动耗用现金流量净额
	NetcashFinance float64 `json:"netcash_finance"` // 融资活动耗用现金流量净额
	EndCash float64 `json:"end_cash"` // 期末的现金及现金等价物
	DiviRatio float64 `json:"divi_ratio"` // 分红比例
	DividendRate float64 `json:"dividend_rate"` // 股息率
	CurrentRatio float64 `json:"current_ratio"` // 流动比率(倍)
	CommonAcs float64 `json:"common_acs"` // 普通股应计股息
	CurrentdebtDebt float64 `json:"currentdebt_debt"` // 流动负债/总负债(%)
	IssuedCommonShares float64 `json:"issued_common_shares"` // 已发行普通股
	HkCommonShares float64 `json:"hk_common_shares"` // 港股本(不建议使用数据源有误)
	PerShares float64 `json:"per_shares"` // 每手股数
	TotalMarketCap float64 `json:"total_market_cap"` // 总市值
	HkskMarketCap float64 `json:"hksk_market_cap"` // 港股市值
	PeTtm float64 `json:"pe_ttm"` // 滚动市盈率
	PbTtm float64 `json:"pb_ttm"` // 滚动市净率
	ReportDateSq string `json:"report_date_sq"` // 季报日期
	ReportTypeSq string `json:"report_type_sq"` // 报告类型
	OperateIncomeSq float64 `json:"operate_income_sq"` // 营业收入
	DpsHkd float64 `json:"dps_hkd"` // 每股股息（港元）
	OperateIncomeQoqSq float64 `json:"operate_income_qoq_sq"` // 营业收入环比
	NetProfitRatioSq float64 `json:"net_profit_ratio_sq"` // 净利润率
	HolderProfitSq float64 `json:"holder_profit_sq"` // 归属于股东净利润
	HolderProfitQoqSq float64 `json:"holder_profit_qoq_sq"` // 归母净利润环比
	RoeAvgSq float64 `json:"roe_avg_sq"` // 平均净资产收益率
	PeTtmSq float64 `json:"pe_ttm_sq"` // 季报滚动市盈率
	PbTtmSq float64 `json:"pb_ttm_sq"` // 季报滚动市净率
	RoaSq float64 `json:"roa_sq"` // 总资产收益率
	StartDate float64 `json:"start_date"` // 会计年度起始日
	FiscalYear float64 `json:"fiscal_year"` // 会计年度截止日
	Currency string `json:"currency"` // 币种 港元（hkd）
	IsCnyCode float64 `json:"is_cny_code"` // 是否人民币代码
	DpsHkdLy float64 `json:"dps_hkd_ly"` // 上一年每股股息
	OrgType string `json:"org_type"` // 企业类型
	PremiumIncome float64 `json:"premium_income"` // 保费收入
	PremiumIncomeYoy float64 `json:"premium_income_yoy"` // 保费收入同比
	NetInterestIncome float64 `json:"net_interest_income"` // 净利息收入
	NetInterestIncomeYoy float64 `json:"net_interest_income_yoy"` // 净利息收入同比
	FeeCommissionIncome float64 `json:"fee_commission_income"` // 手续费及佣金收入
	FeeCommissionIncomeYoy float64 `json:"fee_commission_income_yoy"` // 手续费及佣金收入同比
	AccountsReceTdays float64 `json:"accounts_rece_tdays"` // 应收账款周转率(次)
	InventoryTdays float64 `json:"inventory_tdays"` // 存货周转率(次)
	CurrentAssetsTdays float64 `json:"current_assets_tdays"` // 流动资产周转率(次)
	TotalAssetsTdays float64 `json:"total_assets_tdays"` // 总资产周转率(次)
	PremiumExpense float64 `json:"premium_expense"` // 保险赔付支出
	LoanDeposit float64 `json:"loan_deposit"` // 贷款/存款
	LoanEquity float64 `json:"loan_equity"` // 贷款/股东权益
	LoanAssets float64 `json:"loan_assets"` // 贷款/总资产
	DepositEquity float64 `json:"deposit_equity"` // 存款/股东权益
	DepositAssets float64 `json:"deposit_assets"` // 存款/总资产
	EquityMultiplier float64 `json:"equity_multiplier"` // 权益乘数
	EquityRatio float64 `json:"equity_ratio"` // 产权比率
}

// HkFinaIndicator 调用 港股财务指标数据 API
// 获取港股上市公司财务指标数据，为避免服务器压力，现阶段每次请求最多返回200条记录，可通过设置日期多次请求获取更多数据。
// 注意：积分要求等使用限制请参考Tushare官方文档
func HkFinaIndicator(ctx context.Context, client *sdk.Client, req *HkFinaIndicatorRequest) ([]HkFinaIndicatorItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.Period != "" {
		params["period"] = req.Period
	}
	if req.ReportType != "" {
		params["report_type"] = req.ReportType
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}

	fields := []string{"ts_code", "name", "end_date", "ind_type", "report_type", "std_report_date", "per_netcash_operate", "per_oi", "bps", "basic_eps", "diluted_eps", "operate_income", "operate_income_yoy", "gross_profit", "gross_profit_yoy", "holder_profit", "holder_profit_yoy", "gross_profit_ratio", "eps_ttm", "operate_income_qoq", "net_profit_ratio", "roe_avg", "gross_profit_qoq", "roa", "holder_profit_qoq", "roe_yearly", "roic_yearly", "total_assets", "total_liabilities", "tax_ebt", "ocf_sales", "total_parent_equity", "debt_asset_ratio", "operate_profit", "pretax_profit", "netcash_operate", "netcash_invest", "netcash_finance", "end_cash", "divi_ratio", "dividend_rate", "current_ratio", "common_acs", "currentdebt_debt", "issued_common_shares", "hk_common_shares", "per_shares", "total_market_cap", "hksk_market_cap", "pe_ttm", "pb_ttm", "report_date_sq", "report_type_sq", "operate_income_sq", "dps_hkd", "operate_income_qoq_sq", "net_profit_ratio_sq", "holder_profit_sq", "holder_profit_qoq_sq", "roe_avg_sq", "pe_ttm_sq", "pb_ttm_sq", "roa_sq", "start_date", "fiscal_year", "currency", "is_cny_code", "dps_hkd_ly", "org_type", "premium_income", "premium_income_yoy", "net_interest_income", "net_interest_income_yoy", "fee_commission_income", "fee_commission_income_yoy", "accounts_rece_tdays", "inventory_tdays", "current_assets_tdays", "total_assets_tdays", "premium_expense", "loan_deposit", "loan_equity", "loan_assets", "deposit_equity", "deposit_assets", "equity_multiplier", "equity_ratio"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPIFlexible(ctx, "hk_fina_indicator", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]HkFinaIndicatorItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 ts_code 的简单类型
		// 对 string 类型尝试多种转换
		var tsCode string
		if v, ok := item["ts_code"].(string); ok {
			tsCode = v
		} else if v, ok := item["ts_code"].(float64); ok {
			tsCode = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["ts_code"].(int); ok {
			tsCode = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 name 的简单类型
		// 对 string 类型尝试多种转换
		var name string
		if v, ok := item["name"].(string); ok {
			name = v
		} else if v, ok := item["name"].(float64); ok {
			name = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["name"].(int); ok {
			name = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 name 类型")
		}
		// 处理 end_date 的简单类型
		// 对 string 类型尝试多种转换
		var endDate string
		if v, ok := item["end_date"].(string); ok {
			endDate = v
		} else if v, ok := item["end_date"].(float64); ok {
			endDate = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["end_date"].(int); ok {
			endDate = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 end_date 类型")
		}
		// 处理 ind_type 的简单类型
		// 对 string 类型尝试多种转换
		var indType string
		if v, ok := item["ind_type"].(string); ok {
			indType = v
		} else if v, ok := item["ind_type"].(float64); ok {
			indType = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["ind_type"].(int); ok {
			indType = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 ind_type 类型")
		}
		// 处理 report_type 的简单类型
		// 对 string 类型尝试多种转换
		var reportType string
		if v, ok := item["report_type"].(string); ok {
			reportType = v
		} else if v, ok := item["report_type"].(float64); ok {
			reportType = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["report_type"].(int); ok {
			reportType = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 report_type 类型")
		}
		// 处理 std_report_date 的简单类型
		// 对 string 类型尝试多种转换
		var stdReportDate string
		if v, ok := item["std_report_date"].(string); ok {
			stdReportDate = v
		} else if v, ok := item["std_report_date"].(float64); ok {
			stdReportDate = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["std_report_date"].(int); ok {
			stdReportDate = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 std_report_date 类型")
		}
		// 处理 per_netcash_operate 的简单类型
		perNetcashOperate, ok := item["per_netcash_operate"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 per_netcash_operate 类型")
		}
		// 处理 per_oi 的简单类型
		perOi, ok := item["per_oi"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 per_oi 类型")
		}
		// 处理 bps 的简单类型
		bps, ok := item["bps"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 bps 类型")
		}
		// 处理 basic_eps 的简单类型
		basicEps, ok := item["basic_eps"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 basic_eps 类型")
		}
		// 处理 diluted_eps 的简单类型
		dilutedEps, ok := item["diluted_eps"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 diluted_eps 类型")
		}
		// 处理 operate_income 的简单类型
		operateIncome, ok := item["operate_income"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 operate_income 类型")
		}
		// 处理 operate_income_yoy 的简单类型
		operateIncomeYoy, ok := item["operate_income_yoy"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 operate_income_yoy 类型")
		}
		// 处理 gross_profit 的简单类型
		grossProfit, ok := item["gross_profit"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 gross_profit 类型")
		}
		// 处理 gross_profit_yoy 的简单类型
		grossProfitYoy, ok := item["gross_profit_yoy"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 gross_profit_yoy 类型")
		}
		// 处理 holder_profit 的简单类型
		holderProfit, ok := item["holder_profit"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 holder_profit 类型")
		}
		// 处理 holder_profit_yoy 的简单类型
		holderProfitYoy, ok := item["holder_profit_yoy"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 holder_profit_yoy 类型")
		}
		// 处理 gross_profit_ratio 的简单类型
		grossProfitRatio, ok := item["gross_profit_ratio"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 gross_profit_ratio 类型")
		}
		// 处理 eps_ttm 的简单类型
		epsTtm, ok := item["eps_ttm"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 eps_ttm 类型")
		}
		// 处理 operate_income_qoq 的简单类型
		operateIncomeQoq, ok := item["operate_income_qoq"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 operate_income_qoq 类型")
		}
		// 处理 net_profit_ratio 的简单类型
		netProfitRatio, ok := item["net_profit_ratio"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 net_profit_ratio 类型")
		}
		// 处理 roe_avg 的简单类型
		roeAvg, ok := item["roe_avg"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 roe_avg 类型")
		}
		// 处理 gross_profit_qoq 的简单类型
		grossProfitQoq, ok := item["gross_profit_qoq"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 gross_profit_qoq 类型")
		}
		// 处理 roa 的简单类型
		roa, ok := item["roa"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 roa 类型")
		}
		// 处理 holder_profit_qoq 的简单类型
		holderProfitQoq, ok := item["holder_profit_qoq"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 holder_profit_qoq 类型")
		}
		// 处理 roe_yearly 的简单类型
		roeYearly, ok := item["roe_yearly"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 roe_yearly 类型")
		}
		// 处理 roic_yearly 的简单类型
		roicYearly, ok := item["roic_yearly"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 roic_yearly 类型")
		}
		// 处理 total_assets 的简单类型
		totalAssets, ok := item["total_assets"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 total_assets 类型")
		}
		// 处理 total_liabilities 的简单类型
		totalLiabilities, ok := item["total_liabilities"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 total_liabilities 类型")
		}
		// 处理 tax_ebt 的简单类型
		taxEbt, ok := item["tax_ebt"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 tax_ebt 类型")
		}
		// 处理 ocf_sales 的简单类型
		ocfSales, ok := item["ocf_sales"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 ocf_sales 类型")
		}
		// 处理 total_parent_equity 的简单类型
		totalParentEquity, ok := item["total_parent_equity"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 total_parent_equity 类型")
		}
		// 处理 debt_asset_ratio 的简单类型
		debtAssetRatio, ok := item["debt_asset_ratio"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 debt_asset_ratio 类型")
		}
		// 处理 operate_profit 的简单类型
		operateProfit, ok := item["operate_profit"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 operate_profit 类型")
		}
		// 处理 pretax_profit 的简单类型
		pretaxProfit, ok := item["pretax_profit"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 pretax_profit 类型")
		}
		// 处理 netcash_operate 的简单类型
		netcashOperate, ok := item["netcash_operate"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 netcash_operate 类型")
		}
		// 处理 netcash_invest 的简单类型
		netcashInvest, ok := item["netcash_invest"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 netcash_invest 类型")
		}
		// 处理 netcash_finance 的简单类型
		netcashFinance, ok := item["netcash_finance"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 netcash_finance 类型")
		}
		// 处理 end_cash 的简单类型
		endCash, ok := item["end_cash"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 end_cash 类型")
		}
		// 处理 divi_ratio 的简单类型
		diviRatio, ok := item["divi_ratio"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 divi_ratio 类型")
		}
		// 处理 dividend_rate 的简单类型
		dividendRate, ok := item["dividend_rate"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 dividend_rate 类型")
		}
		// 处理 current_ratio 的简单类型
		currentRatio, ok := item["current_ratio"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 current_ratio 类型")
		}
		// 处理 common_acs 的简单类型
		commonAcs, ok := item["common_acs"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 common_acs 类型")
		}
		// 处理 currentdebt_debt 的简单类型
		currentdebtDebt, ok := item["currentdebt_debt"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 currentdebt_debt 类型")
		}
		// 处理 issued_common_shares 的简单类型
		issuedCommonShares, ok := item["issued_common_shares"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 issued_common_shares 类型")
		}
		// 处理 hk_common_shares 的简单类型
		hkCommonShares, ok := item["hk_common_shares"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 hk_common_shares 类型")
		}
		// 处理 per_shares 的简单类型
		perShares, ok := item["per_shares"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 per_shares 类型")
		}
		// 处理 total_market_cap 的简单类型
		totalMarketCap, ok := item["total_market_cap"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 total_market_cap 类型")
		}
		// 处理 hksk_market_cap 的简单类型
		hkskMarketCap, ok := item["hksk_market_cap"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 hksk_market_cap 类型")
		}
		// 处理 pe_ttm 的简单类型
		peTtm, ok := item["pe_ttm"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 pe_ttm 类型")
		}
		// 处理 pb_ttm 的简单类型
		pbTtm, ok := item["pb_ttm"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 pb_ttm 类型")
		}
		// 处理 report_date_sq 的简单类型
		// 对 string 类型尝试多种转换
		var reportDateSq string
		if v, ok := item["report_date_sq"].(string); ok {
			reportDateSq = v
		} else if v, ok := item["report_date_sq"].(float64); ok {
			reportDateSq = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["report_date_sq"].(int); ok {
			reportDateSq = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 report_date_sq 类型")
		}
		// 处理 report_type_sq 的简单类型
		// 对 string 类型尝试多种转换
		var reportTypeSq string
		if v, ok := item["report_type_sq"].(string); ok {
			reportTypeSq = v
		} else if v, ok := item["report_type_sq"].(float64); ok {
			reportTypeSq = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["report_type_sq"].(int); ok {
			reportTypeSq = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 report_type_sq 类型")
		}
		// 处理 operate_income_sq 的简单类型
		operateIncomeSq, ok := item["operate_income_sq"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 operate_income_sq 类型")
		}
		// 处理 dps_hkd 的简单类型
		dpsHkd, ok := item["dps_hkd"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 dps_hkd 类型")
		}
		// 处理 operate_income_qoq_sq 的简单类型
		operateIncomeQoqSq, ok := item["operate_income_qoq_sq"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 operate_income_qoq_sq 类型")
		}
		// 处理 net_profit_ratio_sq 的简单类型
		netProfitRatioSq, ok := item["net_profit_ratio_sq"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 net_profit_ratio_sq 类型")
		}
		// 处理 holder_profit_sq 的简单类型
		holderProfitSq, ok := item["holder_profit_sq"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 holder_profit_sq 类型")
		}
		// 处理 holder_profit_qoq_sq 的简单类型
		holderProfitQoqSq, ok := item["holder_profit_qoq_sq"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 holder_profit_qoq_sq 类型")
		}
		// 处理 roe_avg_sq 的简单类型
		roeAvgSq, ok := item["roe_avg_sq"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 roe_avg_sq 类型")
		}
		// 处理 pe_ttm_sq 的简单类型
		peTtmSq, ok := item["pe_ttm_sq"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 pe_ttm_sq 类型")
		}
		// 处理 pb_ttm_sq 的简单类型
		pbTtmSq, ok := item["pb_ttm_sq"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 pb_ttm_sq 类型")
		}
		// 处理 roa_sq 的简单类型
		roaSq, ok := item["roa_sq"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 roa_sq 类型")
		}
		// 处理 start_date 的简单类型
		startDate, ok := item["start_date"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 start_date 类型")
		}
		// 处理 fiscal_year 的简单类型
		fiscalYear, ok := item["fiscal_year"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 fiscal_year 类型")
		}
		// 处理 currency 的简单类型
		// 对 string 类型尝试多种转换
		var currency string
		if v, ok := item["currency"].(string); ok {
			currency = v
		} else if v, ok := item["currency"].(float64); ok {
			currency = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["currency"].(int); ok {
			currency = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 currency 类型")
		}
		// 处理 is_cny_code 的简单类型
		isCnyCode, ok := item["is_cny_code"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 is_cny_code 类型")
		}
		// 处理 dps_hkd_ly 的简单类型
		dpsHkdLy, ok := item["dps_hkd_ly"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 dps_hkd_ly 类型")
		}
		// 处理 org_type 的简单类型
		// 对 string 类型尝试多种转换
		var orgType string
		if v, ok := item["org_type"].(string); ok {
			orgType = v
		} else if v, ok := item["org_type"].(float64); ok {
			orgType = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["org_type"].(int); ok {
			orgType = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 org_type 类型")
		}
		// 处理 premium_income 的简单类型
		premiumIncome, ok := item["premium_income"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 premium_income 类型")
		}
		// 处理 premium_income_yoy 的简单类型
		premiumIncomeYoy, ok := item["premium_income_yoy"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 premium_income_yoy 类型")
		}
		// 处理 net_interest_income 的简单类型
		netInterestIncome, ok := item["net_interest_income"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 net_interest_income 类型")
		}
		// 处理 net_interest_income_yoy 的简单类型
		netInterestIncomeYoy, ok := item["net_interest_income_yoy"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 net_interest_income_yoy 类型")
		}
		// 处理 fee_commission_income 的简单类型
		feeCommissionIncome, ok := item["fee_commission_income"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 fee_commission_income 类型")
		}
		// 处理 fee_commission_income_yoy 的简单类型
		feeCommissionIncomeYoy, ok := item["fee_commission_income_yoy"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 fee_commission_income_yoy 类型")
		}
		// 处理 accounts_rece_tdays 的简单类型
		accountsReceTdays, ok := item["accounts_rece_tdays"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 accounts_rece_tdays 类型")
		}
		// 处理 inventory_tdays 的简单类型
		inventoryTdays, ok := item["inventory_tdays"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 inventory_tdays 类型")
		}
		// 处理 current_assets_tdays 的简单类型
		currentAssetsTdays, ok := item["current_assets_tdays"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 current_assets_tdays 类型")
		}
		// 处理 total_assets_tdays 的简单类型
		totalAssetsTdays, ok := item["total_assets_tdays"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 total_assets_tdays 类型")
		}
		// 处理 premium_expense 的简单类型
		premiumExpense, ok := item["premium_expense"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 premium_expense 类型")
		}
		// 处理 loan_deposit 的简单类型
		loanDeposit, ok := item["loan_deposit"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 loan_deposit 类型")
		}
		// 处理 loan_equity 的简单类型
		loanEquity, ok := item["loan_equity"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 loan_equity 类型")
		}
		// 处理 loan_assets 的简单类型
		loanAssets, ok := item["loan_assets"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 loan_assets 类型")
		}
		// 处理 deposit_equity 的简单类型
		depositEquity, ok := item["deposit_equity"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 deposit_equity 类型")
		}
		// 处理 deposit_assets 的简单类型
		depositAssets, ok := item["deposit_assets"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 deposit_assets 类型")
		}
		// 处理 equity_multiplier 的简单类型
		equityMultiplier, ok := item["equity_multiplier"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 equity_multiplier 类型")
		}
		// 处理 equity_ratio 的简单类型
		equityRatio, ok := item["equity_ratio"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 equity_ratio 类型")
		}
		items[i] = HkFinaIndicatorItem{
			TsCode: tsCode,
			Name: name,
			EndDate: endDate,
			IndType: indType,
			ReportType: reportType,
			StdReportDate: stdReportDate,
			PerNetcashOperate: perNetcashOperate,
			PerOi: perOi,
			Bps: bps,
			BasicEps: basicEps,
			DilutedEps: dilutedEps,
			OperateIncome: operateIncome,
			OperateIncomeYoy: operateIncomeYoy,
			GrossProfit: grossProfit,
			GrossProfitYoy: grossProfitYoy,
			HolderProfit: holderProfit,
			HolderProfitYoy: holderProfitYoy,
			GrossProfitRatio: grossProfitRatio,
			EpsTtm: epsTtm,
			OperateIncomeQoq: operateIncomeQoq,
			NetProfitRatio: netProfitRatio,
			RoeAvg: roeAvg,
			GrossProfitQoq: grossProfitQoq,
			Roa: roa,
			HolderProfitQoq: holderProfitQoq,
			RoeYearly: roeYearly,
			RoicYearly: roicYearly,
			TotalAssets: totalAssets,
			TotalLiabilities: totalLiabilities,
			TaxEbt: taxEbt,
			OcfSales: ocfSales,
			TotalParentEquity: totalParentEquity,
			DebtAssetRatio: debtAssetRatio,
			OperateProfit: operateProfit,
			PretaxProfit: pretaxProfit,
			NetcashOperate: netcashOperate,
			NetcashInvest: netcashInvest,
			NetcashFinance: netcashFinance,
			EndCash: endCash,
			DiviRatio: diviRatio,
			DividendRate: dividendRate,
			CurrentRatio: currentRatio,
			CommonAcs: commonAcs,
			CurrentdebtDebt: currentdebtDebt,
			IssuedCommonShares: issuedCommonShares,
			HkCommonShares: hkCommonShares,
			PerShares: perShares,
			TotalMarketCap: totalMarketCap,
			HkskMarketCap: hkskMarketCap,
			PeTtm: peTtm,
			PbTtm: pbTtm,
			ReportDateSq: reportDateSq,
			ReportTypeSq: reportTypeSq,
			OperateIncomeSq: operateIncomeSq,
			DpsHkd: dpsHkd,
			OperateIncomeQoqSq: operateIncomeQoqSq,
			NetProfitRatioSq: netProfitRatioSq,
			HolderProfitSq: holderProfitSq,
			HolderProfitQoqSq: holderProfitQoqSq,
			RoeAvgSq: roeAvgSq,
			PeTtmSq: peTtmSq,
			PbTtmSq: pbTtmSq,
			RoaSq: roaSq,
			StartDate: startDate,
			FiscalYear: fiscalYear,
			Currency: currency,
			IsCnyCode: isCnyCode,
			DpsHkdLy: dpsHkdLy,
			OrgType: orgType,
			PremiumIncome: premiumIncome,
			PremiumIncomeYoy: premiumIncomeYoy,
			NetInterestIncome: netInterestIncome,
			NetInterestIncomeYoy: netInterestIncomeYoy,
			FeeCommissionIncome: feeCommissionIncome,
			FeeCommissionIncomeYoy: feeCommissionIncomeYoy,
			AccountsReceTdays: accountsReceTdays,
			InventoryTdays: inventoryTdays,
			CurrentAssetsTdays: currentAssetsTdays,
			TotalAssetsTdays: totalAssetsTdays,
			PremiumExpense: premiumExpense,
			LoanDeposit: loanDeposit,
			LoanEquity: loanEquity,
			LoanAssets: loanAssets,
			DepositEquity: depositEquity,
			DepositAssets: depositAssets,
			EquityMultiplier: equityMultiplier,
			EquityRatio: equityRatio,
		}
	}

	return items, nil
}
