// Code generated by gen-mcp-tools. DO NOT EDIT.

package etftools

import (
	"context"
	"encoding/json"
	"fmt"

	etf "tushare-go/pkg/sdk/api/etf"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerRtMin registers the tool
func (r *EtfTools) registerRtMin() {
	inputSchema, _ := jsonschema.For[RtMinInput](nil)

	tool := &mcp.Tool{
		Name:        "etf.rt_min",
		Description: "Retrieve rtmin data from Tushare etf API",
		InputSchema: inputSchema,
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input RtMinInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &etf.RtMinRequest{
Freq: input.Freq,
TsCode: input.TsCode,

		}

		items, err := etf.RtMin(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := RtMinOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
