// Code generated by gen-mcp-tools. DO NOT EDIT.

package etftools

import (
	"context"

	etf "github.com/chenniannian90/tushare-go/pkg/sdk/api/etf"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// callStkMins handles StkMins tool calls
func (m *EtfTools) callStkMins(ctx context.Context, args map[string]interface{}) (*common.ToolResult, error) {
	req := &etf.StkMinsRequest{}

	// Parse arguments into request
	if err := common.ParseInput(args, req); err != nil {
		return common.ErrorResult(err), nil
	}

	items, err := etf.StkMins(ctx, m.client, req)
	if err != nil {
		return common.ErrorResult(err), nil
	}

	// Format results
	result, err := common.APIResult(items, "etf", "stk_mins")
	if err != nil {
		return common.ErrorResult(err), nil
	}
	return result, nil
}
