// Code generated by gen-mcp-tools. DO NOT EDIT.

package fundtools

import (
	"context"
	"fmt"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// FundTools implements tools for fund API
type FundTools struct {
	client *sdk.Client
}

// NewFundTools creates a new fund tools instance
func NewFundTools(client *sdk.Client) *FundTools {
	return &FundTools{
		client: client,
	}
}

// GetAPIName returns the Tushare API name for this module
func (m *FundTools) GetAPIName() string {
	return "fund"
}

// ListTools returns all available tools in this module
func (m *FundTools) ListTools() []common.Tool {
	return []common.Tool{
		{
			Name: "fund.api359",
			Description: "Access api359 data from Tushare API",
		},
		{
			Name: "fund.fund_basic",
			Description: "Access fund_basic data from Tushare API",
		},
		{
			Name: "fund.fund_div",
			Description: "Access fund_div data from Tushare API",
		},
		{
			Name: "fund.fund_manager",
			Description: "Access fund_manager data from Tushare API",
		},
		{
			Name: "fund.fund_nav",
			Description: "Access fund_nav data from Tushare API",
		},
		{
			Name: "fund.fund_portfolio",
			Description: "Access fund_portfolio data from Tushare API",
		},
	}
}

// HandlesTool checks if this module handles a tool
func (m *FundTools) HandlesTool(toolName string) bool {
	tools := m.ListTools()
	for _, tool := range tools {
		if tool.Name == toolName {
			return true
		}
	}
	return false
}

// CallTool executes a tool call
func (m *FundTools) CallTool(ctx context.Context, toolName string, args map[string]interface{}) (*common.ToolResult, error) {
	switch toolName {
	case "fund.api359":
		return m.callApi359(ctx, args)
	case "fund.fund_basic":
		return m.callFundBasic(ctx, args)
	case "fund.fund_div":
		return m.callFundDiv(ctx, args)
	case "fund.fund_manager":
		return m.callFundManager(ctx, args)
	case "fund.fund_nav":
		return m.callFundNav(ctx, args)
	case "fund.fund_portfolio":
		return m.callFundPortfolio(ctx, args)
	default:
		return nil, fmt.Errorf("unknown tool: %s", toolName)
	}
}
