// Code generated by gen-mcp-tools. DO NOT EDIT.

package fundtools

import (
	"context"
	"fmt"

	fund "github.com/chenniannian90/tushare-go/pkg/sdk/api/fund"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// callFundCompany handles FundCompany tool calls
func (m *FundTools) callFundCompany(ctx context.Context, args map[string]interface{}) (*common.ToolResult, error) {
	req := &fund.FundCompanyRequest{}

	// Parse arguments into request
	// TODO: Implement proper argument parsing based on request struct fields
	// For now, this is a placeholder implementation

	items, err := fund.FundCompany(ctx, m.client, req)
	if err != nil {
		return nil, fmt.Errorf("failed to call fund_company API: %w", err)
	}

	// Format results
	result, err := common.APIResult(items, "fund", "fund_company")
	if err != nil {
		return nil, err
	}
	return result, nil
}
