// Code generated by gen-mcp-tools. DO NOT EDIT.

package fundtools

import (
	"context"
	"encoding/json"
	"fmt"

	fund "tushare-go/pkg/sdk/api/fund"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerFundDiv registers the tool
func (r *FundTools) registerFundDiv() {
	inputSchema, _ := jsonschema.For[FundDivInput](nil)

	tool := &mcp.Tool{
		Name:        "fund.fund_div",
		Description: "获取公募基金分红数据",
		InputSchema: inputSchema,
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input FundDivInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &fund.FundDivRequest{
AnnDate: input.AnnDate,
ExDate: input.ExDate,
PayDate: input.PayDate,
TsCode: input.TsCode,

		}

		items, err := fund.FundDiv(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := FundDivOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
