// Code generated by gen-mcp-tools. DO NOT EDIT.

package fundtools

import (
	"context"

	fund "github.com/chenniannian90/tushare-go/pkg/sdk/api/fund"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// callFundNav handles FundNav tool calls
func (m *FundTools) callFundNav(ctx context.Context, args map[string]interface{}) (*common.ToolResult, error) {
	req := &fund.FundNavRequest{}

	// Parse arguments into request
	if err := common.ParseInput(args, req); err != nil {
		return common.ErrorResult(err), nil
	}

	items, err := fund.FundNav(ctx, m.client, req)
	if err != nil {
		return common.ErrorResult(err), nil
	}

	// Format results
	result, err := common.APIResult(items, "fund", "fund_nav")
	if err != nil {
		return common.ErrorResult(err), nil
	}
	return result, nil
}
