// Code generated by gen-mcp-tools. DO NOT EDIT.

package forextools

import (
	"context"

	forex "github.com/chenniannian90/tushare-go/pkg/sdk/api/forex"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// callFxObasic handles FxObasic tool calls
func (m *ForexTools) callFxObasic(ctx context.Context, args map[string]interface{}) (*common.ToolResult, error) {
	req := &forex.FxObasicRequest{}

	// Parse arguments into request
	if err := common.ParseInput(args, req); err != nil {
		return common.ErrorResult(err), nil
	}

	items, err := forex.FxObasic(ctx, m.client, req)
	if err != nil {
		return common.ErrorResult(err), nil
	}

	// Format results
	result, err := common.APIResult(items, "forex", "fx_obasic")
	if err != nil {
		return common.ErrorResult(err), nil
	}
	return result, nil
}
