// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_boardtools

import (
	"context"
	"encoding/json"
	"fmt"

	stock_stock_board "tushare-go/pkg/sdk/api/stock/stock_board"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerDcDaily registers the tool
func (r *Stock_boardTools) registerDcDaily() {
	inputSchema, _ := jsonschema.For[DcDailyInput](nil)

	tool := &mcp.Tool{
		Name:        "stock_board.dc_daily",
		Description: "Retrieve dcdaily data from Tushare stock board API",
		InputSchema: inputSchema,
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input DcDailyInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &stock_stock_board.DcDailyRequest{

		}

		items, err := stock_stock_board.DcDaily(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := DcDailyOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
