// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_boardtools

import (
	"context"
	"encoding/json"
	"fmt"

	stock_stock_board "tushare-go/pkg/sdk/api/stock/stock_board"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerKplList registers the tool
func (r *Stock_boardTools) registerKplList() {
	inputSchema, _ := jsonschema.For[KplListInput](nil)

	tool := &mcp.Tool{
		Name:        "stock_board.kpl_list",
		Description: "Retrieve kpllist data from Tushare stock board API",
		InputSchema: inputSchema,
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input KplListInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &stock_stock_board.KplListRequest{
TsCode: input.TsCode,
TradeDate: input.TradeDate,
Tag: input.Tag,
StartDate: input.StartDate,
EndDate: input.EndDate,

		}

		items, err := stock_stock_board.KplList(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := KplListOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
