// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_boardtools

import (
	stock_stock_board "tushare-go/pkg/sdk/api/stock/stock_board"

)


// DcDailyInput defines the input schema
type DcDailyInput struct {

}

// DcDailyOutput defines the output schema
type DcDailyOutput struct {
	Data  []stock_stock_board.DcDailyItem `json:data jsonschema:dc_daily data list`
	Total int              `json:total jsonschema:Total count`
}

// DcHotInput defines the input schema
type DcHotInput struct {

}

// DcHotOutput defines the output schema
type DcHotOutput struct {
	Data  []stock_stock_board.DcHotItem `json:data jsonschema:dc_hot data list`
	Total int              `json:total jsonschema:Total count`
}

// DcIndexInput defines the input schema
type DcIndexInput struct {

}

// DcIndexOutput defines the output schema
type DcIndexOutput struct {
	Data  []stock_stock_board.DcIndexItem `json:data jsonschema:dc_index data list`
	Total int              `json:total jsonschema:Total count`
}

// DcMemberInput defines the input schema
type DcMemberInput struct {

}

// DcMemberOutput defines the output schema
type DcMemberOutput struct {
	Data  []stock_stock_board.DcMemberItem `json:data jsonschema:dc_member data list`
	Total int              `json:total jsonschema:Total count`
}

// HmDetailInput defines the input schema
type HmDetailInput struct {

}

// HmDetailOutput defines the output schema
type HmDetailOutput struct {
	Data  []stock_stock_board.HmDetailItem `json:data jsonschema:hm_detail data list`
	Total int              `json:total jsonschema:Total count`
}

// HmListInput defines the input schema
type HmListInput struct {

}

// HmListOutput defines the output schema
type HmListOutput struct {
	Data  []stock_stock_board.HmListItem `json:data jsonschema:hm_list data list`
	Total int              `json:total jsonschema:Total count`
}

// KplConceptConsInput defines the input schema
type KplConceptConsInput struct {

}

// KplConceptConsOutput defines the output schema
type KplConceptConsOutput struct {
	Data  []stock_stock_board.KplConceptConsItem `json:data jsonschema:kpl_concept_cons data list`
	Total int              `json:total jsonschema:Total count`
}

// KplListInput defines the input schema
type KplListInput struct {

}

// KplListOutput defines the output schema
type KplListOutput struct {
	Data  []stock_stock_board.KplListItem `json:data jsonschema:kpl_list data list`
	Total int              `json:total jsonschema:Total count`
}

// LimitCptListInput defines the input schema
type LimitCptListInput struct {

}

// LimitCptListOutput defines the output schema
type LimitCptListOutput struct {
	Data  []stock_stock_board.LimitCptListItem `json:data jsonschema:limit_cpt_list data list`
	Total int              `json:total jsonschema:Total count`
}

// LimitListDInput defines the input schema
type LimitListDInput struct {

}

// LimitListDOutput defines the output schema
type LimitListDOutput struct {
	Data  []stock_stock_board.LimitListDItem `json:data jsonschema:limit_list_d data list`
	Total int              `json:total jsonschema:Total count`
}

// LimitListThsInput defines the input schema
type LimitListThsInput struct {

}

// LimitListThsOutput defines the output schema
type LimitListThsOutput struct {
	Data  []stock_stock_board.LimitListThsItem `json:data jsonschema:limit_list_ths data list`
	Total int              `json:total jsonschema:Total count`
}

// LimitStepInput defines the input schema
type LimitStepInput struct {

}

// LimitStepOutput defines the output schema
type LimitStepOutput struct {
	Data  []stock_stock_board.LimitStepItem `json:data jsonschema:limit_step data list`
	Total int              `json:total jsonschema:Total count`
}

// StkAuctionInput defines the input schema
type StkAuctionInput struct {

}

// StkAuctionOutput defines the output schema
type StkAuctionOutput struct {
	Data  []stock_stock_board.StkAuctionItem `json:data jsonschema:stk_auction data list`
	Total int              `json:total jsonschema:Total count`
}

// TdxDailyInput defines the input schema
type TdxDailyInput struct {

}

// TdxDailyOutput defines the output schema
type TdxDailyOutput struct {
	Data  []stock_stock_board.TdxDailyItem `json:data jsonschema:tdx_daily data list`
	Total int              `json:total jsonschema:Total count`
}

// TdxIndexInput defines the input schema
type TdxIndexInput struct {

}

// TdxIndexOutput defines the output schema
type TdxIndexOutput struct {
	Data  []stock_stock_board.TdxIndexItem `json:data jsonschema:tdx_index data list`
	Total int              `json:total jsonschema:Total count`
}

// TdxMemberInput defines the input schema
type TdxMemberInput struct {

}

// TdxMemberOutput defines the output schema
type TdxMemberOutput struct {
	Data  []stock_stock_board.TdxMemberItem `json:data jsonschema:tdx_member data list`
	Total int              `json:total jsonschema:Total count`
}

// ThsDailyInput defines the input schema
type ThsDailyInput struct {

}

// ThsDailyOutput defines the output schema
type ThsDailyOutput struct {
	Data  []stock_stock_board.ThsDailyItem `json:data jsonschema:ths_daily data list`
	Total int              `json:total jsonschema:Total count`
}

// ThsHotInput defines the input schema
type ThsHotInput struct {

}

// ThsHotOutput defines the output schema
type ThsHotOutput struct {
	Data  []stock_stock_board.ThsHotItem `json:data jsonschema:ths_hot data list`
	Total int              `json:total jsonschema:Total count`
}

// ThsIndexInput defines the input schema
type ThsIndexInput struct {

}

// ThsIndexOutput defines the output schema
type ThsIndexOutput struct {
	Data  []stock_stock_board.ThsIndexItem `json:data jsonschema:ths_index data list`
	Total int              `json:total jsonschema:Total count`
}

// ThsMemberInput defines the input schema
type ThsMemberInput struct {

}

// ThsMemberOutput defines the output schema
type ThsMemberOutput struct {
	Data  []stock_stock_board.ThsMemberItem `json:data jsonschema:ths_member data list`
	Total int              `json:total jsonschema:Total count`
}

// TopInstInput defines the input schema
type TopInstInput struct {

}

// TopInstOutput defines the output schema
type TopInstOutput struct {
	Data  []stock_stock_board.TopInstItem `json:data jsonschema:top_inst data list`
	Total int              `json:total jsonschema:Total count`
}

// TopListInput defines the input schema
type TopListInput struct {

}

// TopListOutput defines the output schema
type TopListOutput struct {
	Data  []stock_stock_board.TopListItem `json:data jsonschema:top_list data list`
	Total int              `json:total jsonschema:Total count`
}

