// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_basictools

import (
	"tushare-go/pkg/sdk"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// Stock_basicTools represents stock_basic tools
type Stock_basicTools struct {
	server *mcp.Server
	client *sdk.Client
}

// NewStock_basicTools creates a new instance
func NewStock_basicTools(server *mcp.Server, client *sdk.Client) *Stock_basicTools {
	return &Stock_basicTools{server: server, client: client}
}

// RegisterAll registers all tools
func (r *Stock_basicTools) RegisterAll() {
	r.registerBakBasic()
	r.registerBseMapping()
	r.registerNamechange()
	r.registerNewShare()
	r.registerSt()
	r.registerStkManagers()
	r.registerStkPremarket()
	r.registerStkRewards()
	r.registerStockBasic()
	r.registerStockCompany()
	r.registerStockHsgt()
	r.registerStockSt()
	r.registerTradeCal()

}
