// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_basictools

import (
	"context"
	"encoding/json"
	"fmt"

	stock_basic "tushare-go/pkg/sdk/api/stock_basic"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerStkRewards registers the tool
func (r *Stock_basicTools) registerStkRewards() {
	inputSchema, _ := jsonschema.For[StkRewardsInput](nil)

	tool := &mcp.Tool{
		Name:        "stock_basic.stk_rewards",
		Description: "获取上市公司管理层薪酬和持股",
		InputSchema: inputSchema,
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input StkRewardsInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &stock_basic.StkRewardsRequest{
TsCode: input.TsCode,
EndDate: input.EndDate,

		}

		items, err := stock_basic.StkRewards(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := StkRewardsOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
