// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_basictools

import (
	"context"
	"encoding/json"
	"fmt"

	stock_basic "tushare-go/pkg/sdk/api/stock_basic"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerStockHsgt registers the tool
func (r *Stock_basicTools) registerStockHsgt() {
	inputSchema, _ := jsonschema.For[StockHsgtInput](nil)

	tool := &mcp.Tool{
		Name:        "stock_basic.stock_hsgt",
		Description: "获取沪深港通股票列表",
		InputSchema: inputSchema,
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input StockHsgtInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &stock_basic.StockHsgtRequest{
TsCode: input.TsCode,
TradeDate: input.TradeDate,
Type: input.Type,
StartDate: input.StartDate,
EndDate: input.EndDate,

		}

		items, err := stock_basic.StockHsgt(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := StockHsgtOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
