// Code generated by tushare-gen. DO NOT EDIT.

package api

import (
	"context"
	"fmt"

	"tushare-go/pkg/sdk"
)

// ComplexTypesExampleRequest 表示 复杂类型示例 API 的请求
type ComplexTypesExampleRequest struct {
	IncludeNested bool `json:"include_nested,omitempty"` // 是否包含嵌套数据
}

// ComplexTypesExampleItem 表示单个 复杂类型示例 数据项
type ComplexTypesExampleItem struct {
	Tags []string `json:"tags"` // 标签数组
	Scores []float64 `json:"scores"` // 分数数组
	Metadata map[string]interface{} `json:"metadata"` // 元数据对象
}

// ComplexTypesExample 调用 复杂类型示例 API
// 这是一个用于测试复杂类型支持的示例API
// 注意：积分要求等使用限制请参考Tushare官方文档
func ComplexTypesExample(ctx context.Context, client *sdk.Client, req *ComplexTypesExampleRequest) ([]ComplexTypesExampleItem, error) {
	params := map[string]interface{}{}
	if req.IncludeNested {
		params["include_nested"] = req.IncludeNested
	}

	fields := []string{"tags", "scores", "metadata"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "complex_types_example", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]ComplexTypesExampleItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 tags 的数组类型
		tagsRaw, ok := item["tags"]
		if !ok {
			return nil, fmt.Errorf("缺少字段 tags")
		}
		var tags []string
		if tagsRaw != nil {
			switch v := tagsRaw.(type) {
			case []interface{}:
				tags = make([]string, len(v))
				for j, val := range v {
					tags[j] = val.(string)
				}
			case []string:
				tags = make([]string, len(v))
				for j, val := range v {
					tags[j] = val
				}
			default:
				tags = []string{}
			}
		}
		// 处理 scores 的数组类型
		scoresRaw, ok := item["scores"]
		if !ok {
			return nil, fmt.Errorf("缺少字段 scores")
		}
		var scores []float64
		if scoresRaw != nil {
			switch v := scoresRaw.(type) {
			case []interface{}:
				scores = make([]float64, len(v))
				for j, val := range v {
					scores[j] = val.(float64)
				}
			case []float64:
				scores = make([]float64, len(v))
				for j, val := range v {
					scores[j] = val
				}
			default:
				scores = []float64{}
			}
		}
		// 处理 metadata 的对象类型
		metadataRaw, ok := item["metadata"]
		if !ok {
			return nil, fmt.Errorf("缺少字段 metadata")
		}
		var metadata map[string]interface{}
		if metadataRaw != nil {
			metadata, ok = metadataRaw.(map[string]interface{})
			if !ok {
				return nil, fmt.Errorf("无效的 metadata 类型")
			}
		}
		items[i] = ComplexTypesExampleItem{
			Tags: tags,
			Scores: scores,
			Metadata: metadata,
		}
	}

	return items, nil
}
