// Code generated by tushare-gen. DO NOT EDIT.

package api

import (
	"context"
	"fmt"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// ConceptRequest 表示 concept API 的请求
type ConceptRequest struct {
	TsCode string `json:"ts_code,omitempty"`
	Name string `json:"name,omitempty"`
}

// ConceptItem 表示单个 concept 数据项
type ConceptItem struct {
	Code string `json:"code"`
	Name string `json:"name"`
	IndexCode string `json:"index_code"`
	InDate string `json:"in_date"`
	OutDate string `json:"out_date"`
}

// Concept 调用 concept API
func Concept(ctx context.Context, client *sdk.Client, req *ConceptRequest) ([]ConceptItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.Name != "" {
		params["name"] = req.Name
	}

	fields := []string{"code", "name", "index_code", "in_date", "out_date"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "concept", params, fields, &result); err != nil {
		return nil, err
	}

	items := make([]ConceptItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 code 的简单类型
		code, ok := item["code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 code 类型")
		}
		// 处理 name 的简单类型
		name, ok := item["name"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 name 类型")
		}
		// 处理 index_code 的简单类型
		indexCode, ok := item["index_code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 index_code 类型")
		}
		// 处理 in_date 的简单类型
		inDate, ok := item["in_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 in_date 类型")
		}
		// 处理 out_date 的简单类型
		outDate, ok := item["out_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 out_date 类型")
		}
		items[i] = ConceptItem{
			Code: code,
			Name: name,
			IndexCode: indexCode,
			InDate: inDate,
			OutDate: outDate,
		}
	}

	return items, nil
}
