// Code generated by tushare-gen. DO NOT EDIT.

package stock_board

import (
	"context"
	"fmt"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// DcHotRequest 表示 东方财富App热榜 API 的请求
type DcHotRequest struct {
	TradeDate string `json:"trade_date,omitempty"`
	TsCode string `json:"ts_code,omitempty"`
	Market string `json:"market,omitempty"`
	HotType string `json:"hot_type,omitempty"`
	IsNew string `json:"is_new,omitempty"`
}

// DcHotItem 表示单个 东方财富App热榜 数据项
type DcHotItem struct {
	TradeDate string `json:"trade_date"`
	DataType string `json:"data_type"`
	TsCode string `json:"ts_code"`
	TsName string `json:"ts_name"`
	Rank int `json:"rank"`
	PctChange float64 `json:"pct_change"`
	CurrentPrice float64 `json:"current_price"`
	RankTime string `json:"rank_time"`
}

// DcHot 调用 东方财富App热榜 API
func DcHot(ctx context.Context, client *sdk.Client, req *DcHotRequest) ([]DcHotItem, error) {
	params := map[string]interface{}{}
	if req.TradeDate != "" {
		params["trade_date"] = req.TradeDate
	}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.Market != "" {
		params["market"] = req.Market
	}
	if req.HotType != "" {
		params["hot_type"] = req.HotType
	}
	if req.IsNew != "" {
		params["is_new"] = req.IsNew
	}

	fields := []string{"trade_date", "data_type", "ts_code", "ts_name", "rank", "pct_change", "current_price", "rank_time"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "dc_hot", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]DcHotItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 trade_date 的简单类型
		tradeDate, ok := item["trade_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 trade_date 类型")
		}
		// 处理 data_type 的简单类型
		dataType, ok := item["data_type"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 data_type 类型")
		}
		// 处理 ts_code 的简单类型
		tsCode, ok := item["ts_code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 ts_name 的简单类型
		tsName, ok := item["ts_name"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ts_name 类型")
		}
		// 处理 rank 的简单类型
		rank, ok := item["rank"].(int)
		if !ok {
			return nil, fmt.Errorf("无效的 rank 类型")
		}
		// 处理 pct_change 的简单类型
		pctChange, ok := item["pct_change"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 pct_change 类型")
		}
		// 处理 current_price 的简单类型
		currentPrice, ok := item["current_price"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 current_price 类型")
		}
		// 处理 rank_time 的简单类型
		rankTime, ok := item["rank_time"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 rank_time 类型")
		}
		items[i] = DcHotItem{
			TradeDate: tradeDate,
			DataType: dataType,
			TsCode: tsCode,
			TsName: tsName,
			Rank: rank,
			PctChange: pctChange,
			CurrentPrice: currentPrice,
			RankTime: rankTime,
		}
	}

	return items, nil
}
