// Code generated by tushare-gen. DO NOT EDIT.

package stock_board

import (
	"context"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// TdxSectorRequest 表示 tdx_sector API 的请求
type TdxSectorRequest struct {
}

// TdxSectorItem 表示单个 tdx_sector 数据项
type TdxSectorItem struct {
}

// TdxSector 调用 tdx_sector API
func TdxSector(ctx context.Context, client *sdk.Client, req *TdxSectorRequest) ([]TdxSectorItem, error) {
	params := map[string]interface{}{}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "tdx_sector", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []TdxSectorItem{}, nil
}
