// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_financialtools

import (
	"context"

	stock_stock_financial "github.com/chenniannian90/tushare-go/pkg/sdk/api/stock/stock_financial"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// callForecast handles Forecast tool calls
func (m *Stock_financialTools) callForecast(ctx context.Context, args map[string]interface{}) (*common.ToolResult, error) {
	req := &stock_stock_financial.ForecastRequest{}

	// Parse arguments into request
	if err := common.ParseInput(args, req); err != nil {
		return common.ErrorResult(err), nil
	}

	items, err := stock_stock_financial.Forecast(ctx, m.client, req)
	if err != nil {
		return common.ErrorResult(err), nil
	}

	// Format results
	result, err := common.APIResult(items, "stock_financial", "forecast")
	if err != nil {
		return common.ErrorResult(err), nil
	}
	return result, nil
}
