// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_financialtools

import (
	"context"
	"fmt"

	stock_stock_financial "github.com/chenniannian90/tushare-go/pkg/sdk/api/stock/stock_financial"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// callIncome handles Income tool calls
func (m *Stock_financialTools) callIncome(ctx context.Context, args map[string]interface{}) (*common.ToolResult, error) {
	req := &stock_stock_financial.IncomeRequest{}

	// Parse arguments into request
	// TODO: Implement proper argument parsing based on request struct fields
	// For now, this is a placeholder implementation

	items, err := stock_stock_financial.Income(ctx, m.client, req)
	if err != nil {
		return nil, fmt.Errorf("failed to call income API: %w", err)
	}

	// Format results
	result, err := common.APIResult(items, "stock_financial", "income")
	if err != nil {
		return nil, err
	}
	return result, nil
}
