// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_financialtools

import (
	"tushare-go/pkg/sdk"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// Stock_financialTools represents stock_financial tools
type Stock_financialTools struct {
	server *mcp.Server
	client *sdk.Client
}

// NewStock_financialTools creates a new instance
func NewStock_financialTools(server *mcp.Server, client *sdk.Client) *Stock_financialTools {
	return &Stock_financialTools{server: server, client: client}
}

// RegisterAll registers all tools
func (r *Stock_financialTools) RegisterAll() {
	r.registerBalancesheet()
	r.registerCashflow()
	r.registerDisclosureDate()
	r.registerDividend()
	r.registerExpress()
	r.registerFinaAudit()
	r.registerFinaIndicator()
	r.registerFinaMainbz()
	r.registerForecast()
	r.registerIncome()

}
