// Code generated by tushare-gen. DO NOT EDIT.

package macro_interest_rate

import (
	"context"
	"encoding/json"
	"fmt"
	"log"

	"tushare-go/pkg/sdk"
)

// ShiborRequest 表示 Shibor利率 API 的请求
type ShiborRequest struct {
	Date string `json:"date,omitempty"` // 日期 (日期输入格式：YYYYMMDD，下同)
	StartDate string `json:"start_date,omitempty"` // 开始日期
	EndDate string `json:"end_date,omitempty"` // 结束日期
}

// ShiborItem 表示单个 Shibor利率 数据项
type ShiborItem struct {
	Date string `json:"date"` // 日期
	On float64 `json:"on"` // 隔夜
	Field1w float64 `json:"1w"` // 1周
	Field2w float64 `json:"2w"` // 2周
	Field1m float64 `json:"1m"` // 1个月
	Field3m float64 `json:"3m"` // 3个月
	Field6m float64 `json:"6m"` // 6个月
	Field9m float64 `json:"9m"` // 9个月
	Field1y float64 `json:"1y"` // 1年
}

// Shibor 调用 Shibor利率 API
// shibor利率
// 注意：积分要求等使用限制请参考Tushare官方文档
func Shibor(ctx context.Context, client *sdk.Client, req *ShiborRequest) ([]ShiborItem, error) {
	params := map[string]interface{}{}
	if req.Date != "" {
		params["date"] = req.Date
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}

	fields := []string{"date", "on", "1w", "2w", "1m", "3m", "6m", "9m", "1y"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPIFlexible(ctx, "shibor", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]ShiborItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 date 的简单类型
		// 对 string 类型尝试多种转换
		var date string
		if v, ok := item["date"].(string); ok {
			date = v
		} else if v, ok := item["date"].(float64); ok {
			date = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["date"].(int); ok {
			date = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["date"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: shibor")
			log.Printf("字段: date")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["date"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 date 类型")
		}
		// 处理 on 的简单类型
		on, ok := item["on"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 on 类型")
		}
		// 处理 1w 的简单类型
		field1w, ok := item["1w"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 1w 类型")
		}
		// 处理 2w 的简单类型
		field2w, ok := item["2w"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 2w 类型")
		}
		// 处理 1m 的简单类型
		field1m, ok := item["1m"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 1m 类型")
		}
		// 处理 3m 的简单类型
		field3m, ok := item["3m"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 3m 类型")
		}
		// 处理 6m 的简单类型
		field6m, ok := item["6m"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 6m 类型")
		}
		// 处理 9m 的简单类型
		field9m, ok := item["9m"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 9m 类型")
		}
		// 处理 1y 的简单类型
		field1y, ok := item["1y"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 1y 类型")
		}
		items[i] = ShiborItem{
			Date: date,
			On: on,
			Field1w: field1w,
			Field2w: field2w,
			Field1m: field1m,
			Field3m: field3m,
			Field6m: field6m,
			Field9m: field9m,
			Field1y: field1y,
		}
	}

	return items, nil
}
