// Code generated by tushare-gen. DO NOT EDIT.

package api

import (
	"context"
	"fmt"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// IndexBasicRequest 表示 index_basic API 的请求
type IndexBasicRequest struct {
	TsCode string `json:"ts_code,omitempty"`
	Name string `json:"name,omitempty"`
	Market string `json:"market,omitempty"`
}

// Validate 验证请求参数
func (r *IndexBasicRequest) Validate() error {
	// 验证 TsCode 格式（如果提供）
	if r.TsCode != "" {
		if len(r.TsCode) != 9 {
			return fmt.Errorf("ts_code 必须为9个字符（例如：000001.SH），当前为%d个字符", len(r.TsCode))
		}
		suffix := r.TsCode[6:]
		if suffix != ".SZ" && suffix != ".SH" {
			return fmt.Errorf("ts_code 必须以.SZ或.SH结尾，当前为%s", suffix)
		}
	}

	// 验证 Market（如果提供）
	if r.Market != "" {
		validMarkets := map[string]bool{
			"SSE":  true, // 上交所
			"SZSE": true, // 深交所
			"CZCE": true, // 郑商所
			"SHFE": true, // 上期所
			"INE":  true, // 能源所
			"BJE":  true, // 北交所
		}
		if !validMarkets[r.Market] {
			return fmt.Errorf("market 必须为 SSE、SZSE、CZCE、SHFE、INE、BJE 之一，当前为%s", r.Market)
		}
	}

	return nil
}

// IndexBasicItem 表示单个 index_basic 数据项
type IndexBasicItem struct {
	TsCode string `json:"ts_code"`
	Name string `json:"name"`
	Market string `json:"market"`
	Publisher string `json:"publisher"`
	IndexType string `json:"index_type"`
	Category string `json:"category"`
}

// IndexBasic 调用 index_basic API
func IndexBasic(ctx context.Context, client *sdk.Client, req *IndexBasicRequest) ([]IndexBasicItem, error) {
	// 验证请求参数
	if err := req.Validate(); err != nil {
		return nil, fmt.Errorf("无效的请求: %w", err)
	}

	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.Name != "" {
		params["name"] = req.Name
	}
	if req.Market != "" {
		params["market"] = req.Market
	}

	fields := []string{"ts_code", "name", "market", "publisher", "index_type", "category"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "index_basic", params, fields, &result); err != nil {
		return nil, err
	}

	items := make([]IndexBasicItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 ts_code 的简单类型
		tsCode, ok := item["ts_code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 name 的简单类型
		name, ok := item["name"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 name 类型")
		}
		// 处理 market 的简单类型
		market, ok := item["market"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 market 类型")
		}
		// 处理 publisher 的简单类型
		publisher, ok := item["publisher"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 publisher 类型")
		}
		// 处理 index_type 的简单类型
		indexType, ok := item["index_type"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 index_type 类型")
		}
		// 处理 category 的简单类型
		category, ok := item["category"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 category 类型")
		}
		items[i] = IndexBasicItem{
			TsCode: tsCode,
			Name: name,
			Market: market,
			Publisher: publisher,
			IndexType: indexType,
			Category: category,
		}
	}

	return items, nil
}
