// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_margintools

import (
	"context"

	stock_stock_margin "github.com/chenniannian90/tushare-go/pkg/sdk/api/stock/stock_margin"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// callSlbSecDetail handles SlbSecDetail tool calls
func (m *Stock_marginTools) callSlbSecDetail(ctx context.Context, args map[string]interface{}) (*common.ToolResult, error) {
	req := &stock_stock_margin.SlbSecDetailRequest{}

	// Parse arguments into request
	if err := common.ParseInput(args, req); err != nil {
		return common.ErrorResult(err), nil
	}

	items, err := stock_stock_margin.SlbSecDetail(ctx, m.client, req)
	if err != nil {
		return common.ErrorResult(err), nil
	}

	// Format results
	result, err := common.APIResult(items, "stock_margin", "slb_sec_detail")
	if err != nil {
		return common.ErrorResult(err), nil
	}
	return result, nil
}
