// Code generated by tushare-gen. DO NOT EDIT.

package index

import (
	"context"
	"fmt"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// IdxMinsRequest 表示 指数历史分钟 API 的请求
type IdxMinsRequest struct {
	TsCode string `json:"ts_code,omitempty"` // 指数代码，e.g. 000001.SH
	Freq string `json:"freq,omitempty"` // 分钟频度（1min/5min/15min/30min/60min）
	StartDate string `json:"start_date,omitempty"` // 开始日期 格式：2023-08-25 09:00:00
	EndDate string `json:"end_date,omitempty"` // 结束时间 格式：2023-08-25 19:00:00
}

// IdxMinsItem 表示单个 指数历史分钟 数据项
type IdxMinsItem struct {
	TsCode string `json:"ts_code"` // 指数代码
	TradeTime string `json:"trade_time"` // 交易时间
	Open float64 `json:"open"` // 开盘价
	Close float64 `json:"close"` // 收盘价
	High float64 `json:"high"` // 最高价
	Low float64 `json:"low"` // 最低价
	Vol int `json:"vol"` // 成交量(股)
	Amount float64 `json:"amount"` // 成交金额（元）
}

// IdxMins 调用 指数历史分钟 API
func IdxMins(ctx context.Context, client *sdk.Client, req *IdxMinsRequest) ([]IdxMinsItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.Freq != "" {
		params["freq"] = req.Freq
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}

	fields := []string{"ts_code", "trade_time", "open", "close", "high", "low", "vol", "amount"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "idx_mins", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]IdxMinsItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 ts_code 的简单类型
		tsCode, ok := item["ts_code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 trade_time 的简单类型
		tradeTime, ok := item["trade_time"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 trade_time 类型")
		}
		// 处理 open 的简单类型
		open, ok := item["open"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 open 类型")
		}
		// 处理 close 的简单类型
		close, ok := item["close"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 close 类型")
		}
		// 处理 high 的简单类型
		high, ok := item["high"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 high 类型")
		}
		// 处理 low 的简单类型
		low, ok := item["low"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 low 类型")
		}
		// 处理 vol 的简单类型
		vol, ok := item["vol"].(int)
		if !ok {
			return nil, fmt.Errorf("无效的 vol 类型")
		}
		// 处理 amount 的简单类型
		amount, ok := item["amount"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 amount 类型")
		}
		items[i] = IdxMinsItem{
			TsCode: tsCode,
			TradeTime: tradeTime,
			Open: open,
			Close: close,
			High: high,
			Low: low,
			Vol: vol,
			Amount: amount,
		}
	}

	return items, nil
}
