// Code generated by tushare-gen. DO NOT EDIT.

package index

import (
	"context"
	"fmt"

	"tushare-go/pkg/sdk"
)

// IndexClassifyRequest 表示 申万行业分类 API 的请求
type IndexClassifyRequest struct {
	IndexCode string `json:"index_code,omitempty"` // 指数代码
	Level string `json:"level,omitempty"` // 行业分级（L1/L2/L3）
	ParentCode string `json:"parent_code,omitempty"` // 父级代码（一级为0）
	Src string `json:"src,omitempty"` // 指数来源（SW2014：申万2014年版本，SW2021：申万2021年版本）
}

// IndexClassifyItem 表示单个 申万行业分类 数据项
type IndexClassifyItem struct {
	IndexCode string `json:"index_code"` // 指数代码
	IndustryName string `json:"industry_name"` // 行业名称
	ParentCode string `json:"parent_code"` // 父级代码
	Level string `json:"level"` // 行业层级
	IndustryCode string `json:"industry_code"` // 行业代码
	IsPub string `json:"is_pub"` // 是否发布了指数
	Src string `json:"src"` // 行业分类（SW申万）
}

// IndexClassify 调用 申万行业分类 API
// 获取申万行业分类，可以获取申万2014年版本（28个一级分类，104个二级分类，227个三级分类）和2021年本版（31个一级分类，134个二级分类，346个三级分类）列表信息
// 注意：积分要求等使用限制请参考Tushare官方文档
func IndexClassify(ctx context.Context, client *sdk.Client, req *IndexClassifyRequest) ([]IndexClassifyItem, error) {
	params := map[string]interface{}{}
	if req.IndexCode != "" {
		params["index_code"] = req.IndexCode
	}
	if req.Level != "" {
		params["level"] = req.Level
	}
	if req.ParentCode != "" {
		params["parent_code"] = req.ParentCode
	}
	if req.Src != "" {
		params["src"] = req.Src
	}

	fields := []string{"index_code", "industry_name", "parent_code", "level", "industry_code", "is_pub", "src"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPIFlexible(ctx, "index_classify", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]IndexClassifyItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 index_code 的简单类型
		// 对 string 类型尝试多种转换
		var indexCode string
		if v, ok := item["index_code"].(string); ok {
			indexCode = v
		} else if v, ok := item["index_code"].(float64); ok {
			indexCode = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["index_code"].(int); ok {
			indexCode = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 index_code 类型")
		}
		// 处理 industry_name 的简单类型
		// 对 string 类型尝试多种转换
		var industryName string
		if v, ok := item["industry_name"].(string); ok {
			industryName = v
		} else if v, ok := item["industry_name"].(float64); ok {
			industryName = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["industry_name"].(int); ok {
			industryName = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 industry_name 类型")
		}
		// 处理 parent_code 的简单类型
		// 对 string 类型尝试多种转换
		var parentCode string
		if v, ok := item["parent_code"].(string); ok {
			parentCode = v
		} else if v, ok := item["parent_code"].(float64); ok {
			parentCode = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["parent_code"].(int); ok {
			parentCode = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 parent_code 类型")
		}
		// 处理 level 的简单类型
		// 对 string 类型尝试多种转换
		var level string
		if v, ok := item["level"].(string); ok {
			level = v
		} else if v, ok := item["level"].(float64); ok {
			level = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["level"].(int); ok {
			level = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 level 类型")
		}
		// 处理 industry_code 的简单类型
		// 对 string 类型尝试多种转换
		var industryCode string
		if v, ok := item["industry_code"].(string); ok {
			industryCode = v
		} else if v, ok := item["industry_code"].(float64); ok {
			industryCode = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["industry_code"].(int); ok {
			industryCode = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 industry_code 类型")
		}
		// 处理 is_pub 的简单类型
		// 对 string 类型尝试多种转换
		var isPub string
		if v, ok := item["is_pub"].(string); ok {
			isPub = v
		} else if v, ok := item["is_pub"].(float64); ok {
			isPub = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["is_pub"].(int); ok {
			isPub = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 is_pub 类型")
		}
		// 处理 src 的简单类型
		// 对 string 类型尝试多种转换
		var src string
		if v, ok := item["src"].(string); ok {
			src = v
		} else if v, ok := item["src"].(float64); ok {
			src = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["src"].(int); ok {
			src = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 src 类型")
		}
		items[i] = IndexClassifyItem{
			IndexCode: indexCode,
			IndustryName: industryName,
			ParentCode: parentCode,
			Level: level,
			IndustryCode: industryCode,
			IsPub: isPub,
			Src: src,
		}
	}

	return items, nil
}
