// Code generated by tushare-gen. DO NOT EDIT.

package index

import (
	"context"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// IndexMinRequest 表示 index_min API 的请求
type IndexMinRequest struct {
}

// IndexMinItem 表示单个 index_min 数据项
type IndexMinItem struct {
}

// IndexMin 调用 index_min API
func IndexMin(ctx context.Context, client *sdk.Client, req *IndexMinRequest) ([]IndexMinItem, error) {
	params := map[string]interface{}{}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "index_min", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []IndexMinItem{}, nil
}
