// Code generated by tushare-gen. DO NOT EDIT.

package index

import (
	"context"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// IndexWeightRequest 表示 指数成分和权重 API 的请求
type IndexWeightRequest struct {
	IndexCode string `json:"index_code,omitempty"` // 指数代码，来源指数基础信息接口
	TradeDate string `json:"trade_date,omitempty"` // 交易日期（格式YYYYMMDD，下同）
	StartDate string `json:"start_date,omitempty"` // 开始日期
	EndDate string `json:"end_date,omitempty"` // 结束日期
}

// IndexWeightItem 表示单个 指数成分和权重 数据项
type IndexWeightItem struct {
}

// IndexWeight 调用 指数成分和权重 API
func IndexWeight(ctx context.Context, client *sdk.Client, req *IndexWeightRequest) ([]IndexWeightItem, error) {
	params := map[string]interface{}{}
	if req.IndexCode != "" {
		params["index_code"] = req.IndexCode
	}
	if req.TradeDate != "" {
		params["trade_date"] = req.TradeDate
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "index_weight", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []IndexWeightItem{}, nil
}
