// Code generated by tushare-gen. DO NOT EDIT.

package index

import (
	"context"
	"fmt"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// RtSwKRequest 表示 申万实时行情 API 的请求
type RtSwKRequest struct {
	TsCode string `json:"ts_code,omitempty"`
}

// RtSwKItem 表示单个 申万实时行情 数据项
type RtSwKItem struct {
	TsCode string `json:"ts_code"`
	Name string `json:"name"`
	TradeTime string `json:"trade_time"`
	Close float64 `json:"close"`
	PreClose float64 `json:"pre_close"`
	High float64 `json:"high"`
	Open float64 `json:"open"`
	Low float64 `json:"low"`
	Vol float64 `json:"vol"`
	Amount float64 `json:"amount"`
	PctChange float64 `json:"pct_change"`
}

// RtSwK 调用 申万实时行情 API
func RtSwK(ctx context.Context, client *sdk.Client, req *RtSwKRequest) ([]RtSwKItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}

	fields := []string{"ts_code", "name", "trade_time", "close", "pre_close", "high", "open", "low", "vol", "amount", "pct_change"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "rt_sw_k", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]RtSwKItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 ts_code 的简单类型
		tsCode, ok := item["ts_code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 name 的简单类型
		name, ok := item["name"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 name 类型")
		}
		// 处理 trade_time 的简单类型
		tradeTime, ok := item["trade_time"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 trade_time 类型")
		}
		// 处理 close 的简单类型
		close, ok := item["close"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 close 类型")
		}
		// 处理 pre_close 的简单类型
		preClose, ok := item["pre_close"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 pre_close 类型")
		}
		// 处理 high 的简单类型
		high, ok := item["high"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 high 类型")
		}
		// 处理 open 的简单类型
		open, ok := item["open"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 open 类型")
		}
		// 处理 low 的简单类型
		low, ok := item["low"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 low 类型")
		}
		// 处理 vol 的简单类型
		vol, ok := item["vol"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 vol 类型")
		}
		// 处理 amount 的简单类型
		amount, ok := item["amount"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 amount 类型")
		}
		// 处理 pct_change 的简单类型
		pctChange, ok := item["pct_change"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 pct_change 类型")
		}
		items[i] = RtSwKItem{
			TsCode: tsCode,
			Name: name,
			TradeTime: tradeTime,
			Close: close,
			PreClose: preClose,
			High: high,
			Open: open,
			Low: low,
			Vol: vol,
			Amount: amount,
			PctChange: pctChange,
		}
	}

	return items, nil
}
