// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_referencetools

import (
	"context"
	"encoding/json"
	"fmt"

	stock_reference "tushare-go/pkg/sdk/api/stock_reference"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerBlockTrade registers the tool
func (r *Stock_referenceTools) registerBlockTrade() {
	inputSchema, _ := jsonschema.For[BlockTradeInput](nil)
	schemaJSON, _ := json.Marshal(inputSchema)

	tool := &mcp.Tool{
		Name:        "stock_reference.block_trade",
		Description: "查询A股大宗交易数据，包含交易价格、成交量、买卖方营业部等信息。参数说明：ts_code和trade_date至少填写一个。日期格式必须为YYYYMMDD（如：20240301）。返回字段：股票代码、交易日期、成交价格、成交量、成交金额、买方营业部、卖方营业部",
		InputSchema: json.RawMessage(schemaJSON),
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input BlockTradeInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &stock_reference.BlockTradeRequest{
TsCode: input.TsCode,
TradeDate: input.TradeDate,
StartDate: input.StartDate,
EndDate: input.EndDate,

		}

		items, err := stock_reference.BlockTrade(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := BlockTradeOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
