// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_referencetools

import (
	"context"
	"encoding/json"
	"fmt"

	stock_reference "tushare-go/pkg/sdk/api/stock_reference"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerStkHoldernumber registers the tool
func (r *Stock_referenceTools) registerStkHoldernumber() {
	inputSchema, _ := jsonschema.For[StkHoldernumberInput](nil)
	schemaJSON, _ := json.Marshal(inputSchema)

	tool := &mcp.Tool{
		Name:        "stock_reference.stk_holdernumber",
		Description: "获取上市公司股东户数数据。注意事项：数据不定期公布，通常在季度报告中披露。返回字段：股票代码、公告日期、截止日期、股东户数",
		InputSchema: json.RawMessage(schemaJSON),
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input StkHoldernumberInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &stock_reference.StkHoldernumberRequest{
TsCode: input.TsCode,
AnnDate: input.AnnDate,
Enddate: input.Enddate,
StartDate: input.StartDate,
EndDate: input.EndDate,

		}

		items, err := stock_reference.StkHoldernumber(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := StkHoldernumberOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
