// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_referencetools

import (
	"context"
	"fmt"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// Stock_referenceTools implements tools for stock_reference API
type Stock_referenceTools struct {
	client *sdk.Client
}

// NewStock_referenceTools creates a new stock_reference tools instance
func NewStock_referenceTools(client *sdk.Client) *Stock_referenceTools {
	return &Stock_referenceTools{
		client: client,
	}
}

// GetAPIName returns the Tushare API name for this module
func (m *Stock_referenceTools) GetAPIName() string {
	return "stock_reference"
}

// ListTools returns all available tools in this module
func (m *Stock_referenceTools) ListTools() []common.Tool {
	return []common.Tool{
		{
			Name: "stock_reference.api164",
			Description: "Access api164 data from Tushare API",
		},
		{
			Name: "stock_reference.api165",
			Description: "Access api165 data from Tushare API",
		},
		{
			Name: "stock_reference.block_trade",
			Description: "Access block_trade data from Tushare API",
		},
		{
			Name: "stock_reference.pledge_detail",
			Description: "Access pledge_detail data from Tushare API",
		},
		{
			Name: "stock_reference.pledge_stat",
			Description: "Access pledge_stat data from Tushare API",
		},
		{
			Name: "stock_reference.repurchase",
			Description: "Access repurchase data from Tushare API",
		},
		{
			Name: "stock_reference.stk_change",
			Description: "Access stk_change data from Tushare API",
		},
		{
			Name: "stock_reference.stk_holdernumber",
			Description: "Access stk_holdernumber data from Tushare API",
		},
		{
			Name: "stock_reference.top10_floatholders",
			Description: "Access top10_floatholders data from Tushare API",
		},
		{
			Name: "stock_reference.top10_holders",
			Description: "Access top10_holders data from Tushare API",
		},
		{
			Name: "stock_reference.unlock_share",
			Description: "Access unlock_share data from Tushare API",
		},
	}
}

// HandlesTool checks if this module handles a tool
func (m *Stock_referenceTools) HandlesTool(toolName string) bool {
	tools := m.ListTools()
	for _, tool := range tools {
		if tool.Name == toolName {
			return true
		}
	}
	return false
}

// CallTool executes a tool call
func (m *Stock_referenceTools) CallTool(ctx context.Context, toolName string, args map[string]interface{}) (*common.ToolResult, error) {
	switch toolName {
	case "stock_reference.api164":
		return m.callApi164(ctx, args)
	case "stock_reference.api165":
		return m.callApi165(ctx, args)
	case "stock_reference.block_trade":
		return m.callBlockTrade(ctx, args)
	case "stock_reference.pledge_detail":
		return m.callPledgeDetail(ctx, args)
	case "stock_reference.pledge_stat":
		return m.callPledgeStat(ctx, args)
	case "stock_reference.repurchase":
		return m.callRepurchase(ctx, args)
	case "stock_reference.stk_change":
		return m.callStkChange(ctx, args)
	case "stock_reference.stk_holdernumber":
		return m.callStkHoldernumber(ctx, args)
	case "stock_reference.top10_floatholders":
		return m.callTop10Floatholders(ctx, args)
	case "stock_reference.top10_holders":
		return m.callTop10Holders(ctx, args)
	case "stock_reference.unlock_share":
		return m.callUnlockShare(ctx, args)
	default:
		return nil, fmt.Errorf("unknown tool: %s", toolName)
	}
}
