// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_referencetools

import (
	"context"
	"fmt"

	stock_stock_reference "github.com/chenniannian90/tushare-go/pkg/sdk/api/stock/stock_reference"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// callTop10Floatholders handles Top10Floatholders tool calls
func (m *Stock_referenceTools) callTop10Floatholders(ctx context.Context, args map[string]interface{}) (*common.ToolResult, error) {
	req := &stock_stock_reference.Top10FloatholdersRequest{}

	// Parse arguments into request
	// TODO: Implement proper argument parsing based on request struct fields
	// For now, this is a placeholder implementation

	items, err := stock_stock_reference.Top10Floatholders(ctx, m.client, req)
	if err != nil {
		return nil, fmt.Errorf("failed to call top10_floatholders API: %w", err)
	}

	// Format results
	result, err := common.APIResult(items, "stock_reference", "top10_floatholders")
	if err != nil {
		return nil, err
	}
	return result, nil
}
