// Code generated by tushare-gen. DO NOT EDIT.

package stock_reference

import (
	"context"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// Api164Request 表示 api_164 API 的请求
type Api164Request struct {
}

// Api164Item 表示单个 api_164 数据项
type Api164Item struct {
}

// Api164 调用 api_164 API
func Api164(ctx context.Context, client *sdk.Client, req *Api164Request) ([]Api164Item, error) {
	params := map[string]interface{}{}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "api_164", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []Api164Item{}, nil
}
