// Code generated by tushare-gen. DO NOT EDIT.

package stock_reference

import (
	"context"
	"fmt"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// StkAccountRequest 表示 股票开户数据（停） API 的请求
type StkAccountRequest struct {
	Date string `json:"date,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
}

// StkAccountItem 表示单个 股票开户数据（停） 数据项
type StkAccountItem struct {
	Date string `json:"date"`
	WeeklyNew float64 `json:"weekly_new"`
	Total float64 `json:"total"`
	WeeklyHold float64 `json:"weekly_hold"`
	WeeklyTrade float64 `json:"weekly_trade"`
}

// StkAccount 调用 股票开户数据（停） API
func StkAccount(ctx context.Context, client *sdk.Client, req *StkAccountRequest) ([]StkAccountItem, error) {
	params := map[string]interface{}{}
	if req.Date != "" {
		params["date"] = req.Date
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}

	fields := []string{"date", "weekly_new", "total", "weekly_hold", "weekly_trade"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "stk_account", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]StkAccountItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 date 的简单类型
		date, ok := item["date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 date 类型")
		}
		// 处理 weekly_new 的简单类型
		weeklyNew, ok := item["weekly_new"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 weekly_new 类型")
		}
		// 处理 total 的简单类型
		total, ok := item["total"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 total 类型")
		}
		// 处理 weekly_hold 的简单类型
		weeklyHold, ok := item["weekly_hold"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 weekly_hold 类型")
		}
		// 处理 weekly_trade 的简单类型
		weeklyTrade, ok := item["weekly_trade"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 weekly_trade 类型")
		}
		items[i] = StkAccountItem{
			Date: date,
			WeeklyNew: weeklyNew,
			Total: total,
			WeeklyHold: weeklyHold,
			WeeklyTrade: weeklyTrade,
		}
	}

	return items, nil
}
