// Code generated by tushare-gen. DO NOT EDIT.

package stock_reference

import (
	"context"
	"fmt"

	"tushare-go/pkg/sdk"
)

// StkHoldertradeRequest 表示 股东增减持 API 的请求
type StkHoldertradeRequest struct {
	TsCode string `json:"ts_code,omitempty"` // TS股票代码
	AnnDate string `json:"ann_date,omitempty"` // 公告日期
	StartDate string `json:"start_date,omitempty"` // 公告开始日期
	EndDate string `json:"end_date,omitempty"` // 公告结束日期
	TradeType string `json:"trade_type,omitempty"` // 交易类型IN增持DE减持
	HolderType string `json:"holder_type,omitempty"` // 股东类型C公司P个人G高管
}

// StkHoldertradeItem 表示单个 股东增减持 数据项
type StkHoldertradeItem struct {
	TsCode string `json:"ts_code"` // TS代码
	AnnDate string `json:"ann_date"` // 公告日期
	HolderName string `json:"holder_name"` // 股东名称
	HolderType string `json:"holder_type"` // 股东类型G高管P个人C公司
	InDe string `json:"in_de"` // 类型IN增持DE减持
	ChangeVol float64 `json:"change_vol"` // 变动数量
	ChangeRatio float64 `json:"change_ratio"` // 占流通比例（%）
	AfterShare float64 `json:"after_share"` // 变动后持股
	AfterRatio float64 `json:"after_ratio"` // 变动后占流通比例（%）
	AvgPrice float64 `json:"avg_price"` // 平均价格
	TotalShare float64 `json:"total_share"` // 持股总数
	BeginDate string `json:"begin_date"` // 增减持开始日期
	CloseDate string `json:"close_date"` // 增减持结束日期
}

// StkHoldertrade 调用 股东增减持 API
func StkHoldertrade(ctx context.Context, client *sdk.Client, req *StkHoldertradeRequest) ([]StkHoldertradeItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.AnnDate != "" {
		params["ann_date"] = req.AnnDate
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}
	if req.TradeType != "" {
		params["trade_type"] = req.TradeType
	}
	if req.HolderType != "" {
		params["holder_type"] = req.HolderType
	}

	fields := []string{"ts_code", "ann_date", "holder_name", "holder_type", "in_de", "change_vol", "change_ratio", "after_share", "after_ratio", "avg_price", "total_share", "begin_date", "close_date"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "stk_holdertrade", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]StkHoldertradeItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 ts_code 的简单类型
		tsCode, ok := item["ts_code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 ann_date 的简单类型
		annDate, ok := item["ann_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ann_date 类型")
		}
		// 处理 holder_name 的简单类型
		holderName, ok := item["holder_name"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 holder_name 类型")
		}
		// 处理 holder_type 的简单类型
		holderType, ok := item["holder_type"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 holder_type 类型")
		}
		// 处理 in_de 的简单类型
		inDe, ok := item["in_de"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 in_de 类型")
		}
		// 处理 change_vol 的简单类型
		changeVol, ok := item["change_vol"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 change_vol 类型")
		}
		// 处理 change_ratio 的简单类型
		changeRatio, ok := item["change_ratio"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 change_ratio 类型")
		}
		// 处理 after_share 的简单类型
		afterShare, ok := item["after_share"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 after_share 类型")
		}
		// 处理 after_ratio 的简单类型
		afterRatio, ok := item["after_ratio"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 after_ratio 类型")
		}
		// 处理 avg_price 的简单类型
		avgPrice, ok := item["avg_price"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 avg_price 类型")
		}
		// 处理 total_share 的简单类型
		totalShare, ok := item["total_share"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 total_share 类型")
		}
		// 处理 begin_date 的简单类型
		beginDate, ok := item["begin_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 begin_date 类型")
		}
		// 处理 close_date 的简单类型
		closeDate, ok := item["close_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 close_date 类型")
		}
		items[i] = StkHoldertradeItem{
			TsCode: tsCode,
			AnnDate: annDate,
			HolderName: holderName,
			HolderType: holderType,
			InDe: inDe,
			ChangeVol: changeVol,
			ChangeRatio: changeRatio,
			AfterShare: afterShare,
			AfterRatio: afterRatio,
			AvgPrice: avgPrice,
			TotalShare: totalShare,
			BeginDate: beginDate,
			CloseDate: closeDate,
		}
	}

	return items, nil
}
