// Code generated by tushare-gen. DO NOT EDIT.

package stock_reference

import (
	"context"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// Top10FloatholdersRequest 表示 top10_floatholders API 的请求
type Top10FloatholdersRequest struct {
}

// Top10FloatholdersItem 表示单个 top10_floatholders 数据项
type Top10FloatholdersItem struct {
}

// Top10Floatholders 调用 top10_floatholders API
func Top10Floatholders(ctx context.Context, client *sdk.Client, req *Top10FloatholdersRequest) ([]Top10FloatholdersItem, error) {
	params := map[string]interface{}{}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "top10_floatholders", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []Top10FloatholdersItem{}, nil
}
