// Code generated by tushare-gen. DO NOT EDIT.

package etf

import (
	"context"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// Api386Request 表示 api_386 API 的请求
type Api386Request struct {
}

// Api386Item 表示单个 api_386 数据项
type Api386Item struct {
}

// Api386 调用 api_386 API
func Api386(ctx context.Context, client *sdk.Client, req *Api386Request) ([]Api386Item, error) {
	params := map[string]interface{}{}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "api_386", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []Api386Item{}, nil
}
