// Code generated by tushare-gen. DO NOT EDIT.

package apis

import (
	"context"
	"github.com/chenniannian90/tushare-go/pkg/sdk"
	"github.com/chenniannian90/tushare-go/pkg/sdk/api/etf"
)

type Etf interface {
	EtfBasic(ctx context.Context, req *etf.EtfBasicRequest) ([]etf.EtfBasicItem, error)
	EtfIndex(ctx context.Context, req *etf.EtfIndexRequest) ([]etf.EtfIndexItem, error)
	EtfShareSize(ctx context.Context, req *etf.EtfShareSizeRequest) ([]etf.EtfShareSizeItem, error)
	FundAdj(ctx context.Context, req *etf.FundAdjRequest) ([]etf.FundAdjItem, error)
	FundDaily(ctx context.Context, req *etf.FundDailyRequest) ([]etf.FundDailyItem, error)
	RtEtfK(ctx context.Context, req *etf.RtEtfKRequest) ([]etf.RtEtfKItem, error)
	RtMin(ctx context.Context, req *etf.RtMinRequest) ([]etf.RtMinItem, error)
	StkMins(ctx context.Context, req *etf.StkMinsRequest) ([]etf.StkMinsItem, error)
}

type etfImpl struct {
	client *sdk.Client
}

func (impl *etfImpl) EtfBasic(ctx context.Context, req *etf.EtfBasicRequest) ([]etf.EtfBasicItem, error) {
	return etf.EtfBasic(ctx, impl.client, req)
}

func (impl *etfImpl) EtfIndex(ctx context.Context, req *etf.EtfIndexRequest) ([]etf.EtfIndexItem, error) {
	return etf.EtfIndex(ctx, impl.client, req)
}

func (impl *etfImpl) EtfShareSize(ctx context.Context, req *etf.EtfShareSizeRequest) ([]etf.EtfShareSizeItem, error) {
	return etf.EtfShareSize(ctx, impl.client, req)
}

func (impl *etfImpl) FundAdj(ctx context.Context, req *etf.FundAdjRequest) ([]etf.FundAdjItem, error) {
	return etf.FundAdj(ctx, impl.client, req)
}

func (impl *etfImpl) FundDaily(ctx context.Context, req *etf.FundDailyRequest) ([]etf.FundDailyItem, error) {
	return etf.FundDaily(ctx, impl.client, req)
}

func (impl *etfImpl) RtEtfK(ctx context.Context, req *etf.RtEtfKRequest) ([]etf.RtEtfKItem, error) {
	return etf.RtEtfK(ctx, impl.client, req)
}

func (impl *etfImpl) RtMin(ctx context.Context, req *etf.RtMinRequest) ([]etf.RtMinItem, error) {
	return etf.RtMin(ctx, impl.client, req)
}

func (impl *etfImpl) StkMins(ctx context.Context, req *etf.StkMinsRequest) ([]etf.StkMinsItem, error) {
	return etf.StkMins(ctx, impl.client, req)
}

func newetfImpl(client *sdk.Client) Etf {
	return &etfImpl{client: client}
}
