// Code generated by tushare-gen. DO NOT EDIT.

package apis

import (
	"context"
	"github.com/chenniannian90/tushare-go/pkg/sdk"
	"github.com/chenniannian90/tushare-go/pkg/sdk/api/llm_corpus"
)

type LlmCorpus interface {
	AnnsD(ctx context.Context, req *llm_corpus.AnnsDRequest) ([]llm_corpus.AnnsDItem, error)
	CctvNews(ctx context.Context, req *llm_corpus.CctvNewsRequest) ([]llm_corpus.CctvNewsItem, error)
	IrmQaSh(ctx context.Context, req *llm_corpus.IrmQaShRequest) ([]llm_corpus.IrmQaShItem, error)
	IrmQaSz(ctx context.Context, req *llm_corpus.IrmQaSzRequest) ([]llm_corpus.IrmQaSzItem, error)
	MajorNews(ctx context.Context, req *llm_corpus.MajorNewsRequest) ([]llm_corpus.MajorNewsItem, error)
	News(ctx context.Context, req *llm_corpus.NewsRequest) ([]llm_corpus.NewsItem, error)
	Npr(ctx context.Context, req *llm_corpus.NprRequest) ([]llm_corpus.NprItem, error)
	ResearchReport(ctx context.Context, req *llm_corpus.ResearchReportRequest) ([]llm_corpus.ResearchReportItem, error)
}

type llmCorpusImpl struct {
	client *sdk.Client
}

func (impl *llmCorpusImpl) AnnsD(ctx context.Context, req *llm_corpus.AnnsDRequest) ([]llm_corpus.AnnsDItem, error) {
	return llm_corpus.AnnsD(ctx, impl.client, req)
}

func (impl *llmCorpusImpl) CctvNews(ctx context.Context, req *llm_corpus.CctvNewsRequest) ([]llm_corpus.CctvNewsItem, error) {
	return llm_corpus.CctvNews(ctx, impl.client, req)
}

func (impl *llmCorpusImpl) IrmQaSh(ctx context.Context, req *llm_corpus.IrmQaShRequest) ([]llm_corpus.IrmQaShItem, error) {
	return llm_corpus.IrmQaSh(ctx, impl.client, req)
}

func (impl *llmCorpusImpl) IrmQaSz(ctx context.Context, req *llm_corpus.IrmQaSzRequest) ([]llm_corpus.IrmQaSzItem, error) {
	return llm_corpus.IrmQaSz(ctx, impl.client, req)
}

func (impl *llmCorpusImpl) MajorNews(ctx context.Context, req *llm_corpus.MajorNewsRequest) ([]llm_corpus.MajorNewsItem, error) {
	return llm_corpus.MajorNews(ctx, impl.client, req)
}

func (impl *llmCorpusImpl) News(ctx context.Context, req *llm_corpus.NewsRequest) ([]llm_corpus.NewsItem, error) {
	return llm_corpus.News(ctx, impl.client, req)
}

func (impl *llmCorpusImpl) Npr(ctx context.Context, req *llm_corpus.NprRequest) ([]llm_corpus.NprItem, error) {
	return llm_corpus.Npr(ctx, impl.client, req)
}

func (impl *llmCorpusImpl) ResearchReport(ctx context.Context, req *llm_corpus.ResearchReportRequest) ([]llm_corpus.ResearchReportItem, error) {
	return llm_corpus.ResearchReport(ctx, impl.client, req)
}

func newllmCorpusImpl(client *sdk.Client) LlmCorpus {
	return &llmCorpusImpl{client: client}
}
