// Code generated by tushare-gen. DO NOT EDIT.

package apis

import (
	"context"
	"github.com/chenniannian90/tushare-go/pkg/sdk"
	"github.com/chenniannian90/tushare-go/pkg/sdk/api/stock_market"
)

type StockMarket interface {
	AdjFactor(ctx context.Context, req *stock_market.AdjFactorRequest) ([]stock_market.AdjFactorItem, error)
	Api109(ctx context.Context, req *stock_market.Api109Request) ([]stock_market.Api109Item, error)
	Api146(ctx context.Context, req *stock_market.Api146Request) ([]stock_market.Api146Item, error)
	BakDaily(ctx context.Context, req *stock_market.BakDailyRequest) ([]stock_market.BakDailyItem, error)
	Daily(ctx context.Context, req *stock_market.DailyRequest) ([]stock_market.DailyItem, error)
	DailyBasic(ctx context.Context, req *stock_market.DailyBasicRequest) ([]stock_market.DailyBasicItem, error)
	GgtDaily(ctx context.Context, req *stock_market.GgtDailyRequest) ([]stock_market.GgtDailyItem, error)
	GgtMonthly(ctx context.Context, req *stock_market.GgtMonthlyRequest) ([]stock_market.GgtMonthlyItem, error)
	GgtTop10(ctx context.Context, req *stock_market.GgtTop10Request) ([]stock_market.GgtTop10Item, error)
	HsgtTop10(ctx context.Context, req *stock_market.HsgtTop10Request) ([]stock_market.HsgtTop10Item, error)
	Monthly(ctx context.Context, req *stock_market.MonthlyRequest) ([]stock_market.MonthlyItem, error)
	RealtimeList(ctx context.Context, req *stock_market.RealtimeListRequest) ([]stock_market.RealtimeListItem, error)
	RealtimeQuote(ctx context.Context, req *stock_market.RealtimeQuoteRequest) ([]stock_market.RealtimeQuoteItem, error)
	RealtimeTick(ctx context.Context, req *stock_market.RealtimeTickRequest) ([]stock_market.RealtimeTickItem, error)
	RtK(ctx context.Context, req *stock_market.RtKRequest) ([]stock_market.RtKItem, error)
	RtMin(ctx context.Context, req *stock_market.RtMinRequest) ([]stock_market.RtMinItem, error)
	StkLimit(ctx context.Context, req *stock_market.StkLimitRequest) ([]stock_market.StkLimitItem, error)
	StkMins(ctx context.Context, req *stock_market.StkMinsRequest) ([]stock_market.StkMinsItem, error)
	StkWeekMonthAdj(ctx context.Context, req *stock_market.StkWeekMonthAdjRequest) ([]stock_market.StkWeekMonthAdjItem, error)
	StkWeeklyMonthly(ctx context.Context, req *stock_market.StkWeeklyMonthlyRequest) ([]stock_market.StkWeeklyMonthlyItem, error)
	SuspendD(ctx context.Context, req *stock_market.SuspendDRequest) ([]stock_market.SuspendDItem, error)
	Weekly(ctx context.Context, req *stock_market.WeeklyRequest) ([]stock_market.WeeklyItem, error)
}

type stockMarketImpl struct {
	client *sdk.Client
}

func (impl *stockMarketImpl) AdjFactor(ctx context.Context, req *stock_market.AdjFactorRequest) ([]stock_market.AdjFactorItem, error) {
	return stock_market.AdjFactor(ctx, impl.client, req)
}

func (impl *stockMarketImpl) Api109(ctx context.Context, req *stock_market.Api109Request) ([]stock_market.Api109Item, error) {
	return stock_market.Api109(ctx, impl.client, req)
}

func (impl *stockMarketImpl) Api146(ctx context.Context, req *stock_market.Api146Request) ([]stock_market.Api146Item, error) {
	return stock_market.Api146(ctx, impl.client, req)
}

func (impl *stockMarketImpl) BakDaily(ctx context.Context, req *stock_market.BakDailyRequest) ([]stock_market.BakDailyItem, error) {
	return stock_market.BakDaily(ctx, impl.client, req)
}

func (impl *stockMarketImpl) Daily(ctx context.Context, req *stock_market.DailyRequest) ([]stock_market.DailyItem, error) {
	return stock_market.Daily(ctx, impl.client, req)
}

func (impl *stockMarketImpl) DailyBasic(ctx context.Context, req *stock_market.DailyBasicRequest) ([]stock_market.DailyBasicItem, error) {
	return stock_market.DailyBasic(ctx, impl.client, req)
}

func (impl *stockMarketImpl) GgtDaily(ctx context.Context, req *stock_market.GgtDailyRequest) ([]stock_market.GgtDailyItem, error) {
	return stock_market.GgtDaily(ctx, impl.client, req)
}

func (impl *stockMarketImpl) GgtMonthly(ctx context.Context, req *stock_market.GgtMonthlyRequest) ([]stock_market.GgtMonthlyItem, error) {
	return stock_market.GgtMonthly(ctx, impl.client, req)
}

func (impl *stockMarketImpl) GgtTop10(ctx context.Context, req *stock_market.GgtTop10Request) ([]stock_market.GgtTop10Item, error) {
	return stock_market.GgtTop10(ctx, impl.client, req)
}

func (impl *stockMarketImpl) HsgtTop10(ctx context.Context, req *stock_market.HsgtTop10Request) ([]stock_market.HsgtTop10Item, error) {
	return stock_market.HsgtTop10(ctx, impl.client, req)
}

func (impl *stockMarketImpl) Monthly(ctx context.Context, req *stock_market.MonthlyRequest) ([]stock_market.MonthlyItem, error) {
	return stock_market.Monthly(ctx, impl.client, req)
}

func (impl *stockMarketImpl) RealtimeList(ctx context.Context, req *stock_market.RealtimeListRequest) ([]stock_market.RealtimeListItem, error) {
	return stock_market.RealtimeList(ctx, impl.client, req)
}

func (impl *stockMarketImpl) RealtimeQuote(ctx context.Context, req *stock_market.RealtimeQuoteRequest) ([]stock_market.RealtimeQuoteItem, error) {
	return stock_market.RealtimeQuote(ctx, impl.client, req)
}

func (impl *stockMarketImpl) RealtimeTick(ctx context.Context, req *stock_market.RealtimeTickRequest) ([]stock_market.RealtimeTickItem, error) {
	return stock_market.RealtimeTick(ctx, impl.client, req)
}

func (impl *stockMarketImpl) RtK(ctx context.Context, req *stock_market.RtKRequest) ([]stock_market.RtKItem, error) {
	return stock_market.RtK(ctx, impl.client, req)
}

func (impl *stockMarketImpl) RtMin(ctx context.Context, req *stock_market.RtMinRequest) ([]stock_market.RtMinItem, error) {
	return stock_market.RtMin(ctx, impl.client, req)
}

func (impl *stockMarketImpl) StkLimit(ctx context.Context, req *stock_market.StkLimitRequest) ([]stock_market.StkLimitItem, error) {
	return stock_market.StkLimit(ctx, impl.client, req)
}

func (impl *stockMarketImpl) StkMins(ctx context.Context, req *stock_market.StkMinsRequest) ([]stock_market.StkMinsItem, error) {
	return stock_market.StkMins(ctx, impl.client, req)
}

func (impl *stockMarketImpl) StkWeekMonthAdj(ctx context.Context, req *stock_market.StkWeekMonthAdjRequest) ([]stock_market.StkWeekMonthAdjItem, error) {
	return stock_market.StkWeekMonthAdj(ctx, impl.client, req)
}

func (impl *stockMarketImpl) StkWeeklyMonthly(ctx context.Context, req *stock_market.StkWeeklyMonthlyRequest) ([]stock_market.StkWeeklyMonthlyItem, error) {
	return stock_market.StkWeeklyMonthly(ctx, impl.client, req)
}

func (impl *stockMarketImpl) SuspendD(ctx context.Context, req *stock_market.SuspendDRequest) ([]stock_market.SuspendDItem, error) {
	return stock_market.SuspendD(ctx, impl.client, req)
}

func (impl *stockMarketImpl) Weekly(ctx context.Context, req *stock_market.WeeklyRequest) ([]stock_market.WeeklyItem, error) {
	return stock_market.Weekly(ctx, impl.client, req)
}

func newstockMarketImpl(client *sdk.Client) StockMarket {
	return &stockMarketImpl{client: client}
}
