// Code generated by tushare-gen. DO NOT EDIT.

package apis

import (
	"context"
	"tushare-go/pkg/sdk"
	us_stock "tushare-go/pkg/sdk/api/us_stock"
)

type UsStock interface {
	// UsAdjfactor 调用 美股复权因子 API
	UsAdjfactor(ctx context.Context, req *us_stock.UsAdjfactorRequest) ([]us_stock.UsAdjfactorItem, error)
	// UsBalancesheet 调用 美股资产负债表 API
	UsBalancesheet(ctx context.Context, req *us_stock.UsBalancesheetRequest) ([]us_stock.UsBalancesheetItem, error)
	// UsBasic 调用 美股基础信息 API
	UsBasic(ctx context.Context, req *us_stock.UsBasicRequest) ([]us_stock.UsBasicItem, error)
	// UsCashflow 调用 美股现金流量表 API
	UsCashflow(ctx context.Context, req *us_stock.UsCashflowRequest) ([]us_stock.UsCashflowItem, error)
	// UsDaily 调用 美股日线行情 API
	UsDaily(ctx context.Context, req *us_stock.UsDailyRequest) ([]us_stock.UsDailyItem, error)
	// UsDailyAdj 调用 美股复权行情 API
	UsDailyAdj(ctx context.Context, req *us_stock.UsDailyAdjRequest) ([]us_stock.UsDailyAdjItem, error)
	// UsFinaIndicator 调用 美股财务指标数据 API
	UsFinaIndicator(ctx context.Context, req *us_stock.UsFinaIndicatorRequest) ([]us_stock.UsFinaIndicatorItem, error)
	// UsIncome 调用 美股利润表 API
	UsIncome(ctx context.Context, req *us_stock.UsIncomeRequest) ([]us_stock.UsIncomeItem, error)
	// UsTradecal 调用 美股交易日历 API
	UsTradecal(ctx context.Context, req *us_stock.UsTradecalRequest) ([]us_stock.UsTradecalItem, error)
}

type usStockImpl struct {
	client *sdk.Client
}

// UsAdjfactor 调用 美股复权因子 API
func (impl *usStockImpl) UsAdjfactor(ctx context.Context, req *us_stock.UsAdjfactorRequest) ([]us_stock.UsAdjfactorItem, error) {
	return us_stock.UsAdjfactor(ctx, impl.client, req)
}

// UsBalancesheet 调用 美股资产负债表 API
func (impl *usStockImpl) UsBalancesheet(ctx context.Context, req *us_stock.UsBalancesheetRequest) ([]us_stock.UsBalancesheetItem, error) {
	return us_stock.UsBalancesheet(ctx, impl.client, req)
}

// UsBasic 调用 美股基础信息 API
func (impl *usStockImpl) UsBasic(ctx context.Context, req *us_stock.UsBasicRequest) ([]us_stock.UsBasicItem, error) {
	return us_stock.UsBasic(ctx, impl.client, req)
}

// UsCashflow 调用 美股现金流量表 API
func (impl *usStockImpl) UsCashflow(ctx context.Context, req *us_stock.UsCashflowRequest) ([]us_stock.UsCashflowItem, error) {
	return us_stock.UsCashflow(ctx, impl.client, req)
}

// UsDaily 调用 美股日线行情 API
func (impl *usStockImpl) UsDaily(ctx context.Context, req *us_stock.UsDailyRequest) ([]us_stock.UsDailyItem, error) {
	return us_stock.UsDaily(ctx, impl.client, req)
}

// UsDailyAdj 调用 美股复权行情 API
func (impl *usStockImpl) UsDailyAdj(ctx context.Context, req *us_stock.UsDailyAdjRequest) ([]us_stock.UsDailyAdjItem, error) {
	return us_stock.UsDailyAdj(ctx, impl.client, req)
}

// UsFinaIndicator 调用 美股财务指标数据 API
func (impl *usStockImpl) UsFinaIndicator(ctx context.Context, req *us_stock.UsFinaIndicatorRequest) ([]us_stock.UsFinaIndicatorItem, error) {
	return us_stock.UsFinaIndicator(ctx, impl.client, req)
}

// UsIncome 调用 美股利润表 API
func (impl *usStockImpl) UsIncome(ctx context.Context, req *us_stock.UsIncomeRequest) ([]us_stock.UsIncomeItem, error) {
	return us_stock.UsIncome(ctx, impl.client, req)
}

// UsTradecal 调用 美股交易日历 API
func (impl *usStockImpl) UsTradecal(ctx context.Context, req *us_stock.UsTradecalRequest) ([]us_stock.UsTradecalItem, error) {
	return us_stock.UsTradecal(ctx, impl.client, req)
}

func newusStockImpl(client *sdk.Client) UsStock {
	return &usStockImpl{client: client}
}
