// Code generated by tushare-gen. DO NOT EDIT.

package api

import (
	"context"
	"fmt"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// MoneyflowRequest 表示 moneyflow API 的请求
type MoneyflowRequest struct {
	TsCode string `json:"ts_code,omitempty"`
	TradeDate string `json:"trade_date,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
}

// MoneyflowItem 表示单个 moneyflow 数据项
type MoneyflowItem struct {
	TsCode string `json:"ts_code"`
	TradeDate string `json:"trade_date"`
	BuyElgVol float64 `json:"buy_elg_vol"`
	BuyElgAmt float64 `json:"buy_elg_amt"`
	SellElgVol float64 `json:"sell_elg_vol"`
	SellElgAmt float64 `json:"sell_elg_amt"`
	BuyLgVol float64 `json:"buy_lg_vol"`
	BuyLgAmt float64 `json:"buy_lg_amt"`
	SellLgVol float64 `json:"sell_lg_vol"`
	SellLgAmt float64 `json:"sell_lg_amt"`
	NetMfVol float64 `json:"net_mf_vol"`
}

// Moneyflow 调用 moneyflow API
func Moneyflow(ctx context.Context, client *sdk.Client, req *MoneyflowRequest) ([]MoneyflowItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.TradeDate != "" {
		params["trade_date"] = req.TradeDate
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}

	fields := []string{"ts_code", "trade_date", "buy_elg_vol", "buy_elg_amt", "sell_elg_vol", "sell_elg_amt", "buy_lg_vol", "buy_lg_amt", "sell_lg_vol", "sell_lg_amt", "net_mf_vol"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "moneyflow", params, fields, &result); err != nil {
		return nil, err
	}

	items := make([]MoneyflowItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 ts_code 的简单类型
		tsCode, ok := item["ts_code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 trade_date 的简单类型
		tradeDate, ok := item["trade_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 trade_date 类型")
		}
		// 处理 buy_elg_vol 的简单类型
		buyElgVol, ok := item["buy_elg_vol"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 buy_elg_vol 类型")
		}
		// 处理 buy_elg_amt 的简单类型
		buyElgAmt, ok := item["buy_elg_amt"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 buy_elg_amt 类型")
		}
		// 处理 sell_elg_vol 的简单类型
		sellElgVol, ok := item["sell_elg_vol"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 sell_elg_vol 类型")
		}
		// 处理 sell_elg_amt 的简单类型
		sellElgAmt, ok := item["sell_elg_amt"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 sell_elg_amt 类型")
		}
		// 处理 buy_lg_vol 的简单类型
		buyLgVol, ok := item["buy_lg_vol"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 buy_lg_vol 类型")
		}
		// 处理 buy_lg_amt 的简单类型
		buyLgAmt, ok := item["buy_lg_amt"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 buy_lg_amt 类型")
		}
		// 处理 sell_lg_vol 的简单类型
		sellLgVol, ok := item["sell_lg_vol"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 sell_lg_vol 类型")
		}
		// 处理 sell_lg_amt 的简单类型
		sellLgAmt, ok := item["sell_lg_amt"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 sell_lg_amt 类型")
		}
		// 处理 net_mf_vol 的简单类型
		netMfVol, ok := item["net_mf_vol"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 net_mf_vol 类型")
		}
		items[i] = MoneyflowItem{
			TsCode: tsCode,
			TradeDate: tradeDate,
			BuyElgVol: buyElgVol,
			BuyElgAmt: buyElgAmt,
			SellElgVol: sellElgVol,
			SellElgAmt: sellElgAmt,
			BuyLgVol: buyLgVol,
			BuyLgAmt: buyLgAmt,
			SellLgVol: sellLgVol,
			SellLgAmt: sellLgAmt,
			NetMfVol: netMfVol,
		}
	}

	return items, nil
}
