// Code generated by gen-mcp-tools. DO NOT EDIT.

package futurestools

import (
	"context"
	"encoding/json"
	"fmt"

	futures "tushare-go/pkg/sdk/api/futures"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerFutWeeklyMonthly registers the tool
func (r *FuturesTools) registerFutWeeklyMonthly() {
	inputSchema, _ := jsonschema.For[FutWeeklyMonthlyInput](nil)
	schemaJSON, _ := json.Marshal(inputSchema)

	tool := &mcp.Tool{
		Name:        "futures.fut_weekly_monthly",
		Description: "期货周/月线行情(每日更新)",
		InputSchema: json.RawMessage(schemaJSON),
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input FutWeeklyMonthlyInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &futures.FutWeeklyMonthlyRequest{
TsCode: input.TsCode,
TradeDate: input.TradeDate,
StartDate: input.StartDate,
EndDate: input.EndDate,
Freq: input.Freq,
Exchange: input.Exchange,

		}

		items, err := futures.FutWeeklyMonthly(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := FutWeeklyMonthlyOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
