// Code generated by gen-mcp-tools. DO NOT EDIT.

package futurestools

import (
	"context"
	"encoding/json"
	"fmt"

	futures "tushare-go/pkg/sdk/api/futures"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerFutHolding registers the tool
func (r *FuturesTools) registerFutHolding() {
	inputSchema, _ := jsonschema.For[FutHoldingInput](nil)
	schemaJSON, _ := json.Marshal(inputSchema)

	tool := &mcp.Tool{
		Name:        "futures.fut_holding",
		Description: "获取每日成交持仓排名数据",
		InputSchema: json.RawMessage(schemaJSON),
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input FutHoldingInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &futures.FutHoldingRequest{
TradeDate: input.TradeDate,
Symbol: input.Symbol,
StartDate: input.StartDate,
EndDate: input.EndDate,
Exchange: input.Exchange,

		}

		items, err := futures.FutHolding(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := FutHoldingOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
