// Code generated by gen-mcp-tools. DO NOT EDIT.

package futurestools

import (
	"context"

	futures "github.com/chenniannian90/tushare-go/pkg/sdk/api/futures"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// callFutDaily handles FutDaily tool calls
func (m *FuturesTools) callFutDaily(ctx context.Context, args map[string]interface{}) (*common.ToolResult, error) {
	req := &futures.FutDailyRequest{}

	// Parse arguments into request
	if err := common.ParseInput(args, req); err != nil {
		return common.ErrorResult(err), nil
	}

	items, err := futures.FutDaily(ctx, m.client, req)
	if err != nil {
		return common.ErrorResult(err), nil
	}

	// Format results
	result, err := common.APIResult(items, "futures", "fut_daily")
	if err != nil {
		return common.ErrorResult(err), nil
	}
	return result, nil
}
