// Code generated by gen-mcp-tools. DO NOT EDIT.

package futurestools

import (
	"tushare-go/pkg/sdk"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// FuturesTools represents futures tools
type FuturesTools struct {
	server *mcp.Server
	client *sdk.Client
}

// NewFuturesTools creates a new instance
func NewFuturesTools(server *mcp.Server, client *sdk.Client) *FuturesTools {
	return &FuturesTools{server: server, client: client}
}

// RegisterAll registers all tools
func (r *FuturesTools) RegisterAll() {
	r.registerApi314()
	r.registerFtLimit()
	r.registerFtMins()
	r.registerFutBasic()
	r.registerFutDaily()
	r.registerFutHolding()
	r.registerFutMapping()
	r.registerFutSettle()
	r.registerFutTick()
	r.registerFutWeeklyDetail()
	r.registerFutWeeklyMonthly()
	r.registerFutWsr()
	r.registerIndexDaily()
	r.registerRtFutMin()
	r.registerTradeCal()

}
