// Code generated by tushare-gen. DO NOT EDIT.

package stock_feature

import (
	"context"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// AhLotSizeRequest 表示 ah_lot_size API 的请求
type AhLotSizeRequest struct {
}

// AhLotSizeItem 表示单个 ah_lot_size 数据项
type AhLotSizeItem struct {
}

// AhLotSize 调用 ah_lot_size API
func AhLotSize(ctx context.Context, client *sdk.Client, req *AhLotSizeRequest) ([]AhLotSizeItem, error) {
	params := map[string]interface{}{}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "ah_lot_size", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []AhLotSizeItem{}, nil
}
