// Code generated by tushare-gen. DO NOT EDIT.

package stock_feature

import (
	"context"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// Api328Request 表示 api_328 API 的请求
type Api328Request struct {
}

// Api328Item 表示单个 api_328 数据项
type Api328Item struct {
}

// Api328 调用 api_328 API
func Api328(ctx context.Context, client *sdk.Client, req *Api328Request) ([]Api328Item, error) {
	params := map[string]interface{}{}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "api_328", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []Api328Item{}, nil
}
