// Code generated by tushare-gen. DO NOT EDIT.

package stock_feature

import (
	"context"
	"encoding/json"
	"fmt"
	"log"

	"tushare-go/pkg/sdk"
)

// CyqPerfRequest 表示 每日筹码及胜率 API 的请求
type CyqPerfRequest struct {
	TsCode string `json:"ts_code,omitempty"` // 股票代码
	TradeDate string `json:"trade_date,omitempty"` // 交易日期（YYYYMMDD）
	StartDate string `json:"start_date,omitempty"` // 开始日期
	EndDate string `json:"end_date,omitempty"` // 结束日期
}

// CyqPerfItem 表示单个 每日筹码及胜率 数据项
type CyqPerfItem struct {
	TsCode string `json:"ts_code"` // 股票代码
	TradeDate string `json:"trade_date"` // 交易日期
	HisLow float64 `json:"his_low"` // 历史最低价
	HisHigh float64 `json:"his_high"` // 历史最高价
	Cost5pct float64 `json:"cost_5pct"` // 5分位成本
	Cost15pct float64 `json:"cost_15pct"` // 15分位成本
	Cost50pct float64 `json:"cost_50pct"` // 50分位成本
	Cost85pct float64 `json:"cost_85pct"` // 85分位成本
	Cost95pct float64 `json:"cost_95pct"` // 95分位成本
	WeightAvg float64 `json:"weight_avg"` // 加权平均成本
	WinnerRate float64 `json:"winner_rate"` // 胜率
}

// CyqPerf 调用 每日筹码及胜率 API
// 获取A股每日筹码平均成本和胜率情况，每天18~19点左右更新，数据从2018年开始 来源：Tushare社区
// 注意：积分要求等使用限制请参考Tushare官方文档
func CyqPerf(ctx context.Context, client *sdk.Client, req *CyqPerfRequest) ([]CyqPerfItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.TradeDate != "" {
		params["trade_date"] = req.TradeDate
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}

	fields := []string{"ts_code", "trade_date", "his_low", "his_high", "cost_5pct", "cost_15pct", "cost_50pct", "cost_85pct", "cost_95pct", "weight_avg", "winner_rate"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPIFlexible(ctx, "cyq_perf", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]CyqPerfItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 ts_code 的简单类型
		// 对 string 类型尝试多种转换
		var tsCode string
		if v, ok := item["ts_code"].(string); ok {
			tsCode = v
		} else if v, ok := item["ts_code"].(float64); ok {
			tsCode = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["ts_code"].(int); ok {
			tsCode = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["ts_code"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: cyq_perf")
			log.Printf("字段: ts_code")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["ts_code"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 trade_date 的简单类型
		// 对 string 类型尝试多种转换
		var tradeDate string
		if v, ok := item["trade_date"].(string); ok {
			tradeDate = v
		} else if v, ok := item["trade_date"].(float64); ok {
			tradeDate = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["trade_date"].(int); ok {
			tradeDate = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["trade_date"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: cyq_perf")
			log.Printf("字段: trade_date")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["trade_date"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 trade_date 类型")
		}
		// 处理 his_low 的简单类型
		hisLow, ok := item["his_low"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 his_low 类型")
		}
		// 处理 his_high 的简单类型
		hisHigh, ok := item["his_high"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 his_high 类型")
		}
		// 处理 cost_5pct 的简单类型
		cost5pct, ok := item["cost_5pct"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 cost_5pct 类型")
		}
		// 处理 cost_15pct 的简单类型
		cost15pct, ok := item["cost_15pct"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 cost_15pct 类型")
		}
		// 处理 cost_50pct 的简单类型
		cost50pct, ok := item["cost_50pct"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 cost_50pct 类型")
		}
		// 处理 cost_85pct 的简单类型
		cost85pct, ok := item["cost_85pct"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 cost_85pct 类型")
		}
		// 处理 cost_95pct 的简单类型
		cost95pct, ok := item["cost_95pct"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 cost_95pct 类型")
		}
		// 处理 weight_avg 的简单类型
		weightAvg, ok := item["weight_avg"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 weight_avg 类型")
		}
		// 处理 winner_rate 的简单类型
		winnerRate, ok := item["winner_rate"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 winner_rate 类型")
		}
		items[i] = CyqPerfItem{
			TsCode: tsCode,
			TradeDate: tradeDate,
			HisLow: hisLow,
			HisHigh: hisHigh,
			Cost5pct: cost5pct,
			Cost15pct: cost15pct,
			Cost50pct: cost50pct,
			Cost85pct: cost85pct,
			Cost95pct: cost95pct,
			WeightAvg: weightAvg,
			WinnerRate: winnerRate,
		}
	}

	return items, nil
}
