// Code generated by gen-mcp-tools. DO NOT EDIT.

package indextools

import (
	"context"
	"fmt"

	index "github.com/chenniannian90/tushare-go/pkg/sdk/api/index"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// callIdxFactorPro handles IdxFactorPro tool calls
func (m *IndexTools) callIdxFactorPro(ctx context.Context, args map[string]interface{}) (*common.ToolResult, error) {
	req := &index.IdxFactorProRequest{}

	// Parse arguments into request
	// TODO: Implement proper argument parsing based on request struct fields
	// For now, this is a placeholder implementation

	items, err := index.IdxFactorPro(ctx, m.client, req)
	if err != nil {
		return nil, fmt.Errorf("failed to call idx_factor_pro API: %w", err)
	}

	// Format results
	result, err := common.APIResult(items, "index", "idx_factor_pro")
	if err != nil {
		return nil, err
	}
	return result, nil
}
