// Code generated by gen-mcp-tools. DO NOT EDIT.

package indextools

import (
	"context"
	"fmt"

	index "github.com/chenniannian90/tushare-go/pkg/sdk/api/index"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// callIndexMonthly handles IndexMonthly tool calls
func (m *IndexTools) callIndexMonthly(ctx context.Context, args map[string]interface{}) (*common.ToolResult, error) {
	req := &index.IndexMonthlyRequest{}

	// Parse arguments into request
	// TODO: Implement proper argument parsing based on request struct fields
	// For now, this is a placeholder implementation

	items, err := index.IndexMonthly(ctx, m.client, req)
	if err != nil {
		return nil, fmt.Errorf("failed to call index_monthly API: %w", err)
	}

	// Format results
	result, err := common.APIResult(items, "index", "index_monthly")
	if err != nil {
		return nil, err
	}
	return result, nil
}
