// Code generated by gen-mcp-tools. DO NOT EDIT.

package indextools

import (
	"context"

	index "github.com/chenniannian90/tushare-go/pkg/sdk/api/index"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// callIndexMemberAll handles IndexMemberAll tool calls
func (m *IndexTools) callIndexMemberAll(ctx context.Context, args map[string]interface{}) (*common.ToolResult, error) {
	req := &index.IndexMemberAllRequest{}

	// Parse arguments into request
	if err := common.ParseInput(args, req); err != nil {
		return common.ErrorResult(err), nil
	}

	items, err := index.IndexMemberAll(ctx, m.client, req)
	if err != nil {
		return common.ErrorResult(err), nil
	}

	// Format results
	result, err := common.APIResult(items, "index", "index_member_all")
	if err != nil {
		return common.ErrorResult(err), nil
	}
	return result, nil
}
