// Code generated by gen-mcp-tools. DO NOT EDIT.

package indextools

import (
	"context"
	"fmt"

	index "github.com/chenniannian90/tushare-go/pkg/sdk/api/index"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// callRtIdxMin handles RtIdxMin tool calls
func (m *IndexTools) callRtIdxMin(ctx context.Context, args map[string]interface{}) (*common.ToolResult, error) {
	req := &index.RtIdxMinRequest{}

	// Parse arguments into request
	// TODO: Implement proper argument parsing based on request struct fields
	// For now, this is a placeholder implementation

	items, err := index.RtIdxMin(ctx, m.client, req)
	if err != nil {
		return nil, fmt.Errorf("failed to call rt_idx_min API: %w", err)
	}

	// Format results
	result, err := common.APIResult(items, "index", "rt_idx_min")
	if err != nil {
		return nil, err
	}
	return result, nil
}
