// Code generated by gen-mcp-tools. DO NOT EDIT.

package wealth_fund_salestools

import (
	"tushare-go/pkg/sdk"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// Wealth_fund_salesTools represents wealth_fund_sales tools
type Wealth_fund_salesTools struct {
	server *mcp.Server
	client *sdk.Client
}

// NewWealth_fund_salesTools creates a new instance
func NewWealth_fund_salesTools(server *mcp.Server, client *sdk.Client) *Wealth_fund_salesTools {
	return &Wealth_fund_salesTools{server: server, client: client}
}

// RegisterAll registers all tools
func (r *Wealth_fund_salesTools) RegisterAll() {
	r.registerFundSalesVol()

}
