// Code generated by tushare-gen. DO NOT EDIT.

package llm_corpus

import (
	"context"
	"fmt"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// ResearchReportRequest 表示 券商研究报告 API 的请求
type ResearchReportRequest struct {
	TradeDate string `json:"trade_date,omitempty"` // 研报日期（格式：YYYYMMDD，下同）
	StartDate string `json:"start_date,omitempty"` // 研报开始日期
	EndDate string `json:"end_date,omitempty"` // 研报结束日期
	ReportType string `json:"report_type,omitempty"` // 研报类别：个股研报/行业研报
	TsCode string `json:"ts_code,omitempty"` // 股票代码
	InstCsname string `json:"inst_csname,omitempty"` // 券商名称
	IndName string `json:"ind_name,omitempty"` // 行业名称
}

// ResearchReportItem 表示单个 券商研究报告 数据项
type ResearchReportItem struct {
	TradeDate string `json:"trade_date"` // 研报发布时间
	Abstr string `json:"abstr"` // 研报摘要
	Title string `json:"title"` // 研报标题
	ReportType string `json:"report_type"` // 研报类别
	Author string `json:"author"` // 作者
	Name string `json:"name"` // 股票名称
	TsCode string `json:"ts_code"` // 股票代码
	InstCsname string `json:"inst_csname"` // 机构简称
	IndName string `json:"ind_name"` // 行业名称
	Url string `json:"url"` // 下载链接
}

// ResearchReport 调用 券商研究报告 API
func ResearchReport(ctx context.Context, client *sdk.Client, req *ResearchReportRequest) ([]ResearchReportItem, error) {
	params := map[string]interface{}{}
	if req.TradeDate != "" {
		params["trade_date"] = req.TradeDate
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}
	if req.ReportType != "" {
		params["report_type"] = req.ReportType
	}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.InstCsname != "" {
		params["inst_csname"] = req.InstCsname
	}
	if req.IndName != "" {
		params["ind_name"] = req.IndName
	}

	fields := []string{"trade_date", "abstr", "title", "report_type", "author", "name", "ts_code", "inst_csname", "ind_name", "url"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "research_report", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]ResearchReportItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 trade_date 的简单类型
		tradeDate, ok := item["trade_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 trade_date 类型")
		}
		// 处理 abstr 的简单类型
		abstr, ok := item["abstr"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 abstr 类型")
		}
		// 处理 title 的简单类型
		title, ok := item["title"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 title 类型")
		}
		// 处理 report_type 的简单类型
		reportType, ok := item["report_type"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 report_type 类型")
		}
		// 处理 author 的简单类型
		author, ok := item["author"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 author 类型")
		}
		// 处理 name 的简单类型
		name, ok := item["name"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 name 类型")
		}
		// 处理 ts_code 的简单类型
		tsCode, ok := item["ts_code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 inst_csname 的简单类型
		instCsname, ok := item["inst_csname"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 inst_csname 类型")
		}
		// 处理 ind_name 的简单类型
		indName, ok := item["ind_name"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ind_name 类型")
		}
		// 处理 url 的简单类型
		url, ok := item["url"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 url 类型")
		}
		items[i] = ResearchReportItem{
			TradeDate: tradeDate,
			Abstr: abstr,
			Title: title,
			ReportType: reportType,
			Author: author,
			Name: name,
			TsCode: tsCode,
			InstCsname: instCsname,
			IndName: indName,
			Url: url,
		}
	}

	return items, nil
}
