// Code generated by tushare-gen. DO NOT EDIT.

package spot

import (
	"context"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// SpotBasicRequest 表示 spot_basic API 的请求
type SpotBasicRequest struct {
}

// SpotBasicItem 表示单个 spot_basic 数据项
type SpotBasicItem struct {
}

// SpotBasic 调用 spot_basic API
func SpotBasic(ctx context.Context, client *sdk.Client, req *SpotBasicRequest) ([]SpotBasicItem, error) {
	params := map[string]interface{}{}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "spot_basic", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []SpotBasicItem{}, nil
}
