// Code generated by gen-mcp-tools. DO NOT EDIT.

package bondtools

import (
	"context"

	bond "github.com/chenniannian90/tushare-go/pkg/sdk/api/bond"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// callBondBlk handles BondBlk tool calls
func (m *BondTools) callBondBlk(ctx context.Context, args map[string]interface{}) (*common.ToolResult, error) {
	req := &bond.BondBlkRequest{}

	// Parse arguments into request
	if err := common.ParseInput(args, req); err != nil {
		return common.ErrorResult(err), nil
	}

	items, err := bond.BondBlk(ctx, m.client, req)
	if err != nil {
		return common.ErrorResult(err), nil
	}

	// Format results
	result, err := common.APIResult(items, "bond", "bond_blk")
	if err != nil {
		return common.ErrorResult(err), nil
	}
	return result, nil
}
