// Code generated by gen-mcp-tools. DO NOT EDIT.

package bondtools

import (
	"context"
	"encoding/json"
	"fmt"

	bond "tushare-go/pkg/sdk/api/bond"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerRepoDaily registers the tool
func (r *BondTools) registerRepoDaily() {
	inputSchema, _ := jsonschema.For[RepoDailyInput](nil)
	schemaJSON, _ := json.Marshal(inputSchema)

	tool := &mcp.Tool{
		Name:        "bond.repo_daily",
		Description: "债券回购日行情",
		InputSchema: json.RawMessage(schemaJSON),
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input RepoDailyInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &bond.RepoDailyRequest{
TsCode: input.TsCode,
TradeDate: input.TradeDate,
StartDate: input.StartDate,
EndDate: input.EndDate,

		}

		items, err := bond.RepoDaily(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := RepoDailyOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
