// Code generated by tushare-gen. DO NOT EDIT.

package stock_reference

import (
	"context"
	"encoding/json"
	"fmt"
	"log"

	"tushare-go/pkg/sdk"
)

// StkAccountOldRequest 表示 股票开户数据（旧） API 的请求
type StkAccountOldRequest struct {
	StartDate string `json:"start_date,omitempty"` // 开始日期
	EndDate string `json:"end_date,omitempty"` // 结束日期
}

// StkAccountOldItem 表示单个 股票开户数据（旧） 数据项
type StkAccountOldItem struct {
	Date string `json:"date"` // 统计周期
	NewSh int `json:"new_sh"` // 本周新增（上海，户）
	NewSz int `json:"new_sz"` // 本周新增（深圳，户）
	ActiveSh float64 `json:"active_sh"` // 期末有效账户（上海，万户）
	ActiveSz float64 `json:"active_sz"` // 期末有效账户（深圳，万户）
	TotalSh float64 `json:"total_sh"` // 期末账户数（上海，万户）
	TotalSz float64 `json:"total_sz"` // 期末账户数（深圳，万户）
	TradeSh float64 `json:"trade_sh"` // 参与交易账户数（上海，万户）
	TradeSz float64 `json:"trade_sz"` // 参与交易账户数（深圳，万户）
}

// StkAccountOld 调用 股票开户数据（旧） API
// 获取股票账户开户数据旧版格式数据，数据从2008年1月开始，到2015年5月29，新数据请通过股票开户数据获取。
// 注意：积分要求等使用限制请参考Tushare官方文档
func StkAccountOld(ctx context.Context, client *sdk.Client, req *StkAccountOldRequest) ([]StkAccountOldItem, error) {
	params := map[string]interface{}{}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}

	fields := []string{"date", "new_sh", "new_sz", "active_sh", "active_sz", "total_sh", "total_sz", "trade_sh", "trade_sz"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPIFlexible(ctx, "stk_account_old", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]StkAccountOldItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 date 的简单类型
		// 对 string 类型尝试多种转换
		var date string
		if item["date"] == nil {
			// 字段值为 null，使用零值
			date = ""
		} else if v, ok := item["date"].(string); ok {
			date = v
		} else if v, ok := item["date"].(float64); ok {
			date = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["date"].(int); ok {
			date = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["date"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: stk_account_old")
			log.Printf("字段: date")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["date"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 date 类型")
		}
		// 处理 new_sh 的简单类型
		// 处理 int 类型 - JSON 数字解析为 float64，需要转换
		var newSh int
		if item["new_sh"] == nil {
			// 字段值为 null，使用零值
			newSh = 0
		} else if v, ok := item["new_sh"].(float64); ok {
			newSh = int(v)
		} else if v, ok := item["new_sh"].(int); ok {
			newSh = v
		} else {
			return nil, fmt.Errorf("无效的 new_sh 类型，期望 int 或 float64")
		}
		// 处理 new_sz 的简单类型
		// 处理 int 类型 - JSON 数字解析为 float64，需要转换
		var newSz int
		if item["new_sz"] == nil {
			// 字段值为 null，使用零值
			newSz = 0
		} else if v, ok := item["new_sz"].(float64); ok {
			newSz = int(v)
		} else if v, ok := item["new_sz"].(int); ok {
			newSz = v
		} else {
			return nil, fmt.Errorf("无效的 new_sz 类型，期望 int 或 float64")
		}
		// 处理 active_sh 的简单类型
		activeSh, ok := item["active_sh"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 active_sh 类型")
		}
		// 处理 active_sz 的简单类型
		activeSz, ok := item["active_sz"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 active_sz 类型")
		}
		// 处理 total_sh 的简单类型
		totalSh, ok := item["total_sh"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 total_sh 类型")
		}
		// 处理 total_sz 的简单类型
		totalSz, ok := item["total_sz"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 total_sz 类型")
		}
		// 处理 trade_sh 的简单类型
		tradeSh, ok := item["trade_sh"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 trade_sh 类型")
		}
		// 处理 trade_sz 的简单类型
		tradeSz, ok := item["trade_sz"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 trade_sz 类型")
		}
		items[i] = StkAccountOldItem{
			Date: date,
			NewSh: newSh,
			NewSz: newSz,
			ActiveSh: activeSh,
			ActiveSz: activeSz,
			TotalSh: totalSh,
			TotalSz: totalSz,
			TradeSh: tradeSh,
			TradeSz: tradeSz,
		}
	}

	return items, nil
}
