// Code generated by tushare-gen. DO NOT EDIT.

package stock_basic

import (
	"context"
	"fmt"

	"tushare-go/pkg/sdk"
)

// StkRewardsRequest 表示 管理层薪酬和持股 API 的请求
type StkRewardsRequest struct {
	TsCode string `json:"ts_code,omitempty"` // TS股票代码，支持单个或多个代码输入
	EndDate string `json:"end_date,omitempty"` // 报告期
}

// StkRewardsItem 表示单个 管理层薪酬和持股 数据项
type StkRewardsItem struct {
	TsCode string `json:"ts_code"` // TS股票代码
	AnnDate string `json:"ann_date"` // 公告日期
	EndDate string `json:"end_date"` // 截止日期
	Name string `json:"name"` // 姓名
	Title string `json:"title"` // 职务
	Reward float64 `json:"reward"` // 报酬
	HoldVol float64 `json:"hold_vol"` // 持股数
}

// StkRewards 调用 管理层薪酬和持股 API
// 获取上市公司管理层薪酬和持股
// 注意：积分要求等使用限制请参考Tushare官方文档
func StkRewards(ctx context.Context, client *sdk.Client, req *StkRewardsRequest) ([]StkRewardsItem, error) {
	params := map[string]interface{}{}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}

	fields := []string{"ts_code", "ann_date", "end_date", "name", "title", "reward", "hold_vol"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPIFlexible(ctx, "stk_rewards", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]StkRewardsItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 ts_code 的简单类型
		tsCode, ok := item["ts_code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 ann_date 的简单类型
		annDate, ok := item["ann_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ann_date 类型")
		}
		// 处理 end_date 的简单类型
		endDate, ok := item["end_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 end_date 类型")
		}
		// 处理 name 的简单类型
		name, ok := item["name"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 name 类型")
		}
		// 处理 title 的简单类型
		title, ok := item["title"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 title 类型")
		}
		// 处理 reward 的简单类型
		reward, ok := item["reward"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 reward 类型")
		}
		// 处理 hold_vol 的简单类型
		holdVol, ok := item["hold_vol"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 hold_vol 类型")
		}
		items[i] = StkRewardsItem{
			TsCode: tsCode,
			AnnDate: annDate,
			EndDate: endDate,
			Name: name,
			Title: title,
			Reward: reward,
			HoldVol: holdVol,
		}
	}

	return items, nil
}
