// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_fund_flowtools

import (
	"context"
	"fmt"

	stock_stock_fund_flow "github.com/chenniannian90/tushare-go/pkg/sdk/api/stock/stock_fund_flow"
	"github.com/chenniannian90/tushare-go/pkg/mcp/common"
)

// callApi344 handles Api344 tool calls
func (m *Stock_fund_flowTools) callApi344(ctx context.Context, args map[string]interface{}) (*common.ToolResult, error) {
	req := &stock_stock_fund_flow.Api344Request{}

	// Parse arguments into request
	// TODO: Implement proper argument parsing based on request struct fields
	// For now, this is a placeholder implementation

	items, err := stock_stock_fund_flow.Api344(ctx, m.client, req)
	if err != nil {
		return nil, fmt.Errorf("failed to call api344 API: %w", err)
	}

	// Format results
	result, err := common.APIResult(items, "stock_fund_flow", "api344")
	if err != nil {
		return nil, err
	}
	return result, nil
}
