// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_fund_flowtools

import (
	"context"
	"encoding/json"
	"fmt"

	stock_fund_flow "tushare-go/pkg/sdk/api/stock_fund_flow"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerMoneyflowHsgt registers the tool
func (r *Stock_fund_flowTools) registerMoneyflowHsgt() {
	inputSchema, _ := jsonschema.For[MoneyflowHsgtInput](nil)
	schemaJSON, _ := json.Marshal(inputSchema)

	tool := &mcp.Tool{
		Name:        "stock_fund_flow.moneyflow_hsgt",
		Description: "获取沪股通、深股通、港股通每日资金流向数据，每次最多返回300条记录，总量不限制。 积分要求：2000积分起，5000积分每分钟可提取500次",
		InputSchema: json.RawMessage(schemaJSON),
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input MoneyflowHsgtInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &stock_fund_flow.MoneyflowHsgtRequest{
TradeDate: input.TradeDate,
StartDate: input.StartDate,
EndDate: input.EndDate,

		}

		items, err := stock_fund_flow.MoneyflowHsgt(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := MoneyflowHsgtOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
