// Code generated by gen-mcp-tools. DO NOT EDIT.

package stock_fund_flowtools

import (
	"context"
	"encoding/json"
	"fmt"

	stock_fund_flow "tushare-go/pkg/sdk/api/stock_fund_flow"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerMoneyflowIndDc registers the tool
func (r *Stock_fund_flowTools) registerMoneyflowIndDc() {
	inputSchema, _ := jsonschema.For[MoneyflowIndDcInput](nil)
	schemaJSON, _ := json.Marshal(inputSchema)

	tool := &mcp.Tool{
		Name:        "stock_fund_flow.moneyflow_ind_dc",
		Description: "获取东方财富板块资金流向，每天盘后更新",
		InputSchema: json.RawMessage(schemaJSON),
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input MoneyflowIndDcInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &stock_fund_flow.MoneyflowIndDcRequest{
TsCode: input.TsCode,
TradeDate: input.TradeDate,
StartDate: input.StartDate,
EndDate: input.EndDate,
ContentType: input.ContentType,

		}

		items, err := stock_fund_flow.MoneyflowIndDc(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := MoneyflowIndDcOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
