// Code generated by tushare-gen. DO NOT EDIT.

package macro_social_financing

import (
	"context"
	"fmt"

	"tushare-go/pkg/sdk"
)

// SfMonthRequest 表示 社融增量（月度） API 的请求
type SfMonthRequest struct {
	M string `json:"m,omitempty"` // 月份（YYYYMM，下同），支持多个月份同时输入，逗号分隔
	StartM string `json:"start_m,omitempty"` // 开始月份
	EndM string `json:"end_m,omitempty"` // 结束月份
}

// SfMonthItem 表示单个 社融增量（月度） 数据项
type SfMonthItem struct {
	Month string `json:"month"` // 月度
	IncMonth float64 `json:"inc_month"` // 社融增量当月值（亿元）
	IncCumval float64 `json:"inc_cumval"` // 社融增量累计值（亿元）
	StkEndval float64 `json:"stk_endval"` // 社融存量期末值（万亿元）
}

// SfMonth 调用 社融增量（月度） API
// 获取月度社会融资数据
// 注意：积分要求等使用限制请参考Tushare官方文档
func SfMonth(ctx context.Context, client *sdk.Client, req *SfMonthRequest) ([]SfMonthItem, error) {
	params := map[string]interface{}{}
	if req.M != "" {
		params["m"] = req.M
	}
	if req.StartM != "" {
		params["start_m"] = req.StartM
	}
	if req.EndM != "" {
		params["end_m"] = req.EndM
	}

	fields := []string{"month", "inc_month", "inc_cumval", "stk_endval"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPIFlexible(ctx, "sf_month", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]SfMonthItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 month 的简单类型
		// 对 string 类型尝试多种转换
		var month string
		if v, ok := item["month"].(string); ok {
			month = v
		} else if v, ok := item["month"].(float64); ok {
			month = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["month"].(int); ok {
			month = fmt.Sprintf("%d", v)
		} else {
			return nil, fmt.Errorf("无效的 month 类型")
		}
		// 处理 inc_month 的简单类型
		incMonth, ok := item["inc_month"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 inc_month 类型")
		}
		// 处理 inc_cumval 的简单类型
		incCumval, ok := item["inc_cumval"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 inc_cumval 类型")
		}
		// 处理 stk_endval 的简单类型
		stkEndval, ok := item["stk_endval"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 stk_endval 类型")
		}
		items[i] = SfMonthItem{
			Month: month,
			IncMonth: incMonth,
			IncCumval: incCumval,
			StkEndval: stkEndval,
		}
	}

	return items, nil
}
