// Code generated by tushare-gen. DO NOT EDIT.

package stock_fund_flow

import (
	"context"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// Api345Request 表示 api_345 API 的请求
type Api345Request struct {
}

// Api345Item 表示单个 api_345 数据项
type Api345Item struct {
}

// Api345 调用 api_345 API
func Api345(ctx context.Context, client *sdk.Client, req *Api345Request) ([]Api345Item, error) {
	params := map[string]interface{}{}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "api_345", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []Api345Item{}, nil
}
