// Code generated by tushare-gen. DO NOT EDIT.

package stock_margin

import (
	"context"
	"fmt"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// SlbLenRequest 表示 转融资交易汇总 API 的请求
type SlbLenRequest struct {
	TradeDate string `json:"trade_date,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
}

// SlbLenItem 表示单个 转融资交易汇总 数据项
type SlbLenItem struct {
	TradeDate string `json:"trade_date"`
	Ob float64 `json:"ob"`
	AucAmount float64 `json:"auc_amount"`
	RepoAmount float64 `json:"repo_amount"`
	RepayAmount float64 `json:"repay_amount"`
	Cb float64 `json:"cb"`
}

// SlbLen 调用 转融资交易汇总 API
func SlbLen(ctx context.Context, client *sdk.Client, req *SlbLenRequest) ([]SlbLenItem, error) {
	params := map[string]interface{}{}
	if req.TradeDate != "" {
		params["trade_date"] = req.TradeDate
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}

	fields := []string{"trade_date", "ob", "auc_amount", "repo_amount", "repay_amount", "cb"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "slb_len", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]SlbLenItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 trade_date 的简单类型
		tradeDate, ok := item["trade_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 trade_date 类型")
		}
		// 处理 ob 的简单类型
		ob, ok := item["ob"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 ob 类型")
		}
		// 处理 auc_amount 的简单类型
		aucAmount, ok := item["auc_amount"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 auc_amount 类型")
		}
		// 处理 repo_amount 的简单类型
		repoAmount, ok := item["repo_amount"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 repo_amount 类型")
		}
		// 处理 repay_amount 的简单类型
		repayAmount, ok := item["repay_amount"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 repay_amount 类型")
		}
		// 处理 cb 的简单类型
		cb, ok := item["cb"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 cb 类型")
		}
		items[i] = SlbLenItem{
			TradeDate: tradeDate,
			Ob: ob,
			AucAmount: aucAmount,
			RepoAmount: repoAmount,
			RepayAmount: repayAmount,
			Cb: cb,
		}
	}

	return items, nil
}
