// Code generated by tushare-gen. DO NOT EDIT.

package stock_margin

import (
	"context"
	"fmt"

	"github.com/chenniannian90/tushare-go/pkg/sdk"
)

// SlbSecDetailRequest 表示 转融券交易明细(停） API 的请求
type SlbSecDetailRequest struct {
	TradeDate string `json:"trade_date,omitempty"`
	TsCode string `json:"ts_code,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
}

// SlbSecDetailItem 表示单个 转融券交易明细(停） 数据项
type SlbSecDetailItem struct {
	TradeDate string `json:"trade_date"`
	TsCode string `json:"ts_code"`
	Name string `json:"name"`
	Tenor string `json:"tenor"`
	FeeRate float64 `json:"fee_rate"`
	LentQnt float64 `json:"lent_qnt"`
}

// SlbSecDetail 调用 转融券交易明细(停） API
func SlbSecDetail(ctx context.Context, client *sdk.Client, req *SlbSecDetailRequest) ([]SlbSecDetailItem, error) {
	params := map[string]interface{}{}
	if req.TradeDate != "" {
		params["trade_date"] = req.TradeDate
	}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}

	fields := []string{"trade_date", "ts_code", "name", "tenor", "fee_rate", "lent_qnt"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPI(ctx, "slb_sec_detail", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]SlbSecDetailItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 trade_date 的简单类型
		tradeDate, ok := item["trade_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 trade_date 类型")
		}
		// 处理 ts_code 的简单类型
		tsCode, ok := item["ts_code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 name 的简单类型
		name, ok := item["name"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 name 类型")
		}
		// 处理 tenor 的简单类型
		tenor, ok := item["tenor"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 tenor 类型")
		}
		// 处理 fee_rate 的简单类型
		feeRate, ok := item["fee_rate"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 fee_rate 类型")
		}
		// 处理 lent_qnt 的简单类型
		lentQnt, ok := item["lent_qnt"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 lent_qnt 类型")
		}
		items[i] = SlbSecDetailItem{
			TradeDate: tradeDate,
			TsCode: tsCode,
			Name: name,
			Tenor: tenor,
			FeeRate: feeRate,
			LentQnt: lentQnt,
		}
	}

	return items, nil
}
