// Code generated by tushare-gen. DO NOT EDIT.

package industry_tmt

import (
	"context"
	"encoding/json"
	"fmt"
	"log"

	"tushare-go/pkg/sdk"
)

// BoMonthlyRequest 表示 电影月度票房 API 的请求
type BoMonthlyRequest struct {
	Date string `json:"date,omitempty"` // 日期（每月1号，格式YYYYMMDD）
}

// BoMonthlyItem 表示单个 电影月度票房 数据项
type BoMonthlyItem struct {
	Date string `json:"date"` // 日期
	Name string `json:"name"` // 影片名称
	ListDate string `json:"list_date"` // 上映日期
	AvgPrice float64 `json:"avg_price"` // 平均票价
	MonthAmount float64 `json:"month_amount"` // 当月票房（万）
	ListDay int `json:"list_day"` // 月内天数
	PPc int `json:"p_pc"` // 场均人次
	WomIndex float64 `json:"wom_index"` // 口碑指数
	MRatio float64 `json:"m_ratio"` // 月度占比（%）
	Rank int `json:"rank"` // 排名
}

// BoMonthly 调用 电影月度票房 API
// 获取电影月度票房数据数据更新：本月更新上一月数据数据历史： 数据从2008年1月1日开始，超过10年历史数据。数据
// 注意：积分要求等使用限制请参考Tushare官方文档
func BoMonthly(ctx context.Context, client *sdk.Client, req *BoMonthlyRequest) ([]BoMonthlyItem, error) {
	params := map[string]interface{}{}
	if req.Date != "" {
		params["date"] = req.Date
	}

	fields := []string{"date", "name", "list_date", "avg_price", "month_amount", "list_day", "p_pc", "wom_index", "m_ratio", "rank"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPIFlexible(ctx, "bo_monthly", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]BoMonthlyItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 date 的简单类型
		// 对 string 类型尝试多种转换
		var date string
		if v, ok := item["date"].(string); ok {
			date = v
		} else if v, ok := item["date"].(float64); ok {
			date = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["date"].(int); ok {
			date = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["date"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: bo_monthly")
			log.Printf("字段: date")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["date"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 date 类型")
		}
		// 处理 name 的简单类型
		// 对 string 类型尝试多种转换
		var name string
		if v, ok := item["name"].(string); ok {
			name = v
		} else if v, ok := item["name"].(float64); ok {
			name = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["name"].(int); ok {
			name = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["name"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: bo_monthly")
			log.Printf("字段: name")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["name"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 name 类型")
		}
		// 处理 list_date 的简单类型
		// 对 string 类型尝试多种转换
		var listDate string
		if v, ok := item["list_date"].(string); ok {
			listDate = v
		} else if v, ok := item["list_date"].(float64); ok {
			listDate = fmt.Sprintf("%.0f", v)
		} else if v, ok := item["list_date"].(int); ok {
			listDate = fmt.Sprintf("%d", v)
		} else {
			itemJSON, _ := json.Marshal(item)
			fieldJSON, _ := json.Marshal(item["list_date"])
			log.Printf("=== 字段解析失败 ===")
			log.Printf("API: bo_monthly")
			log.Printf("字段: list_date")
			log.Printf("错误: 类型转换失败，期望类型 string，支持 string/float64/int")
			log.Printf("字段原始值: %s", string(fieldJSON))
			log.Printf("字段实际类型: %T", item["list_date"])
			log.Printf("当前Item: %s", string(itemJSON))
			log.Printf("===================")
			return nil, fmt.Errorf("无效的 list_date 类型")
		}
		// 处理 avg_price 的简单类型
		avgPrice, ok := item["avg_price"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 avg_price 类型")
		}
		// 处理 month_amount 的简单类型
		monthAmount, ok := item["month_amount"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 month_amount 类型")
		}
		// 处理 list_day 的简单类型
		listDay, ok := item["list_day"].(int)
		if !ok {
			return nil, fmt.Errorf("无效的 list_day 类型")
		}
		// 处理 p_pc 的简单类型
		pPc, ok := item["p_pc"].(int)
		if !ok {
			return nil, fmt.Errorf("无效的 p_pc 类型")
		}
		// 处理 wom_index 的简单类型
		womIndex, ok := item["wom_index"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 wom_index 类型")
		}
		// 处理 m_ratio 的简单类型
		mRatio, ok := item["m_ratio"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 m_ratio 类型")
		}
		// 处理 rank 的简单类型
		rank, ok := item["rank"].(int)
		if !ok {
			return nil, fmt.Errorf("无效的 rank 类型")
		}
		items[i] = BoMonthlyItem{
			Date: date,
			Name: name,
			ListDate: listDate,
			AvgPrice: avgPrice,
			MonthAmount: monthAmount,
			ListDay: listDay,
			PPc: pPc,
			WomIndex: womIndex,
			MRatio: mRatio,
			Rank: rank,
		}
	}

	return items, nil
}
