// Code generated by tushare-gen. DO NOT EDIT.

package industry_tmt

import (
	"context"

	"tushare-go/pkg/sdk"
)

// TmtTwincomedetailRequest 表示 台湾电子产业月营收明细 API 的请求
type TmtTwincomedetailRequest struct {
	Date string `json:"date,omitempty"` // 报告期
	Item string `json:"item,omitempty"` // 产品代码
	Symbol string `json:"symbol,omitempty"` // 公司代码
	StartDate string `json:"start_date,omitempty"` // 报告期开始日期
	EndDate string `json:"end_date,omitempty"` // 报告期结束日期
	Source string `json:"source,omitempty"` // None
}

// TmtTwincomedetailItem 表示单个 台湾电子产业月营收明细 数据项
type TmtTwincomedetailItem struct {
}

// TmtTwincomedetail 调用 台湾电子产业月营收明细 API
func TmtTwincomedetail(ctx context.Context, client *sdk.Client, req *TmtTwincomedetailRequest) ([]TmtTwincomedetailItem, error) {
	params := map[string]interface{}{}
	if req.Date != "" {
		params["date"] = req.Date
	}
	if req.Item != "" {
		params["item"] = req.Item
	}
	if req.Symbol != "" {
		params["symbol"] = req.Symbol
	}
	if req.StartDate != "" {
		params["start_date"] = req.StartDate
	}
	if req.EndDate != "" {
		params["end_date"] = req.EndDate
	}
	if req.Source != "" {
		params["source"] = req.Source
	}

	fields := []string{}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPIFlexible(ctx, "tmt_twincomedetail", params, fields, &result); err != nil {
		return nil, err
	}
	// No response fields defined, return empty items
	return []TmtTwincomedetailItem{}, nil
}
