// Code generated by gen-mcp-tools. DO NOT EDIT.

package macro_interest_ratetools

import (
	"context"
	"encoding/json"
	"fmt"

	macro_interest_rate "tushare-go/pkg/sdk/api/macro_interest_rate"
	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// registerHibor registers the tool
func (r *Macro_interest_rateTools) registerHibor() {
	inputSchema, _ := jsonschema.For[HiborInput](nil)
	schemaJSON, _ := json.Marshal(inputSchema)

	tool := &mcp.Tool{
		Name:        "macro_interest_rate.hibor",
		Description: "Hibor利率",
		InputSchema: json.RawMessage(schemaJSON),
	}

	handler := func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		var input HiborInput
		if err := json.Unmarshal(req.Params.Arguments, &input); err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"Invalid input: %v"}`, err)}},
			}, nil
		}

		apiReq := &macro_interest_rate.HiborRequest{
Date: input.Date,
StartDate: input.StartDate,
EndDate: input.EndDate,

		}

		items, err := macro_interest_rate.Hibor(ctx, r.client, apiReq)
		if err != nil {
			return &mcp.CallToolResult{
				IsError: true,
				Content: []mcp.Content{&mcp.TextContent{Text: fmt.Sprintf(`{"error":"API call failed: %v"}`, err)}},
			}, nil
		}

		output := HiborOutput{
			Data:  items,
			Total: len(items),
		}

		outputJSON, _ := json.MarshalIndent(output, "", "  ")
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: string(outputJSON)}},
		}, nil
	}

	r.server.AddTool(tool, handler)
}
