// Code generated by tushare-gen. DO NOT EDIT.

package stock_board

import (
	"context"
	"fmt"

	"tushare-go/pkg/sdk"
)

// TopInstRequest 表示 龙虎榜机构交易单 API 的请求
type TopInstRequest struct {
	TradeDate string `json:"trade_date,omitempty"` // 交易日期
	TsCode string `json:"ts_code,omitempty"` // TS代码
}

// TopInstItem 表示单个 龙虎榜机构交易单 数据项
type TopInstItem struct {
	TradeDate string `json:"trade_date"` // 交易日期
	TsCode string `json:"ts_code"` // TS代码
	Exalter string `json:"exalter"` // 营业部名称
	Side string `json:"side"` // 买卖类型0：买入金额最大的前5名， 1：卖出金额最大的前5名
	Buy float64 `json:"buy"` // 买入额（元）
	BuyRate float64 `json:"buy_rate"` // 买入占总成交比例
	Sell float64 `json:"sell"` // 卖出额（元）
	SellRate float64 `json:"sell_rate"` // 卖出占总成交比例
	NetBuy float64 `json:"net_buy"` // 净成交额（元）
	Reason string `json:"reason"` // 上榜理由
}

// TopInst 调用 龙虎榜机构交易单 API
// 龙虎榜机构成交明细
// 注意：积分要求等使用限制请参考Tushare官方文档
func TopInst(ctx context.Context, client *sdk.Client, req *TopInstRequest) ([]TopInstItem, error) {
	params := map[string]interface{}{}
	if req.TradeDate != "" {
		params["trade_date"] = req.TradeDate
	}
	if req.TsCode != "" {
		params["ts_code"] = req.TsCode
	}

	fields := []string{"trade_date", "ts_code", "exalter", "side", "buy", "buy_rate", "sell", "sell_rate", "net_buy", "reason"}

	var result struct {
		Fields []string                 `json:"fields"`
		Items  []map[string]interface{} `json:"items"`
	}

	if err := client.CallAPIFlexible(ctx, "top_inst", params, fields, &result); err != nil {
		return nil, err
	}
	items := make([]TopInstItem, len(result.Items))
	for i, item := range result.Items {
		// 处理 trade_date 的简单类型
		tradeDate, ok := item["trade_date"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 trade_date 类型")
		}
		// 处理 ts_code 的简单类型
		tsCode, ok := item["ts_code"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 ts_code 类型")
		}
		// 处理 exalter 的简单类型
		exalter, ok := item["exalter"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 exalter 类型")
		}
		// 处理 side 的简单类型
		side, ok := item["side"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 side 类型")
		}
		// 处理 buy 的简单类型
		buy, ok := item["buy"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 buy 类型")
		}
		// 处理 buy_rate 的简单类型
		buyRate, ok := item["buy_rate"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 buy_rate 类型")
		}
		// 处理 sell 的简单类型
		sell, ok := item["sell"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 sell 类型")
		}
		// 处理 sell_rate 的简单类型
		sellRate, ok := item["sell_rate"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 sell_rate 类型")
		}
		// 处理 net_buy 的简单类型
		netBuy, ok := item["net_buy"].(float64)
		if !ok {
			return nil, fmt.Errorf("无效的 net_buy 类型")
		}
		// 处理 reason 的简单类型
		reason, ok := item["reason"].(string)
		if !ok {
			return nil, fmt.Errorf("无效的 reason 类型")
		}
		items[i] = TopInstItem{
			TradeDate: tradeDate,
			TsCode: tsCode,
			Exalter: exalter,
			Side: side,
			Buy: buy,
			BuyRate: buyRate,
			Sell: sell,
			SellRate: sellRate,
			NetBuy: netBuy,
			Reason: reason,
		}
	}

	return items, nil
}
